//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSData;

@interface ADLAndroidCamera2Image : NSObject
{
    int _width;
    int _height;
    int _format;
    int _orientation;
    int _deviceOrientation;
    NSData *_planeY;
    NSData *_planeCb;
    NSData *_planeCr;
    long long _timestamp;
}

+ (id)AndroidCamera2ImageWithPlaneY:(id)arg1 planeCb:(id)arg2 planeCr:(id)arg3 width:(int)arg4 height:(int)arg5 format:(int)arg6 orientation:(int)arg7 deviceOrientation:(int)arg8 timestamp:(long long)arg9;
@property(readonly, nonatomic) long long timestamp; // @synthesize timestamp=_timestamp;
@property(readonly, nonatomic) int deviceOrientation; // @synthesize deviceOrientation=_deviceOrientation;
@property(readonly, nonatomic) int orientation; // @synthesize orientation=_orientation;
@property(readonly, nonatomic) int format; // @synthesize format=_format;
@property(readonly, nonatomic) int height; // @synthesize height=_height;
@property(readonly, nonatomic) int width; // @synthesize width=_width;
@property(readonly, nonatomic) NSData *planeCr; // @synthesize planeCr=_planeCr;
@property(readonly, nonatomic) NSData *planeCb; // @synthesize planeCb=_planeCb;
@property(readonly, nonatomic) NSData *planeY; // @synthesize planeY=_planeY;
- (void).cxx_destruct;
- (id)description;
- (id)initWithPlaneY:(id)arg1 planeCb:(id)arg2 planeCr:(id)arg3 width:(int)arg4 height:(int)arg5 format:(int)arg6 orientation:(int)arg7 deviceOrientation:(int)arg8 timestamp:(long long)arg9;

@end

