//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class ADLAuthDetails, ADLVideoStreamDescriptor, NSNumber, NSString;

@interface ADLConnectionDescriptor : NSObject
{
    _Bool _autoPublishVideo;
    _Bool _autoPublishAudio;
    ADLVideoStreamDescriptor *_videoStream;
    ADLAuthDetails *_authDetails;
    NSNumber *_appId;
    NSString *_scopeId;
    NSString *_url;
    NSString *_endpointDetails;
}

+ (id)ConnectionDescriptorWithVideoStream:(id)arg1 authDetails:(id)arg2 autoPublishVideo:(_Bool)arg3 autoPublishAudio:(_Bool)arg4 appId:(id)arg5 scopeId:(id)arg6 url:(id)arg7 endpointDetails:(id)arg8;
@property(readonly, nonatomic) NSString *endpointDetails; // @synthesize endpointDetails=_endpointDetails;
@property(readonly, nonatomic) NSString *url; // @synthesize url=_url;
@property(readonly, nonatomic) NSString *scopeId; // @synthesize scopeId=_scopeId;
@property(readonly, nonatomic) NSNumber *appId; // @synthesize appId=_appId;
@property(readonly, nonatomic) _Bool autoPublishAudio; // @synthesize autoPublishAudio=_autoPublishAudio;
@property(readonly, nonatomic) _Bool autoPublishVideo; // @synthesize autoPublishVideo=_autoPublishVideo;
@property(readonly, nonatomic) ADLAuthDetails *authDetails; // @synthesize authDetails=_authDetails;
@property(readonly, nonatomic) ADLVideoStreamDescriptor *videoStream; // @synthesize videoStream=_videoStream;
- (void).cxx_destruct;
- (id)description;
- (id)initWithVideoStream:(id)arg1 authDetails:(id)arg2 autoPublishVideo:(_Bool)arg3 autoPublishAudio:(_Bool)arg4 appId:(id)arg5 scopeId:(id)arg6 url:(id)arg7 endpointDetails:(id)arg8;

@end

