//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@class NSString;

@protocol ADLNumberResponder
- (void)onError:(int)arg1 message:(NSString *)arg2;
- (void)onCompletion:(int)arg1;
@end

