//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface ADLRenderContext : NSObject
{
    int _texY;
    int _texU;
    int _texV;
}

+ (id)RenderContextWithTexY:(int)arg1 texU:(int)arg2 texV:(int)arg3;
@property(readonly, nonatomic) int texV; // @synthesize texV=_texV;
@property(readonly, nonatomic) int texU; // @synthesize texU=_texU;
@property(readonly, nonatomic) int texY; // @synthesize texY=_texY;
- (id)description;
- (id)initWithTexY:(int)arg1 texU:(int)arg2 texV:(int)arg3;

@end

