//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "ADLServiceListener.h"

@interface ADLServiceListenerCppProxy : NSObject <ADLServiceListener>
{
    struct Handle<std::__1::shared_ptr<addlive::ServiceListener>, std::__1::shared_ptr<addlive::ServiceListener>> _cppRefHandle;
}

- (id).cxx_construct;
- (void).cxx_destruct;
- (void)onSubscribersCountChanged:(id)arg1;
- (void)onSpeechActivity:(id)arg1;
- (void)onMediaStreamFailure:(id)arg1;
- (void)onMicGain:(id)arg1;
- (void)onMicActivity:(id)arg1;
- (void)onDeviceListChanged:(id)arg1;
- (void)onMediaIssue:(id)arg1;
- (void)onMediaTransportTypeChanged:(id)arg1;
- (void)onMessage:(id)arg1;
- (void)onMediaStats:(id)arg1;
- (void)onMediaStreamEvent:(id)arg1;
- (void)onUserEvent:(id)arg1;
- (void)onSessionReconnected:(id)arg1;
- (void)onConnectionLost:(id)arg1;
- (void)onVideoFrameSizeChanged:(id)arg1;
- (id)initWithCpp:(const shared_ptr_5fdff3df *)arg1;

@end

