//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface ADLService : NSObject
{
    struct Handle<std::__1::shared_ptr<addlive::Service>, std::__1::shared_ptr<addlive::Service>> _cppRefHandle;
}

+ (void)androidFini;
+ (void)androidInit:(void *)arg1;
+ (id)create:(long long)arg1;
- (id).cxx_construct;
- (void).cxx_destruct;
- (void)injectFrame3:(id)arg1;
- (void)injectFrame2:(id)arg1 width:(int)arg2 height:(int)arg3 format:(int)arg4 orientation:(int)arg5 deviceOrientation:(int)arg6 timestamp:(long long)arg7;
- (void)injectFrame:(long long)arg1;
- (void)draw:(int)arg1 context:(id)arg2 top:(int)arg3 left:(int)arg4 bottom:(int)arg5 right:(int)arg6;
- (void)stopRender:(id)arg1 rendererId:(int)arg2;
- (void)startDirectRender:(id)arg1 videoSinkId:(id)arg2 callback:(id)arg3;
- (void)startRender:(id)arg1 videoSinkId:(id)arg2 filters:(id)arg3 mirror:(_Bool)arg4 context:(long long)arg5 callback:(id)arg6;
- (void)flushEvents:(id)arg1 key:(id)arg2 expiryTimestamp:(long long)arg3;
- (void)startEventsTracking:(id)arg1 eventsFile:(id)arg2;
- (void)networkTest:(id)arg1 desc:(id)arg2;
- (void)sendMessage:(id)arg1 scopeId:(id)arg2 message:(id)arg3 userId:(id)arg4;
- (void)unrestrictMediaReception:(id)arg1 scopeId:(id)arg2 mediaType:(long long)arg3;
- (void)restrictMediaReception:(id)arg1 scopeId:(id)arg2 mediaType:(long long)arg3 senders:(id)arg4;
- (void)setProxyCredentials:(id)arg1 username:(id)arg2 password:(id)arg3;
- (void)setProxyServer:(id)arg1 proxyType:(id)arg2 proxyHost:(id)arg3 proxyPort:(int)arg4;
- (void)setProperty:(id)arg1 key:(id)arg2 value:(id)arg3;
- (void)getProperty:(id)arg1 key:(id)arg2;
- (void)reconfigureVideo:(id)arg1 scopeId:(id)arg2 videoDesc:(id)arg3;
- (void)getLogFileTag:(id)arg1;
- (void)monitorSpeechActivity:(id)arg1 scopeId:(id)arg2 enabled:(_Bool)arg3;
- (void)monitorMicActivity:(id)arg1 enabled:(_Bool)arg2;
- (void)stopMeasuringStatistics:(id)arg1 scopeId:(id)arg2;
- (void)startMeasuringStatistics:(id)arg1 scopeId:(id)arg2 intervalSec:(int)arg3;
- (void)unpublish:(id)arg1 scopeId:(id)arg2 mediaType:(long long)arg3;
- (void)publish:(id)arg1 scopeId:(id)arg2 mediaType:(long long)arg3 params:(id)arg4;
- (void)disconnect:(id)arg1 scopeId:(id)arg2 timeoutMs:(int)arg3;
- (void)connect:(id)arg1 desc:(id)arg2;
- (void)stopLocalVideo:(id)arg1;
- (void)startLocalVideo:(id)arg1;
- (void)setMicrophoneVolume:(id)arg1 volume:(int)arg2;
- (void)getMicrophoneVolume:(id)arg1;
- (void)setSpeakersVolume:(id)arg1 volume:(int)arg2;
- (void)getSpeakersVolume:(id)arg1;
- (void)getAudioOutputDeviceNames:(id)arg1;
- (void)setAudioOutputDevice:(id)arg1 devId:(id)arg2;
- (void)getAudioOutputDevice:(id)arg1;
- (void)getAudioCaptureDeviceNames:(id)arg1;
- (void)setAudioCaptureDevice:(id)arg1 devId:(id)arg2;
- (void)getAudioCaptureDevice:(id)arg1;
- (void)getVideoCaptureDeviceNames:(id)arg1;
- (void)setVideoCaptureDevice:(id)arg1 devId:(id)arg2;
- (void)getVideoCaptureDevice:(id)arg1;
- (void)getScreenCaptureSources:(id)arg1;
- (void)setApplicationId:(id)arg1 appId:(long long)arg2;
- (void)getVersion:(id)arg1;
- (void)removeListener:(id)arg1;
- (void)addListener:(id)arg1;
- (void)dispose;
- (id)initWithCpp:(const shared_ptr_756dba43 *)arg1;

@end

