//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "ADLVoidResponder.h"

@interface ADLVoidResponderCppProxy : NSObject <ADLVoidResponder>
{
    struct Handle<std::__1::shared_ptr<addlive::VoidResponder>, std::__1::shared_ptr<addlive::VoidResponder>> _cppRefHandle;
}

- (id).cxx_construct;
- (void).cxx_destruct;
- (void)onError:(int)arg1 message:(id)arg2;
- (void)onCompletion;
- (id)initWithCpp:(const shared_ptr_c0f0acb2 *)arg1;

@end

