//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "ALServiceStub.h"

@class ADLService, NSMutableArray, NSMutableDictionary, NSNotificationCenter;

@interface ALServiceStubDevice : NSObject <ALServiceStub>
{
    ADLService *_svc;
    NSMutableArray *_listeners;
    NSNotificationCenter *_notificationCenter;
    _Bool _logInteractions;
    NSMutableDictionary *activeConnections;
    CDUnknownBlockType logHandler;
}

@property(copy, nonatomic) CDUnknownBlockType logHandler; // @synthesize logHandler;
@property(retain, nonatomic) NSMutableDictionary *activeConnections; // @synthesize activeConnections;
- (void).cxx_destruct;
- (void)injectFrame:(id)arg1;
- (void)handleConnectionLostEvent:(id)arg1;
- (void)handleMediaStreamEvent:(id)arg1;
- (void)handleUserEvent:(id)arg1;
- (void)onSubscribersCountChanged:(id)arg1;
- (void)onSpeechActivity:(id)arg1;
- (void)onMediaStreamFailure:(id)arg1;
- (void)onMicGain:(id)arg1;
- (void)onMicActivity:(id)arg1;
- (void)onDeviceListChanged:(id)arg1;
- (void)onMediaIssue:(id)arg1;
- (void)onMediaTransportTypeChanged:(id)arg1;
- (void)onMessage:(id)arg1;
- (void)onMediaStats:(id)arg1;
- (void)onMediaStreamEvent:(id)arg1;
- (void)onUserEvent:(id)arg1;
- (void)onSessionReconnected:(id)arg1;
- (void)onConnectionLost:(id)arg1;
- (void)onVideoFrameSizeChanged:(id)arg1;
- (void)fireEvent:(SEL)arg1 with:(id)arg2;
- (void)handleEvent:(id)arg1;
- (void)handleResponse:(id)arg1;
- (void)draw:(id)arg1;
- (void)stopRender:(id)arg1;
- (void)directRenderSink:(id)arg1 withResponder:(id)arg2;
- (void)renderSink:(id)arg1 withResponder:(id)arg2;
- (void)removeServiceListener:(id)arg1;
- (void)addServiceListener:(id)arg1;
- (id)getNativeServiceObject;
- (void)disposeInternal;
- (void)dispose;
- (id)initWithOptions:(id)arg1;

@end

