//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSFileManager.h"

@interface NSFileManager (ExtendedAttributes)
- (id)dataForExtendedAttribute:(id)arg1 ofItemAtPath:(id)arg2 error:(id *)arg3;
- (void)setData:(id)arg1 forExtendedAttribute:(id)arg2 ofItemAtPath:(id)arg3 error:(id *)arg4;
@end

