//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSURL.h"

@interface NSURL (SCAdditions)
+ (id)sc_uniqueMP4FileURLInTemporaryDirectory;
+ (id)sc_uniqueJPGFileURLInTemporaryDirectory;
+ (id)sc_fileURLInTemporaryDirectoryWithFilename:(id)arg1 extension:(id)arg2;
+ (id)sc_fileURLInTemporaryDirectoryWithFilename:(id)arg1;
@end

