//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSURL.h"

@interface NSURL (Utils)
+ (id)percentEncodedString:(id)arg1;
+ (id)stringFromQueryParameters:(id)arg1;
+ (struct _NSRange)_rangeOfValueForParameter:(id)arg1 endpoint:(id)arg2;
- (id)updateParametersWithURL:(id)arg1 restrictedParameters:(id)arg2;
- (id)updateParametersWithURL:(id)arg1;
- (id)queryParametersDecoded:(_Bool)arg1 lowercased:(_Bool)arg2;
- (id)suffixWithoutDomain;
@end

