//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "PreviewViewController.h"

@interface PreviewViewController (SCScreenshot)
- (void)getOverlayImageForVideoMediaAsynchronouslyShouldForceLandscapeDirection:(_Bool)arg1 shouldGenerateVideoThumbnailImageWithOverlay:(_Bool)arg2 callbackQueue:(id)arg3 completionBlock:(CDUnknownBlockType)arg4;
- (void)getScreenshotAsynchronouslyWithOriginalImageIncluded:(_Bool)arg1 filteredImageIncluded:(_Bool)arg2 videoOverlayImageIncluded:(_Bool)arg3 framingIncluded:(_Bool)arg4 captionIncluded:(_Bool)arg5 filterOverlayImageIncluded:(_Bool)arg6 shouldForceLandscapeDirection:(_Bool)arg7 shouldGenerateOverlayImageForMask:(_Bool)arg8 shouldGenerateVideoThumbnailImageWithOverlay:(_Bool)arg9 callbackQueue:(id)arg10 completionBlock:(CDUnknownBlockType)arg11;
- (void)getScreenshotAsynchronouslyWithCallbackQueue:(id)arg1 shouldForceLandscapeDirection:(_Bool)arg2 completionBlock:(CDUnknownBlockType)arg3;
@end

