//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SCAUserTrackedEvent.h"

#import "NamedEvent.h"

@class NSNumber, NSString;

@interface SCAChatPageView : SCAUserTrackedEvent <NamedEvent>
{
    NSNumber *viewTimeSec;
    NSString *recipientId;
}

+ (id)copy:(id)arg1;
+ (id)create;
- (void).cxx_destruct;
- (id)asDictionary;
- (id)getRecipientId;
- (void)setRecipientId:(id)arg1;
- (double)getViewTimeSec;
- (void)setViewTimeSec:(double)arg1;
- (id)getEventName;
- (id)init;

@end

