//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SCAUserTrackedEvent.h"

#import "NamedEvent.h"

@class NSNumber, NSString;

@interface SCAChatChatSend : SCAUserTrackedEvent <NamedEvent>
{
    NSNumber *charCount;
    NSNumber *positionIndex;
    NSNumber *noteTimeSec;
    NSNumber *batchStackSize;
    long long mediaType;
    long long source;
    long long messageType;
    long long drawerViewMode;
    NSString *additional_info;
    NSString *stickerId;
    NSString *section;
}

+ (id)copy:(id)arg1;
+ (id)create;
- (void).cxx_destruct;
- (id)asDictionary;
- (id)getSection;
- (void)setSection:(id)arg1;
- (id)getStickerId;
- (void)setStickerId:(id)arg1;
- (id)getAdditional_info;
- (void)setAdditional_info:(id)arg1;
- (long long)getDrawerViewMode;
- (void)setDrawerViewMode:(long long)arg1;
- (long long)getMessageType;
- (void)setMessageType:(long long)arg1;
- (long long)getSource;
- (void)setSource:(long long)arg1;
- (long long)getMediaType;
- (void)setMediaType:(long long)arg1;
- (long long)getBatchStackSize;
- (void)setBatchStackSize:(long long)arg1;
- (double)getNoteTimeSec;
- (void)setNoteTimeSec:(double)arg1;
- (long long)getPositionIndex;
- (void)setPositionIndex:(long long)arg1;
- (long long)getCharCount;
- (void)setCharCount:(long long)arg1;
- (id)getEventName;
- (id)init;

@end

