//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SCAUserTrackedEvent.h"

#import "NamedEvent.h"

@class NSNumber;

@interface SCACameraPageView : SCAUserTrackedEvent <NamedEvent>
{
    NSNumber *filterGeolensCount;
    NSNumber *filterLensCount;
    NSNumber *filterGeofilterCount;
    NSNumber *filterLensStoreCount;
    NSNumber *withGeolocation;
    NSNumber *viewTimeSec;
    NSNumber *withFilterLensSwipe;
    long long pageName;
    long long exitEvent;
}

+ (id)copy:(id)arg1;
+ (id)create;
- (void).cxx_destruct;
- (id)asDictionary;
- (long long)getExitEvent;
- (void)setExitEvent:(long long)arg1;
- (long long)getPageName;
- (void)setPageName:(long long)arg1;
- (_Bool)getWithFilterLensSwipe;
- (void)setWithFilterLensSwipe:(_Bool)arg1;
- (double)getViewTimeSec;
- (void)setViewTimeSec:(double)arg1;
- (_Bool)getWithGeolocation;
- (void)setWithGeolocation:(_Bool)arg1;
- (long long)getFilterLensStoreCount;
- (void)setFilterLensStoreCount:(long long)arg1;
- (long long)getFilterGeofilterCount;
- (void)setFilterGeofilterCount:(long long)arg1;
- (long long)getFilterLensCount;
- (void)setFilterLensCount:(long long)arg1;
- (long long)getFilterGeolensCount;
- (void)setFilterGeolensCount:(long long)arg1;
- (id)getEventName;
- (id)init;

@end

