//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SCAUserTrackedEvent.h"

#import "NamedEvent.h"

@class NSString;

@interface SCADiscoverAdShareLink : SCAUserTrackedEvent <NamedEvent>
{
    long long pageSection;
    NSString *publisherId;
    NSString *editionId;
    NSString *adsnapId;
    NSString *adId;
    NSString *adsnapPlacementId;
    NSString *adsnapLineItemId;
}

+ (id)copy:(id)arg1;
+ (id)create;
- (void).cxx_destruct;
- (id)asDictionary;
- (id)getAdsnapLineItemId;
- (void)setAdsnapLineItemId:(id)arg1;
- (id)getAdsnapPlacementId;
- (void)setAdsnapPlacementId:(id)arg1;
- (id)getAdId;
- (void)setAdId:(id)arg1;
- (id)getAdsnapId;
- (void)setAdsnapId:(id)arg1;
- (id)getEditionId;
- (void)setEditionId:(id)arg1;
- (id)getPublisherId;
- (void)setPublisherId:(id)arg1;
- (long long)getPageSection;
- (void)setPageSection:(long long)arg1;
- (id)getEventName;
- (id)init;

@end

