//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSCacheDelegate.h"
#import "NSCoding.h"

@class NSArray, NSDictionary, NSMutableDictionary, NSString, SCAdIndustryExclusionManager, SCAdInteractionTracker, SCAdManagerConfiguration, SCAdMediaFetchErrorTracker, SCAdMediaRenditionSelector, SCAdRequestQueue, SCAdSources, SCAdThirdPartyTrackUrlCreator, SCAdTrackInfoData;

@interface SCAdManager : NSObject <NSCoding, NSCacheDelegate>
{
    NSMutableDictionary *_adProducts;
    SCAdManagerConfiguration *_configuration;
    NSDictionary *_userTargeting;
    NSArray *_allIndustries;
    SCAdTrackInfoData *_adTrackInfoData;
    SCAdMediaFetchErrorTracker *_downloadTracker;
    SCAdIndustryExclusionManager *_industryExclusionManager;
    SCAdMediaRenditionSelector *_adMediaRenditionSelector;
    NSString *_sessionId;
    NSString *_sessionTargetingString;
    NSMutableDictionary *_controllers;
    SCAdRequestQueue *_adRequestQueue;
    SCAdThirdPartyTrackUrlCreator *_adThirdPartyTrackUrlCreator;
    SCAdSources *_adSources;
    SCAdInteractionTracker *_adInteractionTracker;
    NSMutableDictionary *_primaryAdSourceResponses;
    NSMutableDictionary *_fallbackAdSourceResponses;
    NSMutableDictionary *_adSourceUsedForAdPlacement;
    NSString *_sessionID;
    NSString *_sessionTargeting;
}

+ (id)path;
+ (_Bool)initialized;
+ (id)shared;
@property(retain, nonatomic) NSString *sessionTargeting; // @synthesize sessionTargeting=_sessionTargeting;
@property(retain, nonatomic) NSString *sessionID; // @synthesize sessionID=_sessionID;
@property(retain, nonatomic) NSMutableDictionary *adSourceUsedForAdPlacement; // @synthesize adSourceUsedForAdPlacement=_adSourceUsedForAdPlacement;
@property(retain, nonatomic) NSMutableDictionary *fallbackAdSourceResponses; // @synthesize fallbackAdSourceResponses=_fallbackAdSourceResponses;
@property(retain, nonatomic) NSMutableDictionary *primaryAdSourceResponses; // @synthesize primaryAdSourceResponses=_primaryAdSourceResponses;
@property(retain, nonatomic) SCAdInteractionTracker *adInteractionTracker; // @synthesize adInteractionTracker=_adInteractionTracker;
@property(retain, nonatomic) SCAdSources *adSources; // @synthesize adSources=_adSources;
@property(retain, nonatomic) SCAdThirdPartyTrackUrlCreator *adThirdPartyTrackUrlCreator; // @synthesize adThirdPartyTrackUrlCreator=_adThirdPartyTrackUrlCreator;
@property(retain, nonatomic) SCAdRequestQueue *adRequestQueue; // @synthesize adRequestQueue=_adRequestQueue;
@property(retain, nonatomic) NSMutableDictionary *controllers; // @synthesize controllers=_controllers;
@property(readonly, nonatomic) NSString *sessionTargetingString; // @synthesize sessionTargetingString=_sessionTargetingString;
@property(readonly, nonatomic) NSString *sessionId; // @synthesize sessionId=_sessionId;
@property(retain, nonatomic) SCAdMediaRenditionSelector *adMediaRenditionSelector; // @synthesize adMediaRenditionSelector=_adMediaRenditionSelector;
@property(retain, nonatomic) SCAdIndustryExclusionManager *industryExclusionManager; // @synthesize industryExclusionManager=_industryExclusionManager;
@property(retain, nonatomic) SCAdMediaFetchErrorTracker *downloadTracker; // @synthesize downloadTracker=_downloadTracker;
@property(retain, nonatomic) SCAdTrackInfoData *adTrackInfoData; // @synthesize adTrackInfoData=_adTrackInfoData;
@property(retain, nonatomic) NSArray *allIndustries; // @synthesize allIndustries=_allIndustries;
@property(retain, nonatomic) NSDictionary *userTargeting; // @synthesize userTargeting=_userTargeting;
@property(retain, nonatomic) SCAdManagerConfiguration *configuration; // @synthesize configuration=_configuration;
- (void).cxx_destruct;
- (_Bool)shouldMakeAdRequest:(id)arg1 adServerType:(long long)arg2;
- (id)configForAdProductType:(long long)arg1;
- (void)updateAdProducts:(id)arg1;
- (void)onApplicationDidBecomeActive;
- (void)onApplicationWillResignActive;
- (void)longformVideoViewed:(id)arg1 withViewDuration:(double)arg2 mediaDuration:(double)arg3;
- (void)topSnapVideoViewed:(id)arg1 withViewDuration:(double)arg2 mediaDuration:(double)arg3;
- (void)onHide:(id)arg1 adSnapPanel:(long long)arg2;
- (void)onPanelChanged:(id)arg1 from:(long long)arg2 to:(long long)arg3;
- (void)onShow:(id)arg1 adSnapPanel:(long long)arg2;
- (void)onPrimaryAdSourceResolutionResponse:(id)arg1 adController:(id)arg2;
- (void)onAdResolutionTimeout:(id)arg1 response:(id)arg2;
- (void)recordUnqualifiedImpressionForPlacement:(id)arg1;
- (void)recordQualifiedImpressionForPlacement:(id)arg1 ifDuration:(double)arg2 exceedsLimit:(double)arg3;
- (void)registerAdSkip:(id)arg1;
- (void)recordThirdPartyUrlImpressions:(id)arg1 impressionData:(id)arg2;
- (void)fireThirdPartyTrackingTrackUrls:(id)arg1 idfaApprovedTrackUrls:(id)arg2 trackRequestData:(id)arg3 adPlacement:(id)arg4 interaction:(id)arg5;
- (void)recordImpressionHelper:(id)arg1 impressionData:(id)arg2 adPlacement:(id)arg3;
- (void)recordUnqualifiedAdViewImpressionForAdResponse:(id)arg1;
- (id)createImpressionData:(double)arg1 mediaDuration:(double)arg2 interaction:(id)arg3;
- (void)recordAdViewImpressionForAdResponse:(id)arg1 withViewDuration:(double)arg2 mediaDuration:(double)arg3;
- (void)setController:(id)arg1 forAdPlacement:(id)arg2;
- (id)controllerForAdPlacement:(id)arg1;
- (void)removeControllerForAdPlacement:(id)arg1;
- (void)handleAdResponseDataForIndustryExclusion:(id)arg1 forAdUnit:(id)arg2;
- (id)getLogAdRequestTemplateWithAdController:(id)arg1 contextualTargeting:(id)arg2 industryTargetingParams:(id)arg3;
- (void)fireNextReadyAdRequestForAdUnitId:(id)arg1;
- (void)setAdPlacementAsResolvedHelper:(id)arg1 adResponse:(id)arg2 adSource:(id)arg3;
- (void)setAdPlacementAsResolved:(id)arg1 adResponse:(id)arg2 adSource:(id)arg3;
- (void)clearStoredResponses:(id)arg1;
- (id)getAdSourceForPlacement:(id)arg1;
- (void)setAdSourceForPlacement:(id)arg1 adSource:(id)arg2;
- (void)setPrimaryResponse:(id)arg1 adResponse:(id)arg2;
- (void)setFallbackResponse:(id)arg1 adResponse:(id)arg2;
- (id)getPrimaryResponse:(id)arg1;
- (id)getFallbackResponse:(id)arg1;
- (void)transformAdPlacementAsync:(id)arg1 withListener:(id)arg2;
- (void)ensureNonNilObjects;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)init;
- (void)updateConfig:(id)arg1 sessionID:(id)arg2 targetingString:(id)arg3;
- (id)getAdSourceInfoString;
- (void)updateAdSources:(id)arg1;
- (void)clear;
- (_Bool)saveState;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

