//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SCTextMediaCardView.h"

#import "SCAddressMediaCardViewModelDelegate.h"

@class NSAttributedString, NSString, SCDistanceView, UITapGestureRecognizer;

@interface SCAddressMediaCardView : SCTextMediaCardView <SCAddressMediaCardViewModelDelegate>
{
    UITapGestureRecognizer *_tapGestureRecognizer;
    NSAttributedString *_walkingText;
    NSAttributedString *_drivingText;
    SCDistanceView *_walkingView;
    SCDistanceView *_drivingView;
}

- (void).cxx_destruct;
- (void)handleTapOnAddress:(id)arg1;
- (void)onTap:(id)arg1;
- (void)dealloc;
- (void)_refreshDrivingView;
- (void)_refreshWalkingView;
- (void)_refreshSubtitleView;
- (void)setDrivingText:(id)arg1;
- (void)setWalkingText:(id)arg1;
- (void)setTitle:(id)arg1 walkingText:(id)arg2 drivingText:(id)arg3;
- (id)drivingView;
- (id)walkingView;
- (id)_addressMediaCardViewModel;
- (id)initWithViewModel:(id)arg1 backgroundColor:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

