//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSDictionary;

@interface SCAdProductConfig : NSObject
{
    long long _type;
    NSDictionary *_params;
}

@property(readonly, copy, nonatomic) NSDictionary *params; // @synthesize params=_params;
@property(readonly, nonatomic) long long type; // @synthesize type=_type;
- (void).cxx_destruct;
- (id)initWithSoju:(id)arg1;

@end

