//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SCAUserTrackedEvent.h"

#import "NamedEvent.h"

@class NSNumber, NSString;

@interface SCAFilterLensDownload : SCAUserTrackedEvent <NamedEvent>
{
    NSNumber *automaticDownload;
    NSNumber *downloadTimeSec;
    NSNumber *downloadIndexCount;
    NSNumber *downloadIndexPos;
    NSNumber *sizeByte;
    NSString *filterLensId;
}

+ (id)copy:(id)arg1;
+ (id)create;
- (void).cxx_destruct;
- (id)asDictionary;
- (id)getFilterLensId;
- (void)setFilterLensId:(id)arg1;
- (long long)getSizeByte;
- (void)setSizeByte:(long long)arg1;
- (long long)getDownloadIndexPos;
- (void)setDownloadIndexPos:(long long)arg1;
- (long long)getDownloadIndexCount;
- (void)setDownloadIndexCount:(long long)arg1;
- (double)getDownloadTimeSec;
- (void)setDownloadTimeSec:(double)arg1;
- (_Bool)getAutomaticDownload;
- (void)setAutomaticDownload:(_Bool)arg1;
- (id)getEventName;
- (id)init;

@end

