//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SCAUserTrackedEvent.h"

#import "NamedEvent.h"

@class NSNumber;

@interface SCAGallerySnapPreview : SCAUserTrackedEvent <NamedEvent>
{
    NSNumber *withEdit;
    NSNumber *withSave;
    NSNumber *withDelete;
    NSNumber *viewTimeSec;
    long long mediaType;
    long long galleryContextMenuSource;
}

+ (id)copy:(id)arg1;
+ (id)create;
- (void).cxx_destruct;
- (id)asDictionary;
- (long long)getGalleryContextMenuSource;
- (void)setGalleryContextMenuSource:(long long)arg1;
- (long long)getMediaType;
- (void)setMediaType:(long long)arg1;
- (double)getViewTimeSec;
- (void)setViewTimeSec:(double)arg1;
- (_Bool)getWithDelete;
- (void)setWithDelete:(_Bool)arg1;
- (_Bool)getWithSave;
- (void)setWithSave:(_Bool)arg1;
- (_Bool)getWithEdit;
- (void)setWithEdit:(_Bool)arg1;
- (id)getEventName;
- (id)init;

@end

