//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SCAUserTrackedEvent.h"

#import "NamedEvent.h"

@class NSNumber;

@interface SCAGalleryContextMenuSessionEnd : SCAUserTrackedEvent <NamedEvent>
{
    NSNumber *viewTimeSec;
    NSNumber *snapSendCount;
    NSNumber *storyCreateCount;
    NSNumber *storySendCount;
    NSNumber *storyPostCount;
    long long galleryTab;
}

+ (id)copy:(id)arg1;
+ (id)create;
- (void).cxx_destruct;
- (id)asDictionary;
- (long long)getGalleryTab;
- (void)setGalleryTab:(long long)arg1;
- (long long)getStoryPostCount;
- (void)setStoryPostCount:(long long)arg1;
- (long long)getStorySendCount;
- (void)setStorySendCount:(long long)arg1;
- (long long)getStoryCreateCount;
- (void)setStoryCreateCount:(long long)arg1;
- (long long)getSnapSendCount;
- (void)setSnapSendCount:(long long)arg1;
- (double)getViewTimeSec;
- (void)setViewTimeSec:(double)arg1;
- (id)getEventName;
- (id)init;

@end

