//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SCAUserTrackedEvent.h"

#import "NamedEvent.h"

@class NSNumber;

@interface SCAGeofilterGeofilterRequest : SCAUserTrackedEvent <NamedEvent>
{
    NSNumber *geofilterCount;
    NSNumber *geofilterGeofenceCount;
    NSNumber *geofilterSponsoredCount;
    NSNumber *geofenceMinAreaMeters;
    NSNumber *withGeolocation;
    NSNumber *withFilterSetting;
    NSNumber *locationAccuracyMeters;
}

+ (id)copy:(id)arg1;
+ (id)create;
- (void).cxx_destruct;
- (id)asDictionary;
- (long long)getLocationAccuracyMeters;
- (void)setLocationAccuracyMeters:(long long)arg1;
- (_Bool)getWithFilterSetting;
- (void)setWithFilterSetting:(_Bool)arg1;
- (_Bool)getWithGeolocation;
- (void)setWithGeolocation:(_Bool)arg1;
- (long long)getGeofenceMinAreaMeters;
- (void)setGeofenceMinAreaMeters:(long long)arg1;
- (long long)getGeofilterSponsoredCount;
- (void)setGeofilterSponsoredCount:(long long)arg1;
- (long long)getGeofilterGeofenceCount;
- (void)setGeofilterGeofenceCount:(long long)arg1;
- (long long)getGeofilterCount;
- (void)setGeofilterCount:(long long)arg1;
- (id)getEventName;
- (id)init;

@end

