//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableDictionary;

@interface SCAppNotificationProvider : NSObject
{
    NSMutableDictionary *_activeNotifications;
    NSMutableDictionary *_talkNotificationStartTimes;
    NSMutableDictionary *_notificationExpirationTimers;
    NSMutableDictionary *_knownContent;
    id <SCAppNotificationProviderDelegate> _backgroundDelegate;
    id <SCAppNotificationProviderDelegate> _foregroundDelegate;
}

+ (_Bool)isNotificationStillValid:(id)arg1;
+ (_Bool)isNotificationForReadContent:(id)arg1;
+ (id)knownContentKeyFromNotification:(id)arg1;
+ (id)keyFromNotification:(id)arg1;
+ (id)keyFromUserName:(id)arg1 withType:(id)arg2;
+ (id)sharedInstance;
@property(nonatomic) __weak id <SCAppNotificationProviderDelegate> foregroundDelegate; // @synthesize foregroundDelegate=_foregroundDelegate;
@property(nonatomic) __weak id <SCAppNotificationProviderDelegate> backgroundDelegate; // @synthesize backgroundDelegate=_backgroundDelegate;
- (void).cxx_destruct;
- (void)updateModelFromNotification:(id)arg1;
- (_Bool)hasNotificationAlreadyBeenProcessed:(id)arg1;
- (id)currentNotifications;
- (void)checkHasNotificationExpired:(id)arg1;
- (void)addToActiveNotificationExpirations:(id)arg1 withDuration:(double)arg2;
- (void)addNotification:(id)arg1;
- (void)removeNotification:(id)arg1;
- (void)applicationWillForeground:(id)arg1;
- (void)applicationDidBackground:(id)arg1;
- (id)delegateForAppState;
- (id)init;

@end

