//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SCAUserTrackedEvent.h"

#import "NamedEvent.h"

@class NSNumber;

@interface SCAProfileAddedMePageExit : SCAUserTrackedEvent <NamedEvent>
{
    NSNumber *totalRequestCount;
    NSNumber *totalRequestCountWithDisplayPic;
    NSNumber *newRequestCount;
    NSNumber *requestAcceptCount;
    NSNumber *requestAcceptCountWithDisplayPic;
    NSNumber *requestBlockCount;
    NSNumber *requestIgnoreCount;
    NSNumber *requestNameEditCount;
}

+ (id)copy:(id)arg1;
+ (id)create;
- (void).cxx_destruct;
- (id)asDictionary;
- (long long)getRequestNameEditCount;
- (void)setRequestNameEditCount:(long long)arg1;
- (long long)getRequestIgnoreCount;
- (void)setRequestIgnoreCount:(long long)arg1;
- (long long)getRequestBlockCount;
- (void)setRequestBlockCount:(long long)arg1;
- (long long)getRequestAcceptCountWithDisplayPic;
- (void)setRequestAcceptCountWithDisplayPic:(long long)arg1;
- (long long)getRequestAcceptCount;
- (void)setRequestAcceptCount:(long long)arg1;
- (long long)getNewRequestCount;
- (void)setNewRequestCount:(long long)arg1;
- (long long)getTotalRequestCountWithDisplayPic;
- (void)setTotalRequestCountWithDisplayPic:(long long)arg1;
- (long long)getTotalRequestCount;
- (void)setTotalRequestCount:(long long)arg1;
- (id)getEventName;
- (id)init;

@end

