//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SCAUserTrackedEvent.h"

#import "NamedEvent.h"

@interface SCARegistrationUserComplete : SCAUserTrackedEvent <NamedEvent>
{
    long long registrationVersion;
}

+ (id)copy:(id)arg1;
+ (id)create;
- (id)asDictionary;
- (long long)getRegistrationVersion;
- (void)setRegistrationVersion:(long long)arg1;
- (id)getEventName;
- (id)init;

@end

