//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SCAUserTrackedEvent.h"

#import "NamedEvent.h"

@class NSNumber;

@interface SCARegistrationUserInitialInfoSuccess : SCAUserTrackedEvent <NamedEvent>
{
    NSNumber *editBirthdayYear;
    NSNumber *editBirthdayMonth;
    NSNumber *editBirthdayDay;
    NSNumber *attemptCount;
    long long registrationVersion;
}

+ (id)copy:(id)arg1;
+ (id)create;
- (void).cxx_destruct;
- (id)asDictionary;
- (long long)getRegistrationVersion;
- (void)setRegistrationVersion:(long long)arg1;
- (long long)getAttemptCount;
- (void)setAttemptCount:(long long)arg1;
- (_Bool)getEditBirthdayDay;
- (void)setEditBirthdayDay:(_Bool)arg1;
- (_Bool)getEditBirthdayMonth;
- (void)setEditBirthdayMonth:(_Bool)arg1;
- (_Bool)getEditBirthdayYear;
- (void)setEditBirthdayYear:(_Bool)arg1;
- (id)getEventName;
- (id)init;

@end

