//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SCAUserTrackedEvent.h"

#import "NamedEvent.h"

@class NSNumber, NSString;

@interface SCAStoryStoryUnhide : SCAUserTrackedEvent <NamedEvent>
{
    NSNumber *viewLocation;
    long long storyType;
    NSString *posterId;
    NSString *geoFence;
    NSString *sponsor;
    NSString *additionalInfo;
}

+ (id)copy:(id)arg1;
+ (id)create;
- (void).cxx_destruct;
- (id)asDictionary;
- (id)getAdditionalInfo;
- (void)setAdditionalInfo:(id)arg1;
- (id)getSponsor;
- (void)setSponsor:(id)arg1;
- (id)getGeoFence;
- (void)setGeoFence:(id)arg1;
- (id)getPosterId;
- (void)setPosterId:(id)arg1;
- (long long)getStoryType;
- (void)setStoryType:(long long)arg1;
- (long long)getViewLocation;
- (void)setViewLocation:(long long)arg1;
- (id)getEventName;
- (id)init;

@end

