//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SCAUserTrackedEvent.h"

#import "NamedEvent.h"

@class NSString;

@interface SCAStorySnapRemove : SCAUserTrackedEvent <NamedEvent>
{
    long long reason;
    long long type;
    NSString *storyId;
}

+ (id)copy:(id)arg1;
+ (id)create;
- (void).cxx_destruct;
- (id)asDictionary;
- (id)getStoryId;
- (void)setStoryId:(id)arg1;
- (long long)getType;
- (void)setType:(long long)arg1;
- (long long)getReason;
- (void)setReason:(long long)arg1;
- (id)getEventName;
- (id)init;

@end

