//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SCAStoryCellViewBase.h"

#import "NamedEvent.h"

@class NSNumber, NSString;

@interface SCAStoryCellView : SCAStoryCellViewBase <NamedEvent>
{
    NSNumber *featuredSectionStoriesCount;
    NSNumber *featuredSectionDiscoverCount;
    NSNumber *subscriptionsSectionCount;
    NSString *featuredSectionContentIds;
    NSString *subscriptionsSectionPublisherIds;
}

+ (id)copy:(id)arg1;
+ (id)create;
- (void).cxx_destruct;
- (id)asDictionary;
- (id)getSubscriptionsSectionPublisherIds;
- (void)setSubscriptionsSectionPublisherIds:(id)arg1;
- (id)getFeaturedSectionContentIds;
- (void)setFeaturedSectionContentIds:(id)arg1;
- (long long)getSubscriptionsSectionCount;
- (void)setSubscriptionsSectionCount:(long long)arg1;
- (long long)getFeaturedSectionDiscoverCount;
- (void)setFeaturedSectionDiscoverCount:(long long)arg1;
- (long long)getFeaturedSectionStoriesCount;
- (void)setFeaturedSectionStoriesCount:(long long)arg1;
- (id)getEventName;
- (id)init;

@end

