//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString, SCAudioSession;

@protocol SCAudioSessionListener <NSObject>

@optional
- (void)audioSessionMediaServicesWereReset:(SCAudioSession *)arg1;
- (void)audioSessionRouteDidChangeReasonOldDeviceUnavailable:(SCAudioSession *)arg1;
- (void)audioSessionRouteDidChangeReasonNewDeviceAvailable:(SCAudioSession *)arg1;
- (void)audioSessionDidEndInterruption:(SCAudioSession *)arg1;
- (void)audioSessionDidBeginInterruption:(SCAudioSession *)arg1;
- (void)audioSession:(SCAudioSession *)arg1 didChangeVolume:(double)arg2;
- (void)audioSession:(SCAudioSession *)arg1 didChangeCategory:(NSString *)arg2 mode:(NSString *)arg3;
@end

