//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray;

@interface SCAudioNoteWaveformAnimation : NSObject
{
    NSArray *_waveformAnimationFrames;
}

+ (id)generateAnimationDataWithLinearPCMData:(id)arg1 sampleRate:(double)arg2;
+ (id)waveformAnimationWithAnimationData:(id)arg1;
- (void).cxx_destruct;
- (double)duration;
- (struct SCAudioNoteWaveformAnimationFrame)animationFrameForTime:(double)arg1;
- (id)initWithAnimationFrames:(id)arg1;

@end

