//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "UIGestureRecognizerDelegate.h"

@class NSMutableArray, NSString, UILongPressGestureRecognizer, UIView, UIViewController<SCSnapPlayContainer><SCChatCellGestureDelegate>;

@interface SCBubbleGestureManager : NSObject <UIGestureRecognizerDelegate>
{
    UIViewController<SCSnapPlayContainer><SCChatCellGestureDelegate> *_parentViewController;
    UIView *_containerView;
    UILongPressGestureRecognizer *_longPressGestureRecognizer;
    NSMutableArray *_bubbleGestureHandlers;
    id <NavigationDelegate> _navigationDelegate;
}

- (void).cxx_destruct;
- (_Bool)canHandleTouch:(id)arg1;
- (id)_gestureHandlerForPoint:(struct CGPoint)arg1;
- (void)_longPress:(id)arg1;
- (struct CGPoint)_convertFromActualFrameToEndFrameForPoint:(struct CGPoint)arg1;
- (void)handleBubbleDismissFullScreenWithGestureHandler:(id)arg1;
- (id)_gestureHandlerForBubbleView:(id)arg1;
- (void)handleBubbleFadeOut:(id)arg1;
- (id)addGestureHandlerForBubbleView:(id)arg1;
- (void)_initGestureRecognizers;
- (id)initWithParentViewController:(id)arg1 containerView:(id)arg2 navigationDelegate:(id)arg3;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

