//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableDictionary, NSString;

@interface SCCacheManager : NSObject
{
    _Bool _shouldSave;
    NSString *_keyCachePath;
    id <SCConcurrentPerforming> _queuePerformer;
    NSMutableDictionary *_memoryKeyMap;
    NSMutableDictionary *_diskKeyMap;
    NSMutableDictionary *_cacheMap;
}

+ (id)shared;
@property(retain, nonatomic) NSMutableDictionary *cacheMap; // @synthesize cacheMap=_cacheMap;
@property(retain, nonatomic) NSMutableDictionary *diskKeyMap; // @synthesize diskKeyMap=_diskKeyMap;
@property(retain, nonatomic) NSMutableDictionary *memoryKeyMap; // @synthesize memoryKeyMap=_memoryKeyMap;
@property(nonatomic) _Bool shouldSave; // @synthesize shouldSave=_shouldSave;
@property(retain, nonatomic) id <SCConcurrentPerforming> queuePerformer; // @synthesize queuePerformer=_queuePerformer;
- (void).cxx_destruct;
@property(readonly, nonatomic) NSString *keyCachePath; // @synthesize keyCachePath=_keyCachePath;
- (CDUnknownBlockType)didRemoveObjectFromDiskBlock;
- (CDUnknownBlockType)didRemoveObjectFromMemoryBlock;
- (id)syncGetAllEntriesForKind:(id)arg1;
- (void)removeMemoryKey:(id)arg1;
- (void)addMemoryKey:(id)arg1 forKind:(id)arg2 expirationDate:(id)arg3;
- (void)removeDiskKey:(id)arg1;
- (void)addDiskKey:(id)arg1 forKind:(id)arg2 expirationDate:(id)arg3;
- (void)removeAllDiskKeysExcept:(id)arg1;
- (_Bool)contains:(id)arg1 includingDiskLookup:(_Bool)arg2;
- (void)getAllKeysForKind:(id)arg1 block:(CDUnknownBlockType)arg2;
- (void)getAllEntriesForKind:(id)arg1 block:(CDUnknownBlockType)arg2;
- (void)removeCache:(id)arg1;
- (void)addCache:(id)arg1;
- (void)saveState;
- (id)initWithQueuePerformer:(id)arg1;

@end

