//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "PHPhotoLibraryChangeObserver.h"
#import "SCCameraRollWrapperProtocol.h"

@class NSArray, NSString, PHCachingImageManager, PHFetchResult;

@interface SCCameraRollImageManagerWrapper : NSObject <PHPhotoLibraryChangeObserver, SCCameraRollWrapperProtocol>
{
    PHCachingImageManager *_cachingImageManager;
    PHFetchResult *_assets;
    id <SCPerforming> _performer;
    NSArray *_imagesIdentifiers;
    long long _status;
}

@property long long status; // @synthesize status=_status;
@property(retain, nonatomic) NSArray *imagesIdentifiers; // @synthesize imagesIdentifiers=_imagesIdentifiers;
@property(retain, nonatomic) id <SCPerforming> performer; // @synthesize performer=_performer;
@property(retain, nonatomic) PHFetchResult *assets; // @synthesize assets=_assets;
- (void).cxx_destruct;
- (id)_getImageAtIndex:(unsigned long long)arg1 targetSize:(struct CGSize)arg2 options:(id)arg3 completion:(CDUnknownBlockType)arg4;
- (void)cancelImageLoadingWithId:(id)arg1;
- (id)getOriginalImageAtIndex:(unsigned long long)arg1 completion:(CDUnknownBlockType)arg2;
- (id)getThumbnailImageAtIndex:(unsigned long long)arg1 targetSize:(struct CGSize)arg2 completion:(CDUnknownBlockType)arg3;
- (id)imageIdentifierForItemAtIndex:(unsigned long long)arg1;
- (unsigned long long)imagesCount;
- (void)reloadAssetsIndexWithCompletion:(CDUnknownBlockType)arg1;
- (void)photoLibraryDidChange:(id)arg1;
- (void)preparePhotoManagerIfAllowed;
- (void)dealloc;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

