//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SCFrameableContainerView.h"

#import "SCImageProcessVideoPlaybackSessionListener.h"

@class AVPlayer, NSString, SCBaseChatMedia, SCCAEAGLView, SCImageProcessVideoPlaybackSession, UIImageView;

@interface SCChatBrowseVideoView : SCFrameableContainerView <SCImageProcessVideoPlaybackSessionListener>
{
    SCImageProcessVideoPlaybackSession *_videoPlaybackSession;
    AVPlayer *_player;
    SCCAEAGLView *_glView;
    UIImageView *_overlayView;
    UIImageView *_placeholderView;
    double _playerItemTimeScale;
    SCBaseChatMedia *_media;
    struct CGSize _glViewSize;
    _Bool _startPlayback;
    _Bool _shouldLoop;
    id _timeObserver;
    id <SCChatBrowseVideoViewDelegate> _delegate;
}

+ (void)enqueueReusableBrowseVideoView:(id)arg1;
+ (id)dequeueResuableBrowseVideoView;
@property(nonatomic) __weak id <SCChatBrowseVideoViewDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (struct CGSize)naturalContentSize;
- (void)videoPlaybackSession:(id)arg1 didRenderFrameAtTime:(CDStruct_1b6d18a9)arg2;
- (id)_playerForWaveformData:(id)arg1;
- (void)_removeTimeObserver;
- (void)_attachTimeObserver;
- (void)_configureVideoPlaybackSessionForVideoAsset:(id)arg1 audioDisabled:(_Bool)arg2 completionHandler:(CDUnknownBlockType)arg3;
- (void)prepareForReuse;
- (void)dealloc;
- (void)setVolume:(float)arg1;
- (void)stopPlayback;
- (void)resumePlayback;
- (void)startPlayback;
- (void)setShouldLoop:(_Bool)arg1;
- (void)_loadPlaceholderImage:(CDUnknownBlockType)arg1;
- (void)setPlaceholderForMedia:(id)arg1 completionHandler:(CDUnknownBlockType)arg2;
- (void)setupVideo;
- (void)layoutSubviews;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

