//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableArray, NSMutableDictionary, NSMutableSet, NSObject<OS_dispatch_queue>, NSString;

@interface SCChatMessageSender : NSObject
{
    NSObject<OS_dispatch_queue> *_dispatchQueue;
    NSMutableArray *_inflightMessages;
    NSMutableSet *_inflightMessageIds;
    NSMutableDictionary *_handlers;
    NSString *_conversationId;
}

@property(copy, nonatomic) NSString *conversationId; // @synthesize conversationId=_conversationId;
- (void).cxx_destruct;
- (id)updateResponseForAckedMessage:(id)arg1 response:(id)arg2 success:(_Bool)arg3;
- (id)sequenceNumbersForMessages:(id)arg1;
- (long long)resultForStatusCode:(long long)arg1;
- (id)writeResultFromResponse:(id)arg1;
- (id)messageResponseForAckedMessageId:(id)arg1 response:(id)arg2;
- (void)invokeHandlerForMessage:(id)arg1 result:(long long)arg2 response:(id)arg3;
- (void)handleAckedMessages:(id)arg1 result:(long long)arg2 response:(id)arg3;
- (id)messagesStringToSend;
- (void)httpSendInflightMessages;
- (void)httpSendChatMessage:(id)arg1 responseHandler:(CDUnknownBlockType)arg2;
- (void)sendChatMessage:(id)arg1 responseHandler:(CDUnknownBlockType)arg2;
- (id)initWithDispatchQueue:(id)arg1;
- (id)init;

@end

