//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SCChunkItem.h"

@class NSMutableDictionary, NSString;

@interface SCChunkLocalWebpageItem : SCChunkItem
{
    NSMutableDictionary *_itemsForVideoIds;
    NSString *_htmlFilename;
}

@property(copy, nonatomic) NSString *htmlFilename; // @synthesize htmlFilename=_htmlFilename;
@property(retain, nonatomic) NSMutableDictionary *itemsForVideoIds; // @synthesize itemsForVideoIds=_itemsForVideoIds;
- (void).cxx_destruct;
- (void)clearItems;
- (id)itemForVideoId:(id)arg1;
- (void)saveMediaToCache;
- (id)cacheMediaIds;
- (id)localHTMLURL;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)initWithJSONDictionary:(id)arg1 chunkDictionary:(id)arg2;

@end

