//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "SCChatViewLifeCycleListener.h"
#import "SCChatViewModelListener.h"
#import "SCLocationControllerDelegate.h"

@class NSString, SCChatViewModelForChat, SCLocationController;

@interface SCChatLocationUpdater : NSObject <SCLocationControllerDelegate, SCChatViewLifeCycleListener, SCChatViewModelListener>
{
    SCChatViewModelForChat *_chatViewModel;
    SCLocationController *_locationController;
    CDStruct_2c43369c _currentLocation;
    _Bool _updatingLocation;
}

- (void).cxx_destruct;
- (void)didViewModelsChange;
- (void)newMessageAddedAtIndexPath:(id)arg1;
- (void)didMessagesAddAtIndexPaths:(id)arg1;
- (void)locationController:(id)arg1 didFailWithError:(id)arg2;
- (void)locationController:(id)arg1 didUpdateLocation:(id)arg2;
- (void)_stopUpdatingLocation;
- (void)_startUpdatingLocation;
- (void)viewWillResignActive;
- (void)viewDidBecomeActive;
- (void)viewWillEnterBackground;
- (void)viewDidSwipeOut;
- (void)viewDidSwipeIn;
- (void)setChatViewModel:(id)arg1;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

