//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SCAlertViewActionButtonController.h"

@interface SCChangeableButtonController : SCAlertViewActionButtonController
{
}

+ (id)actionWithState:(unsigned long long)arg1 configBlock:(CDUnknownBlockType)arg2 actionHandler:(CDUnknownBlockType)arg3;
- (id)initWithState:(unsigned long long)arg1 configBlock:(CDUnknownBlockType)arg2 actionHandler:(CDUnknownBlockType)arg3;

@end

