//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "SCChatStickerUseHistory.h"

@class NSString;

@interface SCChatStickerUseHistory : NSObject <SCChatStickerUseHistory>
{
    long long _dayOfUse;
    long long _numOfUse;
}

@property(readonly, nonatomic) long long numOfUse; // @synthesize numOfUse=_numOfUse;
@property(readonly, nonatomic) long long dayOfUse; // @synthesize dayOfUse=_dayOfUse;
@property(readonly, copy) NSString *description;
- (_Bool)isEqual:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)initWithDayOfUse:(long long)arg1 numOfUse:(long long)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

