//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SCChatMediaDrawerBaseMedia.h"

@interface SCChatMediaDrawerImage : SCChatMediaDrawerBaseMedia
{
}

- (_Bool)shouldResizeBeforeUploading;
- (void)prepareUploadDataForMedia:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)prepareUploadDataForMessage:(id)arg1 withCompletion:(CDUnknownBlockType)arg2;
- (void)cancelThumbnailFetchRequest;
- (void)fetchOriginalImageDataWithCompletion:(CDUnknownBlockType)arg1;
- (void)fetchImageWithSize:(struct CGSize)arg1 thumbnailType:(long long)arg2 allowLowQuality:(_Bool)arg3 userSession:(id)arg4 completion:(CDUnknownBlockType)arg5;
- (id)initWithPHAsset:(id)arg1;
- (id)initWithALAsset:(id)arg1;

@end

