//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "SCChatInputAccessory.h"
#import "SCTimeProfilable.h"
#import "SendSnapNavigationControllerDelegate.h"
#import "UINavigationControllerDelegate.h"

@class NSString, SCUserSession, UIButton, UIView, UIViewController;

@interface SCChatInputSnapAccessory : NSObject <SendSnapNavigationControllerDelegate, UINavigationControllerDelegate, SCTimeProfilable, SCChatInputAccessory>
{
    id <SCChatInputProvider> _inputProvider;
    SCUserSession *_userSession;
    UIViewController *_parentViewController;
    UIView *_miniatureView;
    UIButton *_snapButton;
    id <UINavigationControllerDelegate> _oldNavigationDelegate;
}

+ (long long)context;
+ (id)profiledSelectorNames;
- (void).cxx_destruct;
- (void)_dismissPreviewIfPresented;
- (void)_presentInChatSnapWithReplyUsername:(id)arg1;
- (id)navigationController:(id)arg1 animationControllerForOperation:(long long)arg2 fromViewController:(id)arg3 toViewController:(id)arg4;
- (id)navigationController:(id)arg1 interactionControllerForAnimationController:(id)arg2;
- (void)presentPreviewforInChatImage:(id)arg1;
- (void)didComeFromCameraWithoutSendingSnap;
- (void)didPostStoryWithoutSendingSnap;
- (void)didSendToGallery;
- (void)didSendChatMessage;
- (void)didSendSnap:(id)arg1;
- (void)_didSendSnapOrChatMessage;
- (void)didCancelFromPreview:(id)arg1;
- (void)_didPressSnapButton:(id)arg1;
- (id)miniatureView;
- (void)dealloc;
- (id)initWithInputProvider:(id)arg1 userSession:(id)arg2 parentViewController:(id)arg3;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(nonatomic) _Bool fullscreenImageUsed;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

