//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "SCChatDrawerLogger.h"
#import "SCChatInputAccessory.h"
#import "SCChatStickerFavoritesDelegate.h"
#import "SCChatStickerManagerDelegate.h"
#import "SCChatStickerSearchDelegate.h"
#import "SCTimeProfilable.h"
#import "UICollectionViewDataSource.h"
#import "UICollectionViewDelegateFlowLayout.h"
#import "UIGestureRecognizerDelegate.h"

@class NSString, SCChatStickerCollectionViewFlowLayout, SCChatStickerScrollBar, UIActivityIndicatorView, UIButton, UICollectionView, UIPanGestureRecognizer, UIView;

@interface SCChatInputStickerAccessory : NSObject <UICollectionViewDataSource, UICollectionViewDelegateFlowLayout, UIGestureRecognizerDelegate, SCChatStickerManagerDelegate, SCChatStickerSearchDelegate, SCChatStickerFavoritesDelegate, SCTimeProfilable, SCChatInputAccessory, SCChatDrawerLogger>
{
    id <SCChatInputProvider> _inputProvider;
    UIButton *_miniatureView;
    UIView *_drawerView;
    double _drawerHeight;
    SCChatStickerScrollBar *_scrollBar;
    SCChatStickerCollectionViewFlowLayout *_sectionFlowLayout;
    UICollectionView *_sectionCollectionView;
    UIActivityIndicatorView *_activityView;
    UIPanGestureRecognizer *_panGestureRecognizer;
    _Bool _notifySearchResults;
    long long _sentItems;
    _Bool _fullscreenImageUsed;
    id <SCChatDrawerSender> _sender;
}

+ (long long)context;
+ (id)profiledSelectorNames;
@property(nonatomic) __weak id <SCChatDrawerSender> sender; // @synthesize sender=_sender;
@property(nonatomic) _Bool fullscreenImageUsed; // @synthesize fullscreenImageUsed=_fullscreenImageUsed;
- (void).cxx_destruct;
- (id)excludedProfiledSelectorNames;
- (_Bool)openedWithSearch;
- (long long)sentItemCount;
- (long long)drawerType;
- (void)updateMiniatureView;
- (void)_handlePanning:(id)arg1;
- (_Bool)gestureRecognizer:(id)arg1 shouldRecognizeSimultaneouslyWithGestureRecognizer:(id)arg2;
- (_Bool)gestureRecognizerShouldBegin:(id)arg1;
- (void)scrollViewDidEndDragging:(id)arg1 willDecelerate:(_Bool)arg2;
- (void)scrollViewDidScroll:(id)arg1;
- (void)scrollViewWillBeginDragging:(id)arg1;
- (id)collectionView:(id)arg1 viewForSupplementaryElementOfKind:(id)arg2 atIndexPath:(id)arg3;
- (id)collectionView:(id)arg1 cellForItemAtIndexPath:(id)arg2;
- (long long)collectionView:(id)arg1 numberOfItemsInSection:(long long)arg2;
- (long long)numberOfSectionsInCollectionView:(id)arg1;
- (void)collectionView:(id)arg1 didSelectItemAtIndexPath:(id)arg2;
- (_Bool)collectionView:(id)arg1 shouldSelectItemAtIndexPath:(id)arg2;
- (struct UIEdgeInsets)collectionView:(id)arg1 layout:(id)arg2 insetForSectionAtIndex:(long long)arg3;
- (struct CGSize)collectionView:(id)arg1 layout:(id)arg2 referenceSizeForHeaderInSection:(long long)arg3;
- (id)recipient;
- (void)searchResultDidChangeBecauseOfAutoCorrection;
- (void)setNotifySearchResults:(_Bool)arg1;
- (void)stickerPackagesDidChange;
- (void)_updateScrollBar;
- (void)_reloadStickers;
- (void)_makeActivityView;
- (void)_makeSectionView;
- (void)_makeScrollBar;
- (void)_makeStickerViews;
- (void)_updateCollectionViewAnimated:(_Bool)arg1 deltaContentOffset:(double)arg2;
- (void)setDrawerHeight:(double)arg1 resignWhenCollapsed:(_Bool)arg2 animated:(_Bool)arg3 deltaContentOffset:(double)arg4;
- (double)drawerHeight;
- (double)maximumDrawerHeight;
- (double)defaultDrawerHeight;
- (_Bool)shouldBeginDragging;
- (_Bool)readyForPanning;
- (_Bool)expandable;
- (void)resignFromActive;
- (id)drawerView;
- (void)accessoryPressed;
- (id)miniatureView;
- (void)dealloc;
- (id)initWithInputProvider:(id)arg1 sender:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

