//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "SCChatBrowseItemController.h"
#import "SCChatBrowseItemPlaybackTimeObserver.h"

@class NSArray, NSString, SCBaseChatMedia, SCStoriesTimer, UIView;

@interface SCChatBrowseStoryController : NSObject <SCChatBrowseItemPlaybackTimeObserver, SCChatBrowseItemController>
{
    NSArray *_mediaList;
    UIView *_accessoryView;
    UIView *_containerView;
    SCStoriesTimer *_storiesTimer;
    long long _currentIndex;
    NSArray *_storyEndTimes;
    id <SCChatBrowseItemPlayback><SCChatBrowseItemController> _currentItemController;
    id <SCChatBrowseItemPlayback><SCChatBrowseItemController> _nextItemController;
    id <SCBaseMediaFullScreenDelegate> _delegate;
    _Bool _allowsAutoadvance;
}

@property(readonly, nonatomic) UIView *containerView; // @synthesize containerView=_containerView;
@property(nonatomic) _Bool allowsAutoadvance; // @synthesize allowsAutoadvance=_allowsAutoadvance;
- (void).cxx_destruct;
- (void)stop;
- (void)resume;
- (void)startFromBeginning;
@property(readonly, nonatomic) NSArray *items;
@property(readonly, nonatomic) UIView *accessoryView;
- (id)contentView;
- (void)_initContentAndAccessoryView;
- (void)browseItemPlayback:(id)arg1 didProgressAtTime:(double)arg2 duration:(double)arg3;
- (void)_loadBatchOfMediasFromIndex:(long long)arg1;
- (void)_updateTimerWithCurrentItemTime:(double)arg1 itemTimeLeft:(double)arg2;
- (void)_initStoryEndTimes;
- (id)_itemControllerForIndex:(long long)arg1;
- (void)_resumeForCurrentItemController;
- (void)_startFromBeginningForCurrentItemController;
- (void)_prepareAndSetupNextForIndex:(long long)arg1;
- (void)_addCurrentItemViews;
- (void)_removeCurrentItemViews;
@property(readonly, nonatomic) SCBaseChatMedia *viewingMedia;
- (void)navigateAndResumeMedia:(id)arg1;
- (void)advance;
- (id)initWithMediaList:(id)arg1 delegate:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

