//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray, NSAttributedString, NSData, NSString, SCChat, SCChatInputController;

@protocol SCChatInputControllerDelegate <NSObject>
@property(retain, nonatomic) SCChat *chat;
- (void)resumeVideoChatAudioMaybeWithCompletion:(void (^)(void))arg1;
- (void)suspendVideoChatAudioWithCompletion:(void (^)(void))arg1;
- (void)enableTableViewInteractionAfterChatNotesRecording;
- (void)disableTableViewInteractionBeforeChatNotesRecording;
- (void)resizePreview:(_Bool)arg1 dueToTextInput:(_Bool)arg2 completion:(void (^)(void))arg3;
- (void)drawerInactive;
- (void)drawerActive;
- (_Bool)isAnimatingVideoChatFullscreen;
- (_Bool)receivingAudioOrVideo;
- (_Bool)sendingAudioOrVideo;
- (_Bool)isRemoteOrLocalPreviewFullscreen;
- (void)unpublishMedia:(unsigned long long)arg1 withCompletion:(void (^)(_Bool))arg2;
- (void)publishMedia:(unsigned long long)arg1 withCompletion:(void (^)(_Bool))arg2;
- (_Bool)isEligibleSenderReceiverPair;
- (void)chatInputController:(SCChatInputController *)arg1 didTapSendPaymentText:(NSAttributedString *)arg2 cashTagRanges:(NSArray *)arg3 amount:(unsigned long long)arg4;
- (void)chatInputController:(SCChatInputController *)arg1 didPasteGifData:(NSData *)arg2;
- (void)chatInputController:(SCChatInputController *)arg1 didTapSendText:(NSAttributedString *)arg2;
- (void)chatInputController:(SCChatInputController *)arg1 inputTextHeightDidChangeAnimated:(_Bool)arg2;
- (void)chatInputController:(SCChatInputController *)arg1 inputViewWillChangeAnimated:(_Bool)arg2;
- (void)chatInputControllerCashSendButtonPressed:(SCChatInputController *)arg1;
- (void)chatInputControllerTextDidChange:(SCChatInputController *)arg1;
- (NSString *)chatInputControllerRecipient:(SCChatInputController *)arg1;
@end

