//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@protocol SCChatBrowseItemPlaybackTimeObserver <NSObject>
- (void)browseItemPlayback:(id <SCChatBrowseItemPlayback>)arg1 didProgressAtTime:(double)arg2 duration:(double)arg3;
@end

