//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class EGODatabase, EGODatabaseStatement, NSArray, NSMutableDictionary, NSMutableSet, NSObject<OS_dispatch_queue>, NSString, SOJUStickerConfig;

@interface SCChatStickerSearch : NSObject
{
    NSObject<OS_dispatch_queue> *_dispatchQueue;
    EGODatabase *_database;
    EGODatabaseStatement *_stickerTagSearchByStringMatching;
    EGODatabaseStatement *_stickerSynonymSearchByStringMatching;
    SOJUStickerConfig *_stickerConfig;
    NSMutableSet *_publishedStickerPackIds;
    NSMutableDictionary *_stickerPriorities;
    NSString *_currentText;
    id <SCChatStickerSearchDelegate> _delegate;
    NSArray *_searchResults;
}

+ (id)localeURL;
+ (id)shared;
@property(readonly, copy, nonatomic) NSArray *searchResults; // @synthesize searchResults=_searchResults;
@property(nonatomic) __weak id <SCChatStickerSearchDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)_showSynoymTableContent;
- (void)_showTagTableContent;
- (void)addActivePackId:(id)arg1;
- (void)addSticker:(id)arg1 priority:(id)arg2;
- (id)_generateWordWithSynonym:(id)arg1;
- (id)_replaceSynonymsWithText:(id)arg1;
- (id)_mergeSearchResultsWithStickers:(id)arg1 emojis:(id)arg2;
- (id)_removeTrailingSpaces:(id)arg1;
- (_Bool)_textHasPunctuationsOnly:(id)arg1;
- (id)_processedTextWithText:(id)arg1;
- (void)searchStickersWithText:(id)arg1 searchSource:(long long)arg2;
- (void)_retryFetchingMetadataWithSearchPack:(id)arg1;
- (void)_updateDatabaseWithResponseDictionary:(id)arg1 newVersion:(int)arg2;
- (void)_fetchStickerSearchMetadataWithSearchPack:(id)arg1;
- (void)updateWithSearchPack:(id)arg1;
- (void)_storeStickerSearchPackVersion:(int)arg1;
- (int)_localStickerSearchPackVersion;
- (void)_insertSynonyms:(id)arg1 database:(id)arg2;
- (void)_insertTags:(id)arg1 database:(id)arg2;
- (void)_setupSearchStatementsForDatabase:(id)arg1;
- (void)_setupDatabase:(id)arg1;
- (void)_removeOldDatabasesExcludeVersion:(int)arg1;
- (id)_databaseForSearchPackVersion:(int)arg1;
- (void)updateWithStickerConfig:(id)arg1;
- (void)_initStickerConfig;
- (void)reset;
- (id)init;

@end

