//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSDictionary, SCDeepLinkURL, SOJUIdentityDeepLinkRequest, SOJUIdentityDeepLinkResponse;

@protocol SCDeepLinkProcessor <NSObject>
- (void)handleOpenURL:(SCDeepLinkURL *)arg1 additionalInfo:(NSDictionary *)arg2;
- (id)initWithNavigationDelegate:(id <NavigationDelegate>)arg1;

@optional
- (_Bool)processDeepLinkResponse:(SOJUIdentityDeepLinkResponse *)arg1;
- (SOJUIdentityDeepLinkRequest *)getDeepLinkRequest:(SCDeepLinkURL *)arg1;
@end

