//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SCDeepLinkManager.h"

@interface SCDeepLinkManager (API)
+ (void)verifyDeeplinkRequest:(id)arg1 deepLinkURL:(id)arg2 completion:(CDUnknownBlockType)arg3;
+ (void)matchDevice:(id)arg1 pingTimeInMillis:(long long)arg2 preInstall:(_Bool)arg3 userLogin:(_Bool)arg4 successBlock:(CDUnknownBlockType)arg5 failureBlock:(CDUnknownBlockType)arg6;
+ (void)resolveDeepLinkURL:(id)arg1 successBlock:(CDUnknownBlockType)arg2 failureBlock:(CDUnknownBlockType)arg3;
@end

