//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "SCDiscoverOperaPageProvider.h"

@class FBKVOController, NSMutableDictionary, NSString, SCDiscoverChannel, SCDiscoverEdition, SCDiscoverSubscriptionChecker, SCDiscoverUserProperties, SCOperaViewModel;

@interface SCDiscoverEditionOperaDataSource : NSObject <SCDiscoverOperaPageProvider>
{
    NSMutableDictionary *_dsnapIDToViewModelMap;
    NSMutableDictionary *_pageIdToOperaPageMap;
    FBKVOController *_kvoController;
    SCDiscoverUserProperties *_discoverUserProperties;
    SCDiscoverChannel *_channel;
    SCOperaViewModel *_editionEndViewModel;
    SCOperaViewModel *_subscriptionViewModel;
    SCDiscoverSubscriptionChecker *_subscriptionChecker;
    _Bool _shouldStartWithLongform;
    SCOperaViewModel *_rootViewModel;
    SCDiscoverEdition *_edition;
}

+ (void)addGestureToolTipsOverlayForViewModel:(id)arg1;
@property(retain, nonatomic) SCDiscoverEdition *edition; // @synthesize edition=_edition;
@property(retain, nonatomic) SCOperaViewModel *rootViewModel; // @synthesize rootViewModel=_rootViewModel;
- (void).cxx_destruct;
- (id)operaLongformPageWithDsnapId:(id)arg1;
- (id)operaPageWithPageId:(id)arg1;
- (void)_updateSubscriptionViewModel;
- (void)_chunkIsLoadingDidChange:(id)arg1 chunk:(id)arg2;
- (void)setDummyLoadingViewModelLoading;
- (void)setDummyLoadingViewModelRetriableError;
- (void)bindRootViewModelToViewModel:(id)arg1;
- (_Bool)_isRootChunk:(id)arg1 isFirstChunk:(_Bool)arg2;
- (void)updateWithCurrentEdition;
- (void)dealloc;
- (id)initWithEdition:(id)arg1 shouldStartWithLongform:(_Bool)arg2 discoverUserProperties:(id)arg3 channel:(id)arg4 kvoController:(id)arg5;
- (id)initWithEdition:(id)arg1 shouldStartWithLongform:(_Bool)arg2 discoverUserProperties:(id)arg3;
- (id)initWithChannel:(id)arg1 discoverUserProperties:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

