//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString, SCOperaPage;

@protocol SCDiscoverOperaPageProvider <NSObject>
- (SCOperaPage *)operaLongformPageWithDsnapId:(NSString *)arg1;
- (SCOperaPage *)operaPageWithPageId:(NSString *)arg1;
@end

