//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface SCDiscoverAPI : NSObject
{
}

+ (void)updateViewStateForEdition:(id)arg1 openDate:(id)arg2 parameters:(id)arg3;
+ (id)tweakEndpoint:(id)arg1;
+ (void)fetchEdition:(id)arg1 publisher:(id)arg2 endpoint:(id)arg3 successBlock:(CDUnknownBlockType)arg4 failureBlock:(CDUnknownBlockType)arg5;
+ (void)fetchDiscoverChannelsWithEndpoint:(id)arg1 forChannels:(id)arg2 successBlock:(CDUnknownBlockType)arg3 failureBlock:(CDUnknownBlockType)arg4;
+ (void)fetchCatalogForEditionId:(id)arg1 videoId:(id)arg2 videoCatalogEndpoint:(id)arg3 successBlock:(CDUnknownBlockType)arg4 failureBlock:(CDUnknownBlockType)arg5;
+ (void)sendDiscoverMediaWithParameters:(id)arg1 successBlock:(CDUnknownBlockType)arg2 failureBlock:(CDUnknownBlockType)arg3;
+ (void)validateLinkableForDsnapId:(id)arg1 endpoint:(id)arg2 successBlock:(CDUnknownBlockType)arg3 failureBlock:(CDUnknownBlockType)arg4;

@end

