//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "SCDiscoverChunkLoadingStrategy.h"

@class NSString;

@interface SCDiscoverNetworkAwareChunkLoadingStrategy : NSObject <SCDiscoverChunkLoadingStrategy>
{
}

+ (_Bool)setupDownloadRequestWithCurrentEdition:(id)arg1 currentChunkIndex:(long long)arg2 chunk:(id)arg3 chunkIndex:(long long)arg4 downloadRequest:(id)arg5 lastViewedDiscoverTime:(id)arg6;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

