//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSDate, SCDiscoverChunk, SCDiscoverEdition, SCRequest;

@protocol SCDiscoverChunkLoadingStrategy <NSObject>
+ (_Bool)setupDownloadRequestWithCurrentEdition:(SCDiscoverEdition *)arg1 currentChunkIndex:(long long)arg2 chunk:(SCDiscoverChunk *)arg3 chunkIndex:(long long)arg4 downloadRequest:(SCRequest *)arg5 lastViewedDiscoverTime:(NSDate *)arg6;
@end

