//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableDictionary, NSObject<OS_dispatch_queue>;

@interface SCDownloadableContentManager : NSObject
{
    NSMutableDictionary *_requestsCallbacks;
    NSObject<OS_dispatch_queue> *_queue;
}

+ (void)absoluteDataPathForUnzippedData:(id)arg1 directoryPath:(id)arg2 error:(id *)arg3;
+ (id)sharedInstance;
- (void).cxx_destruct;
- (void)requestResourceFromCDNWithContent:(id)arg1 success:(CDUnknownBlockType)arg2 failure:(CDUnknownBlockType)arg3;
- (void)requestLocalResourceWithContent:(id)arg1 success:(CDUnknownBlockType)arg2 failure:(CDUnknownBlockType)arg3;
- (void)runCallbacksForContent:(id)arg1 error:(id)arg2;
- (void)removeAllCallbacksForContent:(id)arg1;
- (unsigned long long)addCallback:(CDUnknownBlockType)arg1 forContent:(id)arg2;
- (void)requestContent:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (id)init;

@end

