//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface SCFeatureSettingsBuilder : NSObject
{
    _Bool _smartFiltersEnabled;
    _Bool _visualFiltersEnabled;
    _Bool _travelModeEnabled;
    _Bool _payToReplayEnabled;
    _Bool _barCodeScanEnabled;
    _Bool _qrCodeScanEnabled;
    _Bool _birthdayPartyEnabled;
    _Bool _pendingUpdateToServer;
    _Bool _permissionsEnabled;
    _Bool _galleryEnabled;
    _Bool _galleryInvited;
    _Bool _eSnapMedia;
}

+ (id)withFeatureSettings:(id)arg1;
- (id)setESnapMedia:(_Bool)arg1;
- (id)setGalleryInvited:(_Bool)arg1;
- (id)setGalleryEnabled:(_Bool)arg1;
- (id)setPermissionsEnabled:(_Bool)arg1;
- (id)setPendingUpdateToServer:(_Bool)arg1;
- (id)setBirthdayPartyEnabled:(_Bool)arg1;
- (id)setQrCodeScanEnabled:(_Bool)arg1;
- (id)setBarCodeScanEnabled:(_Bool)arg1;
- (id)setPayToReplayEnabled:(_Bool)arg1;
- (id)setTravelModeEnabled:(_Bool)arg1;
- (id)setVisualFiltersEnabled:(_Bool)arg1;
- (id)setSmartFiltersEnabled:(_Bool)arg1;
- (id)build;

@end

