//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@protocol SCFilterBase <NSObject>
@property(readonly, nonatomic) _Bool includeInitialValueInFiltering;
@property(readonly, nonatomic) double filterCoefficient;
@property(readonly, nonatomic) unsigned long long sampleCount;
@property(readonly, nonatomic) double filteredValue;
- (void)performFilteringWithNewSample:(double)arg1;
- (void)reset;
- (id)initWithFilterCoefficient:(double)arg1 initialValue:(double)arg2 includeInitialValueInFiltering:(_Bool)arg3;
@end

