//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UITableViewCell.h"

@class SCFriendProfileCellView, UIView;

@interface SCFriendProfileCell : UITableViewCell
{
    UIView *_bottomBorder;
    SCFriendProfileCellView *_cellView;
}

@property(retain, nonatomic) SCFriendProfileCellView *cellView; // @synthesize cellView=_cellView;
- (void).cxx_destruct;
- (void)setBottomBorderRightOffset:(double)arg1;
- (void)setBottomBorderHidden:(_Bool)arg1;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2;

@end

