//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "SCGeoFilterAppearanceSetting.h"

@class NSString, SCSponsoredSlug;

@interface SCGeoFilterAppearanceSetting : NSObject <SCGeoFilterAppearanceSetting>
{
    _Bool _isSponsored;
    _Bool _isUpdatable;
    _Bool _isBelowDrawingLayer;
    SCSponsoredSlug *_sponsoredSlug;
    NSString *_dynamicFilterRefreshHint;
    NSString *_dynamicFilterUpdatingMessage;
    struct CGPoint _updateLabelPosition;
}

@property(readonly, copy, nonatomic) NSString *dynamicFilterUpdatingMessage; // @synthesize dynamicFilterUpdatingMessage=_dynamicFilterUpdatingMessage;
@property(readonly, copy, nonatomic) NSString *dynamicFilterRefreshHint; // @synthesize dynamicFilterRefreshHint=_dynamicFilterRefreshHint;
@property(readonly, copy, nonatomic) SCSponsoredSlug *sponsoredSlug; // @synthesize sponsoredSlug=_sponsoredSlug;
@property(readonly, nonatomic) struct CGPoint updateLabelPosition; // @synthesize updateLabelPosition=_updateLabelPosition;
@property(readonly, nonatomic) _Bool isBelowDrawingLayer; // @synthesize isBelowDrawingLayer=_isBelowDrawingLayer;
@property(readonly, nonatomic) _Bool isUpdatable; // @synthesize isUpdatable=_isUpdatable;
@property(readonly, nonatomic) _Bool isSponsored; // @synthesize isSponsored=_isSponsored;
- (void).cxx_destruct;
@property(readonly, copy) NSString *description;
- (_Bool)isEqual:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)initWithIsSponsored:(_Bool)arg1 isUpdatable:(_Bool)arg2 isBelowDrawingLayer:(_Bool)arg3 updateLabelPosition:(struct CGPoint)arg4 sponsoredSlug:(id)arg5 dynamicFilterRefreshHint:(id)arg6 dynamicFilterUpdatingMessage:(id)arg7;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

