//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableDictionary, SCLocationServicesDataStore;

@interface SCGeoFilterLogger : NSObject
{
    _Bool _isCancelled;
    double _snapTakenTime;
    long long _numSwipes;
    NSMutableDictionary *_loadingMetaDataMap;
    SCLocationServicesDataStore *_locationServiceDataStore;
    long long _initialLocationDataState;
    long long _firstSwipeLocationDataState;
    long long _lastSwipeLocationDataState;
    double _initialLocationAccuracy;
    double _firstSwipeLocationAccuracy;
    double _lastSwipeLocationAccuracy;
    double _firstSwipeDelay;
    double _lastSwipeDelay;
}

+ (long long)numberFiltersMissed:(id)arg1;
+ (id)aggregateLoadingState:(id)arg1;
+ (id)loadingLogParameters:(id)arg1 withReferenceTime:(double)arg2;
+ (double)opportunityCaptured:(id)arg1 withLocationDataState:(long long)arg2;
@property(nonatomic) _Bool isCancelled; // @synthesize isCancelled=_isCancelled;
@property(nonatomic) double lastSwipeDelay; // @synthesize lastSwipeDelay=_lastSwipeDelay;
@property(nonatomic) double firstSwipeDelay; // @synthesize firstSwipeDelay=_firstSwipeDelay;
@property(nonatomic) double lastSwipeLocationAccuracy; // @synthesize lastSwipeLocationAccuracy=_lastSwipeLocationAccuracy;
@property(nonatomic) double firstSwipeLocationAccuracy; // @synthesize firstSwipeLocationAccuracy=_firstSwipeLocationAccuracy;
@property(nonatomic) double initialLocationAccuracy; // @synthesize initialLocationAccuracy=_initialLocationAccuracy;
@property(nonatomic) long long lastSwipeLocationDataState; // @synthesize lastSwipeLocationDataState=_lastSwipeLocationDataState;
@property(nonatomic) long long firstSwipeLocationDataState; // @synthesize firstSwipeLocationDataState=_firstSwipeLocationDataState;
@property(nonatomic) long long initialLocationDataState; // @synthesize initialLocationDataState=_initialLocationDataState;
@property(readonly, nonatomic) __weak SCLocationServicesDataStore *locationServiceDataStore; // @synthesize locationServiceDataStore=_locationServiceDataStore;
@property(readonly, copy, nonatomic) NSMutableDictionary *loadingMetaDataMap; // @synthesize loadingMetaDataMap=_loadingMetaDataMap;
@property(readonly, nonatomic) long long numSwipes; // @synthesize numSwipes=_numSwipes;
@property(readonly, nonatomic) double snapTakenTime; // @synthesize snapTakenTime=_snapTakenTime;
- (void).cxx_destruct;
- (void)logGeofilterLoadingEvent;
- (id)_upsertIfNecessary:(id)arg1 withNewStage:(id)arg2;
- (void)upsertIfNecessary:(id)arg1;
- (void)upsertIfNecessary:(id)arg1 withNewStage:(long long)arg2;
- (void)didSwipe;
- (void)setSnapIsCancelled:(_Bool)arg1;
- (void)swipeOverView:(id)arg1;
- (void)viewingStarted;
- (id)initWithLocationServicesDataStore:(id)arg1;

@end

