//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SCHereBaseCall.h"

@interface SCHereMissCall : SCHereBaseCall
{
    _Bool _shouldAnimate;
}

@property(nonatomic) _Bool shouldAnimate; // @synthesize shouldAnimate=_shouldAnimate;
- (_Bool)shouldAutoRetry;
- (id)initWithUsername:(id)arg1 dictionary:(id)arg2;
- (id)initWithSender:(id)arg1 recipient:(id)arg2;

@end

