//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class FBTweak;

@interface SCIdentityTweaks : NSObject
{
    FBTweak *_fakeEmojiCount;
    FBTweak *_fakeSuggestedFriendCount;
}

+ (id)getRegistrationPermissionsExperimentConfig;
+ (long long)getFilterOnboardingPromptExperimentId;
+ (long long)getRegisterDisplayNameExperimentId;
+ (long long)getQuickAddForSendToLimitExperiementalValue;
+ (long long)getQuickAddForStoriesLimitExperiementalValue;
+ (long long)getPhoneVerificationLatePromptExperimentId;
+ (long long)getLowerLimitFriendsAddedToHideInvites;
+ (long long)getLowerLimitSnapchattersFoundToHideInvites;
+ (id)shared;
- (void).cxx_destruct;
- (void)tweaks;
- (unsigned long long)getFakeSuggestedFriendCount;
- (unsigned long long)getFakeFriendmojiCount;
- (_Bool)isRegistrationFlowV2Enabled;
- (_Bool)shouldFakeBirthdayForUsername:(id)arg1;
- (_Bool)isPreLoginAppResetPasswordEnabled;
- (_Bool)isAddContactsFooterEnabled;
- (_Bool)shareUsernameOnProfileEnabled;
- (unsigned long long)safariCookieMatchSetting;
- (id)init;
- (long long)getNearbyPopTreatment;

@end

