//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UICollectionViewCell.h"

@class SCLoadingIndicatorView;

@interface SCLensesPhotoPickerLoadingCollectionViewCell : UICollectionViewCell
{
    SCLoadingIndicatorView *_loadingIndicatorView;
}

@property(retain, nonatomic) SCLoadingIndicatorView *loadingIndicatorView; // @synthesize loadingIndicatorView=_loadingIndicatorView;
- (void).cxx_destruct;
- (id)initWithFrame:(struct CGRect)arg1;

@end

