//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableDictionary, NSMutableSet, SCLens;

@interface SCLensesLogger : NSObject
{
    _Bool _allPhotosProcessed;
    double _startViewingTime;
    SCLens *_currentViewingLens;
    unsigned long long _overallLensesNumber;
    unsigned long long _currentLensIndex;
    double _startViewingTimeFacePhoto;
    unsigned long long _overallFacePhotosNumber;
    long long _currentFacePhotoIndex;
    NSMutableDictionary *_lensesSwipeLoggingInfo;
    NSMutableDictionary *_faceSwapSwipeLoggingInfo;
    NSMutableDictionary *_lensesDownloadLoggingInfo;
    NSMutableSet *_lensesBought;
}

+ (id)sharedInstance;
@property(retain, nonatomic) NSMutableSet *lensesBought; // @synthesize lensesBought=_lensesBought;
@property(retain, nonatomic) NSMutableDictionary *lensesDownloadLoggingInfo; // @synthesize lensesDownloadLoggingInfo=_lensesDownloadLoggingInfo;
@property(retain, nonatomic) NSMutableDictionary *faceSwapSwipeLoggingInfo; // @synthesize faceSwapSwipeLoggingInfo=_faceSwapSwipeLoggingInfo;
@property(retain, nonatomic) NSMutableDictionary *lensesSwipeLoggingInfo; // @synthesize lensesSwipeLoggingInfo=_lensesSwipeLoggingInfo;
@property(nonatomic) _Bool allPhotosProcessed; // @synthesize allPhotosProcessed=_allPhotosProcessed;
@property(nonatomic) long long currentFacePhotoIndex; // @synthesize currentFacePhotoIndex=_currentFacePhotoIndex;
@property(nonatomic) unsigned long long overallFacePhotosNumber; // @synthesize overallFacePhotosNumber=_overallFacePhotosNumber;
@property(nonatomic) double startViewingTimeFacePhoto; // @synthesize startViewingTimeFacePhoto=_startViewingTimeFacePhoto;
@property(nonatomic) unsigned long long currentLensIndex; // @synthesize currentLensIndex=_currentLensIndex;
@property(nonatomic) unsigned long long overallLensesNumber; // @synthesize overallLensesNumber=_overallLensesNumber;
@property(retain, nonatomic) SCLens *currentViewingLens; // @synthesize currentViewingLens=_currentViewingLens;
@property(nonatomic) double startViewingTime; // @synthesize startViewingTime=_startViewingTime;
- (void).cxx_destruct;
- (void)lensDownloadRemoveLogInfo:(id)arg1 operationId:(id)arg2;
- (void)lensDownloadFinished:(id)arg1 operationId:(id)arg2 downloadSize:(unsigned long long)arg3;
- (void)lensDownloadStarted:(id)arg1 operationId:(id)arg2;
- (void)lensesSessionStopped;
- (void)faceSwapSessionStopped;
- (void)fillSwipeEvent:(id)arg1 withLogObject:(id)arg2;
- (void)facePhotoPresentedAtIndex:(long long)arg1 overallNumber:(unsigned long long)arg2 allPhotosProcessed:(_Bool)arg3;
- (void)lensPresented:(id)arg1 atIndex:(unsigned long long)arg2 overallNumber:(unsigned long long)arg3;
- (id)init;

@end

