//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSDate, NSDictionary, NSString, SCGeofencedObject, SCSponsoredSlug;

@interface SCLensBuilder : NSObject
{
    NSString *_lensId;
    NSString *_code;
    NSString *_hintId;
    NSDictionary *_hintTranslations;
    _Bool _hasSound;
    NSString *_contentURL;
    NSString *_iconURL;
    NSString *_configPath;
    NSString *_signature;
    NSDate *_expirationDate;
    long long _type;
    long long _section;
    NSString *_purchaseId;
    _Bool _isFeatured;
    _Bool _isSponsored;
    unsigned long long _sponsoredSlugPosition;
    SCSponsoredSlug *_sponsoredSlug;
    SCGeofencedObject *_geoFenceData;
}

+ (id)withLens:(id)arg1;
- (void).cxx_destruct;
- (id)setGeoFenceData:(id)arg1;
- (id)setSponsoredSlug:(id)arg1;
- (id)setSponsoredSlugPosition:(unsigned long long)arg1;
- (id)setIsSponsored:(_Bool)arg1;
- (id)setIsFeatured:(_Bool)arg1;
- (id)setPurchaseId:(id)arg1;
- (id)setSection:(long long)arg1;
- (id)setType:(long long)arg1;
- (id)setExpirationDate:(id)arg1;
- (id)setSignature:(id)arg1;
- (id)setConfigPath:(id)arg1;
- (id)setIconURL:(id)arg1;
- (id)setContentURL:(id)arg1;
- (id)setHasSound:(_Bool)arg1;
- (id)setHintTranslations:(id)arg1;
- (id)setHintId:(id)arg1;
- (id)setCode:(id)arg1;
- (id)setLensId:(id)arg1;
- (id)build;

@end

