//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "SCLens.h"

@class NSDate, NSDictionary, NSString, SCGeofencedObject, SCSponsoredSlug;

@interface SCLens : NSObject <SCLens>
{
    _Bool _hasSound;
    _Bool _isFeatured;
    _Bool _isSponsored;
    NSString *_lensId;
    NSString *_code;
    NSString *_hintId;
    NSDictionary *_hintTranslations;
    NSString *_contentURL;
    NSString *_iconURL;
    NSString *_configPath;
    NSString *_signature;
    NSDate *_expirationDate;
    long long _type;
    long long _section;
    NSString *_purchaseId;
    unsigned long long _sponsoredSlugPosition;
    SCSponsoredSlug *_sponsoredSlug;
    SCGeofencedObject *_geoFenceData;
}

@property(readonly, copy, nonatomic) SCGeofencedObject *geoFenceData; // @synthesize geoFenceData=_geoFenceData;
@property(readonly, copy, nonatomic) SCSponsoredSlug *sponsoredSlug; // @synthesize sponsoredSlug=_sponsoredSlug;
@property(readonly, nonatomic) unsigned long long sponsoredSlugPosition; // @synthesize sponsoredSlugPosition=_sponsoredSlugPosition;
@property(readonly, nonatomic) _Bool isSponsored; // @synthesize isSponsored=_isSponsored;
@property(readonly, nonatomic) _Bool isFeatured; // @synthesize isFeatured=_isFeatured;
@property(readonly, copy, nonatomic) NSString *purchaseId; // @synthesize purchaseId=_purchaseId;
@property(readonly, nonatomic) long long section; // @synthesize section=_section;
@property(readonly, nonatomic) long long type; // @synthesize type=_type;
@property(readonly, copy, nonatomic) NSDate *expirationDate; // @synthesize expirationDate=_expirationDate;
@property(readonly, copy, nonatomic) NSString *signature; // @synthesize signature=_signature;
@property(readonly, copy, nonatomic) NSString *configPath; // @synthesize configPath=_configPath;
@property(readonly, copy, nonatomic) NSString *iconURL; // @synthesize iconURL=_iconURL;
@property(readonly, copy, nonatomic) NSString *contentURL; // @synthesize contentURL=_contentURL;
@property(readonly, nonatomic) _Bool hasSound; // @synthesize hasSound=_hasSound;
@property(readonly, copy, nonatomic) NSDictionary *hintTranslations; // @synthesize hintTranslations=_hintTranslations;
@property(readonly, copy, nonatomic) NSString *hintId; // @synthesize hintId=_hintId;
@property(readonly, copy, nonatomic) NSString *code; // @synthesize code=_code;
@property(readonly, copy, nonatomic) NSString *lensId; // @synthesize lensId=_lensId;
- (void).cxx_destruct;
@property(readonly, copy) NSString *description;
- (_Bool)isEqual:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)initWithLensId:(id)arg1 code:(id)arg2 hintId:(id)arg3 hintTranslations:(id)arg4 hasSound:(_Bool)arg5 contentURL:(id)arg6 iconURL:(id)arg7 configPath:(id)arg8 signature:(id)arg9 expirationDate:(id)arg10 type:(long long)arg11 section:(long long)arg12 purchaseId:(id)arg13 isFeatured:(_Bool)arg14 isSponsored:(_Bool)arg15 sponsoredSlugPosition:(unsigned long long)arg16 sponsoredSlug:(id)arg17 geoFenceData:(id)arg18;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

