//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "SCLensesInputImagesProviderProtocol.h"

@class CIDetector, NSArray, NSMutableArray, NSString, SCQueuePerformer, SCSentinel;

@interface SCLensesCameraRollInputFaceImagesProvider : NSObject <SCLensesInputImagesProviderProtocol>
{
    id <SCLensesInputImagesProviderDelegate> _delegate;
    id <SCCameraRollWrapperProtocol> _cameraRollLibrary;
    CIDetector *_faceDetector;
    SCQueuePerformer *_performer;
    long long _processedImagesCount;
    long long _requestedImagesCount;
    NSArray *_croppedFaceImageIds;
    NSMutableArray *_groupedCroppedFaceImageIds;
    SCSentinel *_sentinel;
}

+ (id)imageCache;
@property(retain, nonatomic) SCSentinel *sentinel; // @synthesize sentinel=_sentinel;
@property(retain, nonatomic) NSMutableArray *groupedCroppedFaceImageIds; // @synthesize groupedCroppedFaceImageIds=_groupedCroppedFaceImageIds;
@property(retain, nonatomic) NSArray *croppedFaceImageIds; // @synthesize croppedFaceImageIds=_croppedFaceImageIds;
@property(nonatomic) long long requestedImagesCount; // @synthesize requestedImagesCount=_requestedImagesCount;
@property(nonatomic) long long processedImagesCount; // @synthesize processedImagesCount=_processedImagesCount;
@property(retain, nonatomic) SCQueuePerformer *performer; // @synthesize performer=_performer;
@property(retain, nonatomic) CIDetector *faceDetector; // @synthesize faceDetector=_faceDetector;
@property(retain, nonatomic) id <SCCameraRollWrapperProtocol> cameraRollLibrary; // @synthesize cameraRollLibrary=_cameraRollLibrary;
@property(nonatomic) __weak id <SCLensesInputImagesProviderDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)_processFaceDetectionAndCacheImage:(id)arg1 imageId:(id)arg2 imageIndex:(unsigned long long)arg3 completion:(CDUnknownBlockType)arg4;
- (void)getCroppedThumbnailsFromCameraRollAndCache:(unsigned long long)arg1 size:(struct CGSize)arg2 completion:(CDUnknownBlockType)arg3;
- (void)processImagesRemovingAtIndexes:(id)arg1;
- (void)processImagesInsertingAtIndexes:(id)arg1 size:(struct CGSize)arg2;
- (struct CGRect)normalizedRectFromCroppedImageId:(id)arg1;
- (id)imageIdFromCroppedImageId:(id)arg1;
- (void)getThumbnailImageFromCacheWithCroppedImageId:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)getThumbnailImageFromCameraWithCroppedImageId:(id)arg1 targetSize:(struct CGSize)arg2 completion:(CDUnknownBlockType)arg3;
- (id)getCroppedImagesIdsFromgroupedImagesRepresentation:(id)arg1;
- (void)cancelImageLoadingWithId:(id)arg1;
- (id)getOriginalImageAtIndex:(unsigned long long)arg1 completion:(CDUnknownBlockType)arg2;
- (id)getThumbnailImageAtIndex:(unsigned long long)arg1 targetSize:(struct CGSize)arg2 completion:(CDUnknownBlockType)arg3;
- (unsigned long long)indexOfImageWithIdentifier:(id)arg1;
- (id)imageIdentifierAtIndex:(unsigned long long)arg1;
- (unsigned long long)rawImagesCount;
- (unsigned long long)imagesCount;
- (_Bool)canProcessMoreImages;
- (void)processMoreImagesIfPossibleWithSize:(struct CGSize)arg1 count:(unsigned long long)arg2;
- (void)cooldown;
- (void)warmupWithCompletion:(CDUnknownBlockType)arg1;
- (void)reloadAssetsWithCompletion:(CDUnknownBlockType)arg1;
- (void)reloadAssetsIfNeeded;
- (void)handleCameraRollWrapperDidUpdateNotification:(id)arg1;
- (void)clearCache;
- (void)dealloc;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

