//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface SCLowPowerModeTracker : NSObject
{
    _Bool _lowPowerModeEnabled;
}

+ (id)sharedTracker;
+ (_Bool)isOSInLowPowerMode;
@property(readonly, nonatomic) _Bool lowPowerModeEnabled; // @synthesize lowPowerModeEnabled=_lowPowerModeEnabled;
- (void)lowPowerModeChanged;
- (void)dealloc;
- (id)init;

@end

