//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "SCAppNotificationProviderDelegate.h"

@class NSString;

@interface SCLocalNotificationsController : NSObject <SCAppNotificationProviderDelegate>
{
    NSString *_sourceOfVibration;
}

- (void).cxx_destruct;
- (void)displayNotification:(id)arg1;
- (_Bool)willDisplayNotification:(id)arg1;
- (void)hideNotification:(id)arg1;
- (void)didApplicationStateChange:(_Bool)arg1 withCurrentNotifications:(id)arg2;

@end

