//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSCoding.h"
#import "SCLocationControllerDelegate.h"
#import "SCLocationDataControllerDelegate.h"
#import "SCLocationDataFetcherDelegate.h"
#import "SCTimeProfilable.h"

@class CLLocation, NSDate, NSMutableDictionary, NSString, SCLocationController, SCLocationDataFetcher, SCLocationGeoFilterController, SCLocationGeoLensController, SCLocationSharedStoriesController, SCLocationWeatherController;

@interface SCLocationServicesDataStore : NSObject <NSCoding, SCLocationDataFetcherDelegate, SCLocationControllerDelegate, SCLocationDataControllerDelegate, SCTimeProfilable>
{
    _Bool _fetchingLocationData;
    CLLocation *_location;
    long long _state;
    SCLocationController *_locationController;
    SCLocationDataFetcher *_locationDataFetcher;
    SCLocationGeoFilterController *_geoFilterController;
    SCLocationGeoLensController *_geoLensController;
    SCLocationSharedStoriesController *_sharedStoriesController;
    SCLocationWeatherController *_weatherController;
    NSMutableDictionary *_datastore;
    CLLocation *_dataLocation;
    NSDate *_lastIpRequestTime;
    NSDate *_updateUntil;
}

+ (long long)context;
+ (id)profiledSelectorNames;
+ (id)stringWithLocationDataState:(long long)arg1;
+ (void)removeSavedState;
+ (id)path;
+ (id)sharedInstance;
@property(retain, nonatomic) NSDate *updateUntil; // @synthesize updateUntil=_updateUntil;
@property(retain, nonatomic) NSDate *lastIpRequestTime; // @synthesize lastIpRequestTime=_lastIpRequestTime;
@property(retain, nonatomic) CLLocation *dataLocation; // @synthesize dataLocation=_dataLocation;
@property(nonatomic) _Bool fetchingLocationData; // @synthesize fetchingLocationData=_fetchingLocationData;
@property(retain, nonatomic) NSMutableDictionary *datastore; // @synthesize datastore=_datastore;
@property(retain, nonatomic) SCLocationWeatherController *weatherController; // @synthesize weatherController=_weatherController;
@property(retain, nonatomic) SCLocationSharedStoriesController *sharedStoriesController; // @synthesize sharedStoriesController=_sharedStoriesController;
@property(retain, nonatomic) SCLocationGeoLensController *geoLensController; // @synthesize geoLensController=_geoLensController;
@property(retain, nonatomic) SCLocationGeoFilterController *geoFilterController; // @synthesize geoFilterController=_geoFilterController;
@property(retain, nonatomic) SCLocationDataFetcher *locationDataFetcher; // @synthesize locationDataFetcher=_locationDataFetcher;
@property(retain, nonatomic) SCLocationController *locationController; // @synthesize locationController=_locationController;
@property(readonly, nonatomic) long long state; // @synthesize state=_state;
@property(retain, nonatomic) CLLocation *location; // @synthesize location=_location;
- (void).cxx_destruct;
- (id)excludedProfiledSelectorNames;
- (id)preferredProfiledSelectorNames;
- (void)_logGeolocationLocationDataReadyEvent:(id)arg1;
- (void)locationController:(id)arg1 didUpdateSpeed:(id)arg2;
- (void)locationController:(id)arg1 didFailWithError:(id)arg2;
- (void)locationController:(id)arg1 didUpdateLocation:(id)arg2;
- (void)locationDataController:(id)arg1 didUpdateData:(id)arg2;
- (void)locationDataFetcherFailedToFetchLocationDataWithError:(id)arg1;
- (_Bool)shouldProcessResponseWithNewLocation:(id)arg1 oldLocation:(id)arg2;
- (void)locationDataFetcherFetchedLocationData:(id)arg1 forLocation:(id)arg2;
- (void)_setObject:(id)arg1 forKey:(id)arg2;
- (void)_setState:(long long)arg1;
- (void)processWhiteListedSharedStoryResponse:(id)arg1;
- (id)objectForKey:(id)arg1;
- (void)_fetchIpBasedLocationData;
- (void)_prepareLocationDataUpdate;
- (void)_startUpdatingLocationDataWithLocationServices:(_Bool)arg1;
- (double)currentLocationDataAccuracy;
- (void)stopUpdatingLocationData;
- (void)startUpdatingLocationData;
- (void)stopLocationUpdateIfNecessary;
- (void)startUpdatingLocationServicesIfNecessary;
- (void)updateLocationDataOnceWithLocationServices:(_Bool)arg1;
- (void)updateLocationDataOnce;
- (void)_ensureNonNilObjects;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)init;
- (void)clear;
- (void)saveState;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

