//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "SCManagedVideoCapturerOutputSettings.h"

@class NSString;

@interface SCManagedVideoCapturerOutputSettings : NSObject <SCManagedVideoCapturerOutputSettings>
{
    double _width;
    double _height;
    double _aspectRatio;
    double _videoBitRate;
    double _audioBitRate;
    unsigned long long _keyFrameInterval;
}

@property(readonly, nonatomic) unsigned long long keyFrameInterval; // @synthesize keyFrameInterval=_keyFrameInterval;
@property(readonly, nonatomic) double audioBitRate; // @synthesize audioBitRate=_audioBitRate;
@property(readonly, nonatomic) double videoBitRate; // @synthesize videoBitRate=_videoBitRate;
@property(readonly, nonatomic) double aspectRatio; // @synthesize aspectRatio=_aspectRatio;
@property(readonly, nonatomic) double height; // @synthesize height=_height;
@property(readonly, nonatomic) double width; // @synthesize width=_width;
@property(readonly, copy) NSString *description;
- (_Bool)isEqual:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)initWithWidth:(double)arg1 height:(double)arg2 aspectRatio:(double)arg3 videoBitRate:(double)arg4 audioBitRate:(double)arg5 keyFrameInterval:(unsigned long long)arg6;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

