//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "SCManagedDeviceCapacityAnalyzerListener.h"
#import "SCStillImageCaptureMethodDelegate.h"

@class AVCaptureSession, AVCaptureStillImageOutput, NSString, SCManagedCapturerState, SCStillImageCaptureAutomaticMethod;

@interface SCManagedStillImageCapturer : NSObject <SCStillImageCaptureMethodDelegate, SCManagedDeviceCapacityAnalyzerListener>
{
    AVCaptureStillImageOutput *_stillImageOutput;
    SCManagedCapturerState *_state;
    _Bool _adjustingExposure;
    _Bool _shouldCapture;
    unsigned long long _retries;
    double _aspectRatio;
    float _zoomFactor;
    CDUnknownBlockType _completionHandler;
    id <SCPerforming> _performer;
    AVCaptureSession *_session;
    SCStillImageCaptureAutomaticMethod *_capturer;
}

- (void).cxx_destruct;
- (id)_resizeImageFromData:(id)arg1;
- (id)imageWithAppliedLensesFromImage:(id)arg1 devicePosition:(unsigned long long)arg2;
- (id)_stillImageConnectionFromOutput:(id)arg1;
- (void)_captureStillImage;
- (void)_deadlineCaptureStillImage;
- (void)stillImageCaptureMethod:(id)arg1 didFailWithError:(id)arg2;
- (void)stillImageCaptureMethod:(id)arg1 requestsRetryWithError:(id)arg2;
- (void)stillImageCaptureMethod:(id)arg1 didCaptureStillImage:(id)arg2 cameraInfo:(id)arg3 error:(id)arg4;
- (void)managedDeviceCapacityAnalyzer:(id)arg1 didChangeAdjustingExposure:(_Bool)arg2;
- (void)captureStillImageWithAspectRatio:(double)arg1 atZoomFactor:(float)arg2 state:(id)arg3 completionHandler:(CDUnknownBlockType)arg4;
- (void)removeAsOutput:(id)arg1;
- (void)setHighResolutionStillImageOutputEnabled:(_Bool)arg1;
- (void)setAsOutput:(id)arg1;
- (id)initWithSession:(id)arg1 performer:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

