//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "SCManagedVideoDataSourceListener.h"

@class NSString;

@interface SCManagedVideoStreamReporter : NSObject <SCManagedVideoDataSourceListener>
{
    unsigned long long _droppedSampleBuffers;
    unsigned long long _outputSampleBuffers;
    double _lastReportTime;
}

- (void)managedVideoDataSource:(id)arg1 didDropSampleBuffer:(struct opaqueCMSampleBuffer *)arg2 devicePosition:(unsigned long long)arg3;
- (void)managedVideoDataSource:(id)arg1 didOutputSampleBuffer:(struct opaqueCMSampleBuffer *)arg2 devicePosition:(unsigned long long)arg3;
- (void)_reportIfNeeded;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

