//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface SCMethodLatencyEntry : NSObject
{
    unsigned long long _frequency;
    unsigned long long _maxLatency;
    unsigned long long _totalLatency;
    _Bool _fastMethod;
}

- (_Bool)checkFastMethodWithCurrentLatency:(unsigned long long)arg1;
- (id)initWithFirstLatency:(unsigned long long)arg1 forMethod:(id)arg2;

@end

