//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class SCUserSession;

@interface SCMessageViewModelFactory : NSObject
{
    SCUserSession *_userSession;
}

+ (Class)getViewModelClassForMessage:(id)arg1;
+ (_Bool)isStatusMessage:(id)arg1;
- (void).cxx_destruct;
- (_Bool)isSaved:(id)arg1;
- (_Bool)showsTimestampForMessage:(id)arg1 withPreviousViewModel:(id)arg2;
- (_Bool)showsSenderHeaderForMessage:(id)arg1 withPreviousViewModel:(id)arg2;
- (_Bool)showsDateHeaderForMessage:(id)arg1 withPreviousViewModel:(id)arg2;
- (id)viewModelForMessage:(id)arg1 previousViewModel:(id)arg2 withChatSnapshot:(id)arg3 displayInBubbleChat:(_Bool)arg4;
- (id)initWithUserSession:(id)arg1;

@end

