//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SCSavableItemChatViewModel.h"

#import "SCMediaChatCellViewConfig.h"

@interface SCMediaChatViewModel : SCSavableItemChatViewModel <SCMediaChatCellViewConfig>
{
}

- (struct CGSize)thumbnailSize;
- (double)thumbnailWidth;
- (double)bodyContentWidth;
- (double)payloadVerticalMargin;
- (double)payloadHeight;
- (id)mediaMessage;
- (id)createChatCellWithParentVC:(id)arg1 delegate:(id)arg2;
- (id)reusableCellIdentifier;

@end

