//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray, NSString, SCSummaries;

@protocol SCMessageText <NSObject>
- (void)markAsDisplayed;
- (_Bool)isDisplayed;
- (SCSummaries *)summaries;
- (NSArray *)mediaCardAttributes;
- (NSArray *)attributes;
- (NSString *)text;
@end

