//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

@class NSString, UIColor, UIFont;

@protocol SCMessageChatCellViewConfig
- (_Bool)bottomRightCornerIsRounded;
- (_Bool)topRightCornerIsRounded;
- (_Bool)bottomLeftCornerIsRounded;
- (NSString *)textForTimeLabel;
- (NSString *)textForSenderHeaderLabel;
- (NSString *)textForDateHeaderLabel;
- (unsigned long long)textCheckingTypes;
- (_Bool)shouldShowRetryStatusView;
- (_Bool)shouldShowRetryIcon;
- (_Bool)shouldDisplayInBubbleChat;
- (_Bool)shouldShowURLMediaCards;
- (_Bool)shouldShowTimestamp;
- (_Bool)shouldShowSenderHeader;
- (_Bool)shouldShowDateHeader;
- (double)verticalOffsetForBodyView;
- (double)verticalOffsetForSenderHeaderLabel;
- (double)payloadHeight;
- (double)payloadVerticalMargin;
- (double)bodyContentWidth;
- (double)bubbleCellWidth;
- (double)payloadContentWidth;
- (double)payloadWidth;
- (double)bodyWidth;
- (_Bool)isGrayScaleMediaCard;
- (UIColor *)colorForActionText;
- (UIColor *)colorForSenderLine;
- (UIColor *)textColorForHeaderLabel;
- (UIFont *)fontForActionText;
@end

