//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SCSavableItemChatTableViewCell.h"

#import "SCExpandableMediaChatTableCell.h"

@class NSString, SCBaseMediaThumbnailView, UIViewController<SCChatCellBaseGestureDelegate><SCChatCellMessageStateUpdateDelegate>;

@interface SCMediaChatTableViewCell : SCSavableItemChatTableViewCell <SCExpandableMediaChatTableCell>
{
    UIViewController<SCChatCellBaseGestureDelegate><SCChatCellMessageStateUpdateDelegate> *_parentVC;
    id <SCChatExpandableMediaChatTableCellDelegate> _delegate;
    SCBaseMediaThumbnailView *_mediaThumbnailView;
}

@property(retain, nonatomic) SCBaseMediaThumbnailView *mediaThumbnailView; // @synthesize mediaThumbnailView=_mediaThumbnailView;
- (void).cxx_destruct;
- (_Bool)fullScreenIsShown;
- (void)dismissFullScreenView;
- (void)loadVideoIfNecessary;
- (void)renderMetadata;
- (void)renderPayload;
- (void)initMediaViewWithParentVC:(id)arg1 delegate:(id)arg2;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2 parentVC:(id)arg3 delegate:(id)arg4;
- (id)mediaViewModel;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

