//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SCBaseChatCellViewModel.h"

#import "SCMessageChatCellViewConfig.h"

@class NSString, SCUserSession;

@interface SCMessageChatViewModel : SCBaseChatCellViewModel <SCMessageChatCellViewConfig>
{
    double _intervalFromPrevious;
    _Bool _isFailed;
    _Bool _isSending;
    _Bool _topRightCornerIsRounded;
    _Bool _bottomRightCornerIsRounded;
    _Bool _bottomLeftCornerIsRounded;
    _Bool _hasDateHeader;
    _Bool _hasSenderHeader;
    _Bool _hasTimestamp;
    _Bool _hasURLMediaCards;
    _Bool _displayInBubbleChat;
    id <SCMessage> _message;
    NSString *_sender;
    SCUserSession *_userSession;
    unsigned long long _textCheckingTypes;
}

+ (double)lastCellExtraBottomMargin;
+ (double)bottomMargin;
+ (id)timeLabelColor;
+ (id)blackActionColor;
+ (id)grayActionColor;
+ (id)grayChatColor;
+ (id)sendingTextColor;
+ (id)blueTextColor;
+ (id)redTextColor;
+ (id)textLabelColor;
+ (id)headerLabelFont;
+ (id)dateHeaderLabelFont;
+ (id)actionTextFont;
+ (id)emojiOnlyLabelFont;
+ (id)textLabelFont;
+ (_Bool)textHasOnlyEmoji:(id)arg1;
@property(nonatomic) _Bool displayInBubbleChat; // @synthesize displayInBubbleChat=_displayInBubbleChat;
@property(nonatomic) _Bool hasURLMediaCards; // @synthesize hasURLMediaCards=_hasURLMediaCards;
@property(nonatomic) _Bool hasTimestamp; // @synthesize hasTimestamp=_hasTimestamp;
@property(nonatomic) _Bool hasSenderHeader; // @synthesize hasSenderHeader=_hasSenderHeader;
@property(nonatomic) _Bool hasDateHeader; // @synthesize hasDateHeader=_hasDateHeader;
@property(nonatomic) unsigned long long textCheckingTypes; // @synthesize textCheckingTypes=_textCheckingTypes;
@property(nonatomic) _Bool bottomLeftCornerIsRounded; // @synthesize bottomLeftCornerIsRounded=_bottomLeftCornerIsRounded;
@property(nonatomic) _Bool bottomRightCornerIsRounded; // @synthesize bottomRightCornerIsRounded=_bottomRightCornerIsRounded;
@property(nonatomic) _Bool topRightCornerIsRounded; // @synthesize topRightCornerIsRounded=_topRightCornerIsRounded;
@property(readonly, nonatomic) SCUserSession *userSession; // @synthesize userSession=_userSession;
@property(readonly, nonatomic) _Bool isSending; // @synthesize isSending=_isSending;
@property(readonly, nonatomic) _Bool isFailed; // @synthesize isFailed=_isFailed;
@property(copy, nonatomic) NSString *sender; // @synthesize sender=_sender;
@property(retain, nonatomic) id <SCMessage> message; // @synthesize message=_message;
- (void).cxx_destruct;
- (long long)getSendState;
- (double)heightWithBottomPadding:(_Bool)arg1 isLastMessage:(_Bool)arg2;
- (_Bool)shouldShowRetryStatusView;
- (_Bool)shouldShowRetryIcon;
- (id)textForDateHeaderLabel;
- (id)textForTimeLabel;
- (id)textForSenderHeaderLabel;
- (void)setShouldDisplayURL:(_Bool)arg1;
- (double)verticalOffsetForBodyView;
- (double)verticalOffsetForSenderHeaderLabel;
- (_Bool)isGrayScaleMediaCard;
- (id)colorForActionText;
- (id)colorForSenderLine;
- (id)textColorForHeaderLabel;
- (id)fontForActionText;
- (_Bool)isEqual:(id)arg1;
- (double)bubbleChatLifespan;
- (double)intervalFromPrevious;
- (_Bool)wasSentToday;
- (_Bool)shouldDisplayBelowFoldInChat;
- (_Bool)shouldDisplayInBubbleChat;
- (_Bool)shouldShowURLMediaCards;
- (_Bool)shouldShowTimestamp;
- (_Bool)shouldShowSenderHeader;
- (_Bool)shouldShowDateHeader;
- (id)initWithMessage:(id)arg1 forSender:(id)arg2 withDateHeader:(_Bool)arg3 withSenderHeader:(_Bool)arg4 withTimestamp:(_Bool)arg5 withIntervalFromPrevious:(double)arg6 withURLMediaCards:(_Bool)arg7 displayInBubbleChat:(_Bool)arg8 userSession:(id)arg9;
- (double)bodyHeightForWidth:(double)arg1;
- (double)bodyContentWidth;
- (double)bubbleCellWidth;
- (double)payloadContentWidth;
- (double)payloadWidth;
- (double)bodyWidth;
- (double)payloadHeight;
- (double)payloadVerticalMargin;

@end

