//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SCMiniProfileBaseViewDelegate.h"
#import "SCMiniProfileButtonViewDelegate.h"
#import "SCMiniProfileTextViewDelegate.h"

@class Friend, UIButton;

@protocol SCMiniProfileViewDelegate <SCMiniProfileButtonViewDelegate, SCMiniProfileBaseViewDelegate, SCMiniProfileTextViewDelegate>
- (void)didPressAddFriendButton:(UIButton *)arg1 friend:(Friend *)arg2 onProgress:(void (^)(void))arg3 onSuccess:(void (^)(Friend *))arg4 onFailure:(void (^)(Friend *))arg5;
@end

