//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SCMiniProfileBaseView.h"

@class Friend, NSAttributedString, NSString, SCMiniProfileButtonView, SCMiniProfileTextView, SCSnapcodeView, UIButton, UIPanGestureRecognizer, UITapGestureRecognizer, UIViewController;

@interface SCMiniProfileView : SCMiniProfileBaseView
{
    SCSnapcodeView *_snapcodeView;
    SCMiniProfileTextView *_textView;
    SCMiniProfileButtonView *_buttonView;
    UIButton *_settingsGearButton;
    UIButton *_addFriendButton;
    NSString *_addFriendText;
    NSString *_addingText;
    NSString *_addedText;
    NSAttributedString *_doneString;
    _Bool _addFriendInProgress;
    UITapGestureRecognizer *_tapGestureRecognizer;
    UIPanGestureRecognizer *_panGestureRecognizer;
    struct CGRect _startPanGestureFrame;
    Friend *_friend;
    UIViewController *_parentViewController;
    id <SCMiniProfileViewDelegate> _delegate;
}

+ (id)miniProfileViewWithFriend:(id)arg1 parentViewController:(id)arg2 contexts:(id)arg3 delegate:(id)arg4;
- (void).cxx_destruct;
- (id)friendPictureStatus;
- (void)_resetMiniProfileView;
- (void)_onAddFriendFailure:(id)arg1 friend:(id)arg2;
- (void)_onAddFriendSuccess:(id)arg1 friend:(id)arg2;
- (void)_onAddFriendProgress:(id)arg1;
- (void)didPressSettingsGearButton;
- (void)_didTapActionButton:(id)arg1;
- (void)_initSettingsGearButtonIfNecessary;
- (void)_initAddFriendButtonIfNecessary;
- (_Bool)_shouldHideButtonsForFriendFromParent:(id)arg1;
- (void)_updateButtons;
- (void)updateWithFriend:(id)arg1 contexts:(id)arg2;
- (void)_setCardSize:(id)arg1;
- (double)_cardHeight:(id)arg1;
- (void)_updateMiniProfileAfterPresentingAnimation;
- (void)_moveMiniProfileBelowBottom;
- (void)_miniProfileDismissAnimationDidFinish;
- (void)_updateCardConstraint;
- (id)initWithFrame:(struct CGRect)arg1 friend:(id)arg2 parentViewController:(id)arg3 delegate:(id)arg4;

@end

