//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

#import "SCAddFriendButtonV2Delegate.h"

@class AddedFriend, Friend, NSString, SCAddFriendButtonV2, SCProfilePictureThumbnail, UILabel;

@interface SCMyFriendCellView : UIView <SCAddFriendButtonV2Delegate>
{
    _Bool _alreadyAdded;
    _Bool _selected;
    _Bool _animating;
    id <SCMyFriendCellViewDelegate> _delegate;
    long long _myFriendCellType;
    Friend *_friend;
    AddedFriend *_addedFriend;
    long long _sectionType;
    unsigned long long _numberOfTaps;
    UIView *_profileImagesContainer;
    SCProfilePictureThumbnail *_profilePictureView;
    UILabel *_nameLabel;
    UILabel *_subLabel;
    SCAddFriendButtonV2 *_addFriendButton;
}

@property(retain, nonatomic) SCAddFriendButtonV2 *addFriendButton; // @synthesize addFriendButton=_addFriendButton;
@property(retain, nonatomic) UILabel *subLabel; // @synthesize subLabel=_subLabel;
@property(retain, nonatomic) UILabel *nameLabel; // @synthesize nameLabel=_nameLabel;
@property(retain, nonatomic) SCProfilePictureThumbnail *profilePictureView; // @synthesize profilePictureView=_profilePictureView;
@property(retain, nonatomic) UIView *profileImagesContainer; // @synthesize profileImagesContainer=_profileImagesContainer;
@property(nonatomic) unsigned long long numberOfTaps; // @synthesize numberOfTaps=_numberOfTaps;
@property _Bool animating; // @synthesize animating=_animating;
@property(nonatomic) _Bool selected; // @synthesize selected=_selected;
@property(nonatomic) _Bool alreadyAdded; // @synthesize alreadyAdded=_alreadyAdded;
@property(nonatomic) long long sectionType; // @synthesize sectionType=_sectionType;
@property(retain, nonatomic) AddedFriend *addedFriend; // @synthesize addedFriend=_addedFriend;
@property(retain, nonatomic) Friend *friend; // @synthesize friend=_friend;
@property(nonatomic) long long myFriendCellType; // @synthesize myFriendCellType=_myFriendCellType;
@property(nonatomic) __weak id <SCMyFriendCellViewDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)buttonV2Pressed:(id)arg1 friend:(id)arg2;
- (_Bool)pointInsideAddFriendButton:(struct CGPoint)arg1;
- (void)touchesEnded:(id)arg1 withEvent:(id)arg2;
- (void)toggleRightOffset:(_Bool)arg1;
- (void)setHighlightedState:(_Bool)arg1;
- (void)setProfilePictureViewWithFriend:(id)arg1;
- (void)hideSubLabelAnimated:(_Bool)arg1;
- (void)showSubLabelAnimated:(_Bool)arg1;
- (void)updateWithSubLabelText:(id)arg1 animated:(_Bool)arg2;
- (void)updateWithNameLabeText:(id)arg1;
- (void)setAddFriendButtonOn:(_Bool)arg1;
- (void)setNameLabelText:(id)arg1 subLabelText:(id)arg2 Friend:(id)arg3 buttonState:(long long)arg4 alreadyAdded:(_Bool)arg5 myFriendCellType:(long long)arg6 selected:(_Bool)arg7;
- (id)initWithStyleKey:(id)arg1 page:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

