//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSObject<OS_dispatch_queue>, NSURL, SCNetworkConnectivityListenerAnnouncer, SCQueuePerformer;

@interface SCNetworkConnectivityAnnouncer : NSObject
{
    SCNetworkConnectivityListenerAnnouncer *_announcer;
    NSURL *_defaultURL;
    NSObject<OS_dispatch_queue> *_queue;
    SCQueuePerformer *_performer;
    struct __SCNetworkReachability *_networkReachability;
    long long _status;
}

+ (id)sharedInstance;
- (void).cxx_destruct;
- (void)_stopMonitoringNetworkReachability;
- (void)_startMonitoringNetworkReachability;
- (void)removeListener:(id)arg1;
- (void)addListener:(id)arg1;
- (id)initWithDefaultURL:(id)arg1;

@end

