//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "FindNearbySnapchattersWorkerDelegate.h"
#import "SCFriendProfileCellViewDelegate.h"
#import "SCMiniProfileBaseViewDelegate.h"
#import "SWTableViewCellDelegate.h"
#import "UITableViewDataSource.h"
#import "UITableViewDelegate.h"

@class AddFriendsDelegateObject, NSMutableArray, NSMutableSet, NSString, SCFindNearbySnapchattersWorker, SCNearbyPopupView, SCSWFriendProfileCell, UIViewController;

@interface SCNearbyPopupController : NSObject <SCMiniProfileBaseViewDelegate, FindNearbySnapchattersWorkerDelegate, UITableViewDataSource, UITableViewDelegate, SCFriendProfileCellViewDelegate, SWTableViewCellDelegate>
{
    UIViewController *_parentViewController;
    SCNearbyPopupView *_nearbyPopupView;
    SCFindNearbySnapchattersWorker *_nearbyWorker;
    NSMutableArray *_nearbySnapchatterModels;
    NSMutableSet *_nearbySnapchatterIds;
    AddFriendsDelegateObject *_addFriendsDelegate;
    SCSWFriendProfileCell *_bottomCell;
}

- (void).cxx_destruct;
- (void)reloadData;
- (void)didDisplayProfilePictureOnCellView:(id)arg1 onThumbnail:(id)arg2 friend:(id)arg3;
- (void)friendProfileCellView:(id)arg1 addFriendPressed:(id)arg2 friend:(id)arg3;
- (id)getSwipeableCellButtons;
- (id)_getFriendProfileCellForFriend:(id)arg1 onTableView:(id)arg2 forRowAtindexPath:(id)arg3;
- (id)friendForIndex:(long long)arg1;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (void)alertView:(id)arg1 clickedButtonAtIndex:(long long)arg2;
- (void)onNearbyFinderInterrupted:(long long)arg1;
- (void)onNearbyWorkerCheckpointReached;
- (void)onNearbySnapchattersFound:(id)arg1;
- (void)onNearbyFinderStarted;
- (id)getPageName;
- (void)miniProfileWasDismissed:(id)arg1;
- (_Bool)isPopped;
- (void)pop;
- (void)stopSearching;
- (void)startSearching;
- (void)_reloadData;
- (void)dealloc;
- (id)initWithParentViewController:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

