//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "GenericSettingsViewController.h"

#import "SCLayoutAccessoryTableViewCellDelegate.h"
#import "UITableViewDataSource.h"
#import "UITableViewDelegate.h"

@class NSArray, NSString, UITableView;

@interface SCNotificationSettingsViewController : GenericSettingsViewController <UITableViewDataSource, UITableViewDelegate, SCLayoutAccessoryTableViewCellDelegate>
{
    NSArray *_settingsTags;
    _Bool _notificationSoundsOn;
    _Bool _notificationRingOn;
    UITableView *_tableView;
}

@property(retain, nonatomic) UITableView *tableView; // @synthesize tableView=_tableView;
@property(nonatomic) _Bool notificationRingOn; // @synthesize notificationRingOn=_notificationRingOn;
@property(nonatomic) _Bool notificationSoundsOn; // @synthesize notificationSoundsOn=_notificationSoundsOn;
- (void).cxx_destruct;
- (void)switchChanged:(id)arg1;
- (_Bool)isSwitchOnForAdditionalServiceSetting:(long long)arg1;
- (id)newAttributionLabel;
- (id)newHeaderTextLabel;
- (id)newSwitchViewForSettingTag:(long long)arg1;
- (void)layoutAccessoryTableViewCell:(id)arg1 textLabel:(id)arg2 attributionLabel:(id)arg3;
- (struct CGRect)layoutAccessoryTableViewCell:(id)arg1 frameForAccessoryView:(id)arg2;
- (void)presentReceiveNotifsFromSettings;
- (id)scSettingTableReceiveNotifsFromCell:(id)arg1 accessibilityLabel:(id)arg2;
- (id)toggleRingCell;
- (id)toggleSoundsCell;
- (id)createToggleCellWithIdentifier:(id)arg1 text:(id)arg2 subtext:(id)arg3 tag:(long long)arg4;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (id)tableView:(id)arg1 viewForHeaderInSection:(long long)arg2;
- (double)tableView:(id)arg1 heightForHeaderInSection:(long long)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (double)tableView:(id)arg1 heightForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (void)updateNotificationSettingsIfNecessary;
- (void)observeValueForKeyPath:(id)arg1 ofObject:(id)arg2 change:(id)arg3 context:(void *)arg4;
- (void)leftButtonPressed;
- (id)titleForHeader:(id)arg1;
- (unsigned long long)supportedInterfaceOrientations;
- (void)dealloc;
- (void)resetView;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewWillResignActive;
- (void)viewDidLoad;
- (void)loadView;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

