//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"
#import "SCOperaEventListener.h"

@class NSDictionary, NSString;

@protocol SCOperaSession <NSObject, SCOperaEventListener>
- (_Bool)shouldHandleEvent:(NSString *)arg1 context:(NSDictionary *)arg2 params:(NSDictionary *)arg3;
@end

