//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString, SCOperaViewModel, UIColor;

@interface SCOperaConfiguration : NSObject
{
    _Bool _rotationDisabled;
    _Bool _disableRemoteVideoControls;
    _Bool _shouldUseRemoteVideoProxy;
    SCOperaViewModel *_viewModel;
    id <SCOperaViewModelsManipulator> _modelManipulator;
    double _pageHorizontalMargin;
    double _pageVerticalMargin;
    UIColor *_backgroundColor;
    UIColor *_primaryColor;
    id <SCOperaImageProvider> _imageProvider;
    id <SCOperaDeviceOrientationMonitor> _deviceOrientationMonitor;
    id <SCOperaAudioStatusProvider> _audioStatusProvider;
    NSString *_accessibilityLabel;
    id <SCOperaViewLogger> _pageViewLogger;
    NSString *_pageViewName;
    double _longPressMinimumPressDuration;
    long long _remoteVideoCaptionDisplayStrategy;
    id <SCOperaRemoteVideoPreloadStrategy> _remoteVideoPreloadStrategy;
    id <SCOperaRemoteVideoPropertiesProvider> _remoteVideoPropertiesProvider;
    id <SCOperaActivelyDisplayMediaStrategy> _displayMediaStrategy;
    id <SCOperaSafeBrowsingChecker> _safeBrowsingChecker;
    id <SCOperaSubscriptionChecker> _subscriptionChecker;
    struct CGRect _bounds;
}

@property(retain, nonatomic) id <SCOperaSubscriptionChecker> subscriptionChecker; // @synthesize subscriptionChecker=_subscriptionChecker;
@property(retain, nonatomic) id <SCOperaSafeBrowsingChecker> safeBrowsingChecker; // @synthesize safeBrowsingChecker=_safeBrowsingChecker;
@property(retain, nonatomic) id <SCOperaActivelyDisplayMediaStrategy> displayMediaStrategy; // @synthesize displayMediaStrategy=_displayMediaStrategy;
@property(nonatomic) _Bool shouldUseRemoteVideoProxy; // @synthesize shouldUseRemoteVideoProxy=_shouldUseRemoteVideoProxy;
@property(retain, nonatomic) id <SCOperaRemoteVideoPropertiesProvider> remoteVideoPropertiesProvider; // @synthesize remoteVideoPropertiesProvider=_remoteVideoPropertiesProvider;
@property(retain, nonatomic) id <SCOperaRemoteVideoPreloadStrategy> remoteVideoPreloadStrategy; // @synthesize remoteVideoPreloadStrategy=_remoteVideoPreloadStrategy;
@property(nonatomic) long long remoteVideoCaptionDisplayStrategy; // @synthesize remoteVideoCaptionDisplayStrategy=_remoteVideoCaptionDisplayStrategy;
@property(nonatomic) _Bool disableRemoteVideoControls; // @synthesize disableRemoteVideoControls=_disableRemoteVideoControls;
@property(nonatomic) double longPressMinimumPressDuration; // @synthesize longPressMinimumPressDuration=_longPressMinimumPressDuration;
@property(copy, nonatomic) NSString *pageViewName; // @synthesize pageViewName=_pageViewName;
@property(retain, nonatomic) id <SCOperaViewLogger> pageViewLogger; // @synthesize pageViewLogger=_pageViewLogger;
@property(copy, nonatomic) NSString *accessibilityLabel; // @synthesize accessibilityLabel=_accessibilityLabel;
@property(retain, nonatomic) id <SCOperaAudioStatusProvider> audioStatusProvider; // @synthesize audioStatusProvider=_audioStatusProvider;
@property(retain, nonatomic) id <SCOperaDeviceOrientationMonitor> deviceOrientationMonitor; // @synthesize deviceOrientationMonitor=_deviceOrientationMonitor;
@property(retain, nonatomic) id <SCOperaImageProvider> imageProvider; // @synthesize imageProvider=_imageProvider;
@property(nonatomic) _Bool rotationDisabled; // @synthesize rotationDisabled=_rotationDisabled;
@property(nonatomic) struct CGRect bounds; // @synthesize bounds=_bounds;
@property(retain, nonatomic) UIColor *primaryColor; // @synthesize primaryColor=_primaryColor;
@property(retain, nonatomic) UIColor *backgroundColor; // @synthesize backgroundColor=_backgroundColor;
@property(nonatomic) double pageVerticalMargin; // @synthesize pageVerticalMargin=_pageVerticalMargin;
@property(nonatomic) double pageHorizontalMargin; // @synthesize pageHorizontalMargin=_pageHorizontalMargin;
@property(retain, nonatomic) id <SCOperaViewModelsManipulator> modelManipulator; // @synthesize modelManipulator=_modelManipulator;
@property(readonly, nonatomic) SCOperaViewModel *viewModel; // @synthesize viewModel=_viewModel;
- (void).cxx_destruct;
- (id)initWithViewModel:(id)arg1;

@end

