//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

#import "SCOperaDockableViewController.h"
#import "SCOperaLayerViewController.h"

@class FBKVOController, NSNotificationCenter, NSString, SCOperaEventListenerAnnouncer, SCOperaSharedResourceManager, SCOperaVideoLayer, SCOperaVideoLayerView, SCStopwatch;

@interface SCOperaVideoLayerViewController : UIViewController <SCOperaLayerViewController, SCOperaDockableViewController>
{
    SCOperaVideoLayerView *_layerView;
    FBKVOController *_kvoController;
    NSNotificationCenter *_notificationCenter;
    SCOperaEventListenerAnnouncer *_eventAnnouncer;
    SCOperaSharedResourceManager *_sharedResourceManager;
    _Bool _fullyViewed;
    double _durationSec;
    SCStopwatch *_mediaDisplayStopWatch;
    id <SCOperaPageableViewControllerDelegate> _pageableViewControllerDelegate;
    SCOperaVideoLayer *_layer;
}

+ (id)layerViewControllerWithLayer:(id)arg1 configuration:(id)arg2 kvoController:(id)arg3 mediaDisplayStopwatch:(id)arg4 eventAnnouncer:(id)arg5 sharedResourceManager:(id)arg6 notificationCenter:(id)arg7;
+ (id)layerViewControllerWithLayer:(id)arg1 configuration:(id)arg2 eventAnnouncer:(id)arg3;
@property(retain, nonatomic) SCOperaVideoLayer *layer; // @synthesize layer=_layer;
@property(nonatomic) __weak id <SCOperaPageableViewControllerDelegate> pageableViewControllerDelegate; // @synthesize pageableViewControllerDelegate=_pageableViewControllerDelegate;
- (void).cxx_destruct;
- (void)heightToWidthAspectRatio:(CDUnknownBlockType)arg1;
- (unsigned long long)docking;
- (void)rotateBasedOnOrientation;
- (void)playerItemDidReachEnd:(id)arg1;
- (void)loadView;
- (_Bool)disablePaging;
- (void)teardown;
- (id)shareableMedia;
- (id)currentViewParameters;
- (void)setVolume:(double)arg1;
- (void)resume;
- (void)pause;
- (void)viewDidFullyDisappear;
- (void)viewDidPartiallyAppearWithCurrentViewRelativePosition:(unsigned long long)arg1;
- (void)neighborViewDidFullyAppearWithCurrentViewRelativePosition:(unsigned long long)arg1;
- (void)viewDidFullyAppear;
- (id)layerView;
- (id)initWithLayer:(id)arg1 configuration:(id)arg2 kvoController:(id)arg3 mediaDisplayStopwatch:(id)arg4 eventAnnouncer:(id)arg5 sharedResourceManager:(id)arg6 notificationCenter:(id)arg7;
- (id)initWithLayer:(id)arg1 configuration:(id)arg2 eventAnnouncer:(id)arg3;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

