//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSURL, UIImage;

@interface SCOperaShareableMedia : NSObject
{
    long long _mediaType;
    UIImage *_image;
    NSURL *_videoURL;
    NSURL *_remoteURL;
    CDUnknownBlockType _savableImageProvider;
}

@property(readonly, nonatomic) CDUnknownBlockType savableImageProvider; // @synthesize savableImageProvider=_savableImageProvider;
@property(readonly, nonatomic) NSURL *remoteURL; // @synthesize remoteURL=_remoteURL;
@property(readonly, nonatomic) NSURL *videoURL; // @synthesize videoURL=_videoURL;
@property(readonly, nonatomic) UIImage *image; // @synthesize image=_image;
@property(readonly, nonatomic) long long mediaType; // @synthesize mediaType=_mediaType;
- (void).cxx_destruct;
- (id)initWithVideoURL:(id)arg1;
- (id)initWithShareableImage:(id)arg1 savableImageProvider:(CDUnknownBlockType)arg2 remoteUrl:(id)arg3;
- (id)initWithShareableImage:(id)arg1 savableImageProvider:(CDUnknownBlockType)arg2;

@end

