//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "UIViewControllerAnimatedTransitioning.h"
#import "UIViewControllerInteractiveTransitioning.h"

@class NSString, UIView, UIViewController;

@interface SCOperaInlineVideoDismissalAnimator : NSObject <UIViewControllerAnimatedTransitioning, UIViewControllerInteractiveTransitioning>
{
    UIView *_blackView;
    UIView *_backgroundView;
    struct CGRect _endingFrame;
    id <UIViewControllerContextTransitioning> _transitionContext;
    UIViewController *_dismissingController;
    id <SCOperaDismissInlineVideoAnimatorDelegate> _delegate;
}

@property(nonatomic) __weak id <SCOperaDismissInlineVideoAnimatorDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)finishPan:(id)arg1;
- (void)didPan:(id)arg1;
- (double)ratio:(double)arg1;
- (void)cancelTransition;
- (void)finishDismiss;
- (_Bool)shouldDismissWithVelocity:(struct CGPoint)arg1 translation:(struct CGPoint)arg2;
- (double)transitionDuration:(id)arg1;
- (void)startAnimatingWithContext:(id)arg1;
- (void)animateTransition:(id)arg1;
- (void)startInteractiveTransition:(id)arg1;
- (id)initWithBlackView:(id)arg1 endingFrame:(struct CGRect)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

