//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIScrollView.h"

#import "UIScrollViewDelegate.h"

@class CADisplayLink, NSString, UITapGestureRecognizer;

@interface SCOperaScrollView : UIScrollView <UIScrollViewDelegate>
{
    unsigned long long _currentScrollDirection;
    struct CGPoint _previousOffset;
    struct CGPoint _offsetBeforeScrolling;
    UITapGestureRecognizer *_tapGestureRecognizer;
    CADisplayLink *_scrollDisplayLink;
    id <SCOperaScrollViewDelegate> _operaScrollViewDelegate;
}

@property(nonatomic) __weak id <SCOperaScrollViewDelegate> operaScrollViewDelegate; // @synthesize operaScrollViewDelegate=_operaScrollViewDelegate;
- (void).cxx_destruct;
- (_Bool)_isScrollingDiagonally;
- (void)subviewScrollViewDidStartScrolling;
- (void)subviewScrollViewDidStopScrollingWithBoundaryHit:(_Bool)arg1;
- (void)_scrollViewDidChangeContentOffsetWithDeferredCallback;
- (void)_scrollViewDidEndScrolling;
- (void)scrollViewDidEndScrollingAnimation:(id)arg1;
- (void)scrollViewDidEndDragging:(id)arg1 willDecelerate:(_Bool)arg2;
- (void)scrollViewDidEndDecelerating:(id)arg1;
- (void)scrollViewDidScroll:(id)arg1;
- (void)didTap:(id)arg1;
- (_Bool)isScrolling;
- (void)setContentOffsetWithoutCallback:(struct CGPoint)arg1 deferredCallback:(_Bool)arg2;
- (void)setContentOffsetWithoutCallback:(struct CGPoint)arg1;
- (void)_setupTapGesture;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

