//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class SCOperaPage;

@interface SCOperaViewModel : NSObject
{
    SCOperaPage *_page;
    SCOperaViewModel *_left;
    SCOperaViewModel *_top;
    SCOperaViewModel *_right;
    SCOperaViewModel *_bottom;
    SCOperaViewModel *_previous;
    SCOperaViewModel *_next;
}

+ (id)dismissViewModel;
+ (id)viewModelWithPage:(id)arg1;
+ (id)viewModelWithProperties:(id)arg1;
+ (id)verticalViewModelsWithViewModel:(id)arg1;
+ (id)horizontalViewModelsWithViewModel:(id)arg1;
@property(retain, nonatomic) SCOperaViewModel *next; // @synthesize next=_next;
@property(retain, nonatomic) SCOperaViewModel *previous; // @synthesize previous=_previous;
@property(retain, nonatomic) SCOperaViewModel *bottom; // @synthesize bottom=_bottom;
@property(retain, nonatomic) SCOperaViewModel *right; // @synthesize right=_right;
@property(retain, nonatomic) SCOperaViewModel *top; // @synthesize top=_top;
@property(retain, nonatomic) SCOperaViewModel *left; // @synthesize left=_left;
@property(retain, nonatomic) SCOperaPage *page; // @synthesize page=_page;
- (void).cxx_destruct;
- (id)_initWithPage:(id)arg1;

@end

