//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSDictionary, NSMutableDictionary, NSString;

@interface SCPageViewLogger : NSObject
{
    _Bool _shouldLogPageView;
    NSMutableDictionary *_recordingPages;
    NSMutableDictionary *_startedPages;
    NSString *_currentPage;
    NSString *_sourcePage;
    id <SCPerforming> _performer;
    NSDictionary *_lastRecordingPages;
}

+ (id)shared;
@property(readonly, nonatomic) NSDictionary *lastRecordingPages; // @synthesize lastRecordingPages=_lastRecordingPages;
@property(nonatomic) _Bool shouldLogPageView; // @synthesize shouldLogPageView=_shouldLogPageView;
@property(retain, nonatomic) id <SCPerforming> performer; // @synthesize performer=_performer;
@property(retain, nonatomic) NSString *sourcePage; // @synthesize sourcePage=_sourcePage;
@property(retain, nonatomic) NSString *currentPage; // @synthesize currentPage=_currentPage;
@property(readonly, nonatomic) NSMutableDictionary *startedPages; // @synthesize startedPages=_startedPages;
@property(readonly, nonatomic) NSMutableDictionary *recordingPages; // @synthesize recordingPages=_recordingPages;
- (void).cxx_destruct;
- (id)ownerForPage:(id)arg1;
- (id)pageToOwnerMappingDict;
- (id)getCurrentPage;
- (id)getSourcePage;
- (void)testAndRemoveStartedPage:(id)arg1;
- (void)addStartedPage:(id)arg1;
- (void)logPageViewSession:(id)arg1;
- (void)endPageView:(id)arg1 withEndTime:(double)arg2 exitEvent:(long long)arg3;
- (void)endAllRecordingPageViewsWithExitEvent:(long long)arg1;
- (void)didResignActive:(id)arg1;
- (void)didBecomeActive;
- (void)didEnterBackground:(id)arg1;
- (void)endPageView:(id)arg1 withExitEvent:(long long)arg2;
- (void)endPageView:(id)arg1;
- (void)startPageView:(id)arg1 fromReferrer:(id)arg2;
- (void)startPageView:(id)arg1;
- (id)init;

@end

