//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@interface SCPermissionRequester : NSObject
{
}

+ (void)openSystemPermisionSetting:(id)arg1;
+ (_Bool)promptToChangeSettingsIfPossibleWithAlertTitle:(id)arg1 message:(id)arg2 permissionKey:(id)arg3;
+ (void)requestMicrophone;
+ (void)requestPhotos;
+ (void)requestLocation;
+ (void)requestNotifications;
+ (void)requestCamera;
+ (void)_requestUserSpecificContactAccess;
+ (void)requestContacts;

@end

