//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSCoding.h"

@class NSMutableDictionary;

@interface SCPersistingSnapsStateManager : NSObject <NSCoding>
{
    NSMutableDictionary *_snapsNeedToBeUpdated;
    NSMutableDictionary *_storySnapsNeedToBeUpdated;
}

+ (id)path;
+ (_Bool)initialized;
+ (id)shared;
@property(retain, nonatomic) NSMutableDictionary *storySnapsNeedToBeUpdated; // @synthesize storySnapsNeedToBeUpdated=_storySnapsNeedToBeUpdated;
@property(retain, nonatomic) NSMutableDictionary *snapsNeedToBeUpdated; // @synthesize snapsNeedToBeUpdated=_snapsNeedToBeUpdated;
- (void).cxx_destruct;
- (void)networkReachabilityDidChange:(id)arg1;
- (void)_removeServerUpdatedStorySnaps:(id)arg1;
- (void)_removeServerUpdatedSnaps:(id)arg1;
- (void)flushSnapState;
- (void)_ensureNonNilObjects;
- (void)_updateStorySnapsNeedToBeUpdated;
- (void)_updateSnapsNeedToBeUpdated;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)init;
- (_Bool)saveState;
- (void)dealloc;

@end

