//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableDictionary, NSString;

@interface SCPreviewLogger : NSObject
{
    long long _pickerClosedWithButtonCount;
    long long _pickerClosedWithBackCount;
    long long _stickerAddedCount;
    long long _stickerDeletedCount;
    long long _stickerTrackingNumberTotal;
    double _pickerOpenDuration;
    double _pickerOpenedStart;
    NSMutableDictionary *_stickerFrequency;
    double _viewingTime;
    double _viewingStartTimeInterval;
    _Bool _viewingStarted;
    NSString *_context;
    long long _pickerOpenedCount;
}

@property(readonly, nonatomic) long long pickerOpenedCount; // @synthesize pickerOpenedCount=_pickerOpenedCount;
@property(copy, nonatomic) NSString *context; // @synthesize context=_context;
- (void).cxx_destruct;
- (void)closedStickerPicker:(long long)arg1;
- (void)openedStickerPicker;
- (void)logStickerRemoved:(id)arg1;
- (void)logStickerTracked:(id)arg1;
- (void)logStickerAdded:(id)arg1;
- (void)logStickerPickerEvent:(id)arg1;
- (id)stickerPickerLoggingParameters:(id)arg1;
- (double)viewingTime;
- (void)viewingEnded;
- (void)viewingStarted;
- (void)logPreviewScreenshot:(id)arg1;
- (void)logSnapPreviewAction:(id)arg1 ephemeralMedia:(id)arg2 action:(long long)arg3;
- (void)logDirectSnapCreate:(id)arg1;
- (id)init;

@end

