//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class SCPreviewSnapSenderConfiguration;

@interface SCPreviewSnapSender : NSObject
{
    SCPreviewSnapSenderConfiguration *_configuration;
    id <SendSnapNavigationControllerDelegate> _delegate;
    id <SCInviteSnapSenderDelegate> _inviteSnapSenderDelegate;
}

@property(nonatomic) __weak id <SCInviteSnapSenderDelegate> inviteSnapSenderDelegate; // @synthesize inviteSnapSenderDelegate=_inviteSnapSenderDelegate;
@property(nonatomic) __weak id <SendSnapNavigationControllerDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)_sendSnapAndPostStory:(id)arg1 toRecipients:(id)arg2 invitedRecipients:(id)arg3 postToMyStory:(_Bool)arg4 officialStories:(id)arg5 sharedStories:(id)arg6 fromPreview:(_Bool)arg7;
- (void)_postStory:(id)arg1 postToMyStory:(_Bool)arg2 officialStories:(id)arg3 sharedStories:(id)arg4 fromPreview:(_Bool)arg5;
- (void)_configureUserPostedTimestampForStory:(id)arg1;
- (void)_sendSnap:(id)arg1 toRecipients:(id)arg2 invitedRecipients:(id)arg3 fromPreview:(_Bool)arg4;
- (void)sendDiscoverMessage:(id)arg1 toRecipients:(id)arg2;
- (void)sendChatSharedMessage:(id)arg1 toRecipients:(id)arg2;
- (void)sendEphemeralMedia:(id)arg1 toRecipients:(id)arg2 invitedRecipients:(id)arg3 postToMyStory:(_Bool)arg4 officialStories:(id)arg5 sharedStories:(id)arg6 fromPreview:(_Bool)arg7;
- (id)initWithConfiguration:(id)arg1;

@end

