//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class Friend, UIImageView;

@interface SCProfilePictureThumbnail : UIView
{
    long long _style;
    _Bool _thumbnailLoaded;
    Friend *_friend;
    id <SCProfilePictureThumbnailDelegate> _delegate;
    UIImageView *_profileImageView;
    UIImageView *_ghostBorderView;
    UIImageView *_ghostFaceView;
}

+ (id)thumbnailWithFriend:(id)arg1 contexts:(id)arg2 style:(long long)arg3 delegate:(id)arg4;
@property(retain, nonatomic) UIImageView *ghostFaceView; // @synthesize ghostFaceView=_ghostFaceView;
@property(retain, nonatomic) UIImageView *ghostBorderView; // @synthesize ghostBorderView=_ghostBorderView;
@property(retain, nonatomic) UIImageView *profileImageView; // @synthesize profileImageView=_profileImageView;
- (void).cxx_destruct;
- (id)friendPictureStatus;
- (id)_getImageArrayWithImageDataArray:(id)arg1 style:(long long)arg2;
- (void)_setGhostBorderImage:(long long)arg1;
- (double)_getThumbnailWidth;
- (_Bool)_hasThumbnail:(id)arg1;
- (_Bool)_needsUpdateWidth:(id)arg1;
- (void)_showGhostFace:(unsigned long long)arg1;
- (void)_showProfileImages:(id)arg1;
- (_Bool)updateWithFriend:(id)arg1 contexts:(id)arg2 style:(long long)arg3;
- (id)initWithFrame:(struct CGRect)arg1;

@end

