//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSObject<OS_dispatch_queue>, SCQueueWithCapacity;

@interface SCReachabilityFromNetworkPing : NSObject
{
    NSObject<OS_dispatch_queue> *_queue;
    SCQueueWithCapacity *_pingResults;
    unsigned long long _minErrorSamplesForNotReachable;
    double _earliestStartTimeAcceptable;
    long long _networkPingStatus;
}

@property(nonatomic) unsigned long long minErrorSamplesForNotReachable; // @synthesize minErrorSamplesForNotReachable=_minErrorSamplesForNotReachable;
@property long long networkPingStatus; // @synthesize networkPingStatus=_networkPingStatus;
- (void).cxx_destruct;
- (void)_updateReachabilityStatus;
- (void)didReceivePingResponse:(id)arg1;
- (id)init;

@end

