//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

#import "SCHeaderDelegate.h"
#import "SCRegisterDisplayNameViewDelegate.h"

@class NSString, SCRegisterDisplayNameView;

@interface SCRegisterDisplayNameViewController : UIViewController <SCHeaderDelegate, SCRegisterDisplayNameViewDelegate>
{
    _Bool _failedToSaveDisplayName;
    SCRegisterDisplayNameView *_registerDisplayNameView;
    long long _displayNameExpId;
}

@property(nonatomic) long long displayNameExpId; // @synthesize displayNameExpId=_displayNameExpId;
@property(nonatomic) _Bool failedToSaveDisplayName; // @synthesize failedToSaveDisplayName=_failedToSaveDisplayName;
@property(retain, nonatomic) SCRegisterDisplayNameView *registerDisplayNameView; // @synthesize registerDisplayNameView=_registerDisplayNameView;
- (void).cxx_destruct;
- (void)showErrorMessage:(id)arg1;
- (void)navigateToNextPage;
- (void)tryToSaveDisplayName;
- (void)rightButtonPressed;
- (void)didTapContinue;
- (void)textViewDidChange;
- (void)keyboardWillShow:(id)arg1;
- (_Bool)shouldPopToRootViewController;
- (unsigned long long)supportedInterfaceOrientations;
- (void)viewDidDisappear:(_Bool)arg1;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)viewDidLoad;
- (void)loadView;
- (id)getPageViewName;
- (id)initWithDisplayExperimentId:(long long)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

