//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SCRegisterV2BaseView.h"

#import "SCCaptchaViewDelegate.h"

@class NSString, SCCaptchaView, UIImageView, UILabel, UIScrollView;

@interface SCRegisterCaptchaV2View : SCRegisterV2BaseView <SCCaptchaViewDelegate>
{
    struct UIEdgeInsets _horizontalInsets;
    SCCaptchaView *_captchaView;
    UIScrollView *_scrollView;
    UIImageView *_ghostImageView;
    UILabel *_titleLabel;
    UILabel *_descLabel;
    UILabel *_errorLabel;
}

- (void).cxx_destruct;
- (void)setError:(id)arg1;
- (void)setFieldsEnabled:(_Bool)arg1;
- (void)setContinueButtonEnabled:(_Bool)arg1;
- (void)verifyCaptchaForPasswordReset:(id)arg1;
- (void)verifyCaptcha;
- (void)loadCaptchaForPasswordReset:(id)arg1;
- (void)loadCaptcha;
- (void)captchaViewDidDeselectAllImages:(id)arg1;
- (void)captchaViewDidSelectAnImage:(id)arg1;
- (void)captchaView:(id)arg1 didVerifyWithResult:(long long)arg2 enableFindFriends:(_Bool)arg3 isResetPassword:(_Bool)arg4 preAuthToken:(id)arg5 captchaCount:(unsigned long long)arg6;
- (void)captchaView:(id)arg1 didFinishLoadingCaptcha:(_Bool)arg2;
- (void)initCaptchaGridView;
- (void)initErrorLabel;
- (void)initDescription;
- (void)initTitle;
- (void)initHeaderImage;
- (void)initScrollView;
- (id)initWithFrame:(struct CGRect)arg1 delegate:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

