//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SCRegisterV2BaseView.h"

@class SCRegisterV2AddFriendsInterstitialView, UIButton, UILabel, UIView;

@interface SCRegisterV2AddFriendsView : SCRegisterV2BaseView
{
    struct UIEdgeInsets _horizontalInsets;
    UIView *_titleView;
    UILabel *_titleLabel;
    UILabel *_descLabel;
    UIView *_descLabelSeparator;
    SCRegisterV2AddFriendsInterstitialView *_interstitial;
    UIView *_mask;
    UIView *_currentTableView;
    double _headerOffset;
    double _descLabelMinOffset;
    UIButton *_skipButton;
}

@property(retain, nonatomic) UIButton *skipButton; // @synthesize skipButton=_skipButton;
- (void).cxx_destruct;
- (void)keyboardWillHide:(id)arg1;
- (void)keyboardWillShow:(id)arg1;
- (void)layoutSubviews;
- (_Bool)setHeaderOffset:(double)arg1;
- (void)setContinueActivityAnimating:(_Bool)arg1;
- (void)setContinueButtonHidden:(_Bool)arg1;
- (void)updateToInvite;
- (void)setTableView:(id)arg1;
- (void)hideIntersitial;
- (_Bool)isInterstitialShowing;
- (void)onSkipPressed;
- (void)removeObservers;
- (void)addObservers;
- (void)initSkipButton;
- (void)initGradient;
- (void)initNextButton;
- (void)initDescription;
- (void)initTitle;
- (void)initInterstitial;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1 delegate:(id)arg2;

@end

