//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

#import "SCRegisterPhoneVerificationV2ViewDelegate.h"
#import "SCRegisterV2ViewDelegate.h"

@class NSDictionary, NSString, NSTimer, SCRegisterPhoneVerificationV2View, UIToolbar;

@interface SCRegisterPhoneVerificationV2ViewController : UIViewController <SCRegisterV2ViewDelegate, SCRegisterPhoneVerificationV2ViewDelegate>
{
    NSString *_phoneNumber;
    NSString *_countryCode;
    UIToolbar *_blurOverlay;
    SCRegisterPhoneVerificationV2View *_phoneVerificationView;
    unsigned long long _resendTimeLeft;
    unsigned long long _verifyWithCodeAttemptCount;
    unsigned long long _resendVerificationCodeCount;
    _Bool _phoneCallDefault;
    _Bool _verifyCodeFailed;
    NSTimer *_resendTimer;
    NSString *_passwordResetUsernameOrEmail;
    NSString *_preAuthToken;
    NSDictionary *_context;
}

@property(retain, nonatomic) NSDictionary *context; // @synthesize context=_context;
- (void).cxx_destruct;
- (id)_pageNameForPageView;
- (void)updateContinueButtonState;
- (void)textFieldDidChange:(id)arg1;
- (_Bool)shouldPopToRootViewController;
- (void)backButtonPressed:(id)arg1;
- (void)updateContinueButtonResendLabel;
- (void)updateResendTimeLeft;
- (void)presentSendVerificationDialog:(_Bool)arg1;
- (void)continueButtonClicked;
- (void)keyboardWillHide:(id)arg1;
- (void)keyboardWillShow:(id)arg1;
- (void)finishRegistration;
- (void)presentNextViewController:(_Bool)arg1;
- (void)didRegisterPhoneNumber:(id)arg1;
- (void)_resetPasswordVerifyNumberDidSucceed:(id)arg1;
- (void)verifyNumberDidSucceed:(id)arg1;
- (void)verifyNumberDidFail:(id)arg1;
- (id)blurOverlay;
- (void)dealloc;
- (void)viewDidLoad;
- (void)viewDidDisappear:(_Bool)arg1;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)loadView;
- (_Bool)_isPasswordReset;
- (void)setPasswordResetWithUsernameOrEmail:(id)arg1 preAuthToken:(id)arg2;
- (id)initWithPhoneNumber:(id)arg1 forCountryCode:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

