//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SCRegisterV2BaseView.h"

#import "NewPasswordView.h"

@class NSString, SCTextView, UILabel, UIScrollView;

@interface SCResetPasswordV2View : SCRegisterV2BaseView <NewPasswordView>
{
    id <NewPasswordViewDelegate> _delegate;
    struct UIEdgeInsets _horizontalInsets;
    UILabel *_titleLabel;
    UILabel *_descLabel;
    UILabel *_newPwLabel;
    UILabel *_confirmPwLabel;
    UILabel *_subtextLabel;
    UIScrollView *_scrollView;
    SCTextView *_pwTextView;
    SCTextView *_confirmPwTextView;
}

@property(retain, nonatomic) SCTextView *confirmPwTextView; // @synthesize confirmPwTextView=_confirmPwTextView;
@property(retain, nonatomic) SCTextView *pwTextView; // @synthesize pwTextView=_pwTextView;
- (void).cxx_destruct;
- (void)setContinueIndicatorAnimating:(_Bool)arg1;
- (void)setStrengthIndicatorAnimating:(_Bool)arg1;
- (void)setIndicatorWithMessage:(id)arg1 color:(id)arg2;
- (void)setContinueEnabled:(_Bool)arg1;
- (void)inputKeyboardWillChangeFrame:(id)arg1;
- (void)setSubtextLabel:(id)arg1 message:(id)arg2 color:(id)arg3;
- (void)setPasswordConfirmError:(id)arg1;
- (void)setPasswordError:(id)arg1;
- (_Bool)textViewShouldBeginEditing:(id)arg1;
- (_Bool)textViewShouldReturn:(id)arg1;
- (void)initContinueButton;
- (void)initConfirmSubtextLabel;
- (void)initConfirmPwField;
- (void)initConfirmPwLabel;
- (void)initNewPwField;
- (void)initNewPwLabel;
- (void)initResetPwDescription;
- (void)initResetPwTitle;
- (void)initScrollView;
- (void)becomeFirstResponder;
- (id)initWithFrame:(struct CGRect)arg1 newPwDelegate:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

