//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

#import "SCRegisterViewProtocol.h"

@class NSString, SCRegisterV2BackButton, SCRegisterV2EnterButton;

@interface SCRegisterV2BaseView : UIView <SCRegisterViewProtocol>
{
    id <SCRegisterV2ViewDelegate> _delegate;
    SCRegisterV2BackButton *_backButton;
    SCRegisterV2EnterButton *_continueButton;
}

@property(retain, nonatomic) SCRegisterV2EnterButton *continueButton; // @synthesize continueButton=_continueButton;
@property(retain, nonatomic) SCRegisterV2BackButton *backButton; // @synthesize backButton=_backButton;
@property(nonatomic) __weak id <SCRegisterV2ViewDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)setFieldsEnabled:(_Bool)arg1;
- (void)setActivityAnimating:(_Bool)arg1;
- (void)keyboardWillHide:(id)arg1;
- (void)keyboardWillShow:(id)arg1;
- (void)showOrHideEnterButton;
- (_Bool)isInputIncomplete;
- (double)descriptionBottomPadding;
- (double)titleBottomPadding;
- (double)titleTopPaddingLarge;
- (double)loginTitleTopPadding;
- (double)titleTopPadding;
- (double)descHorizontalInset;
- (double)buttonHorizontalInset;
- (double)horizontalInset;
- (void)setupContinueButtonWithTitle:(id)arg1;
- (void)setupBackButton;
- (id)initWithFrame:(struct CGRect)arg1 delegate:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

