//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "SFSafariViewControllerDelegate.h"

@class NSString, NSURL;

@interface SCSafariCookieManager : NSObject <SFSafariViewControllerDelegate>
{
    NSString *_inquiryId;
    NSURL *_deferredDeepLink;
}

+ (id)shared;
@property(readonly, copy, nonatomic) NSURL *deferredDeepLink; // @synthesize deferredDeepLink=_deferredDeepLink;
- (void).cxx_destruct;
- (id)_getDeepLinkURL:(id)arg1;
- (void)safariViewController:(id)arg1 didCompleteInitialLoad:(_Bool)arg2;
- (_Bool)_shouldMatchSafariCookie;
- (id)getZeroPixelSafariViewControllerIfNewInstall;
- (void)clear;
- (void)_removeObservers;
- (void)_addObservers;
- (void)dealloc;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

