//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

#import "AddFriendByNameCellDelegate.h"
#import "FriendsTableIndexDelegate.h"
#import "SCSearchBarDelegate.h"
#import "SCSendToQuickAddCellViewDelegate.h"
#import "SCTimeProfilable.h"
#import "UIGestureRecognizerDelegate.h"
#import "UITableViewDataSource.h"
#import "UITableViewDelegate.h"

@class Friend, FriendsTableIndex, NSArray, NSDictionary, NSMutableArray, NSString, SCFriendFilter, SCMiniProfileController, SCSearchBar, SCSelectRecipientsConfiguration, UILabel, UITableView, UIViewController;

@interface SCSelectRecipientsView : UIView <SCSearchBarDelegate, AddFriendByNameCellDelegate, UITableViewDataSource, UITableViewDelegate, FriendsTableIndexDelegate, UIGestureRecognizerDelegate, SCSendToQuickAddCellViewDelegate, SCTimeProfilable>
{
    NSArray *_filteredFriends;
    NSArray *_friendKeys;
    NSArray *_friends;
    NSArray *_bestFriends;
    NSArray *_recentFriends;
    NSArray *_contacts;
    NSArray *_needsLoveFriends;
    NSArray *_suggestedFriends;
    NSMutableArray *_mutableRecipients;
    NSMutableArray *_mutableInvitedRecipients;
    NSMutableArray *_mutableJustAdded;
    NSMutableArray *_mutableSharedStoriesSelected;
    NSMutableArray *_mutableQuickAdd;
    NSDictionary *_suggestedReasons;
    _Bool _searching;
    _Bool _showingSearchBar;
    long long _recentsShown;
    long long _contactsShown;
    long long _addDiceEmojiToNeedsLove;
    SCSelectRecipientsConfiguration *_configuration;
    NSString *_friendUsernameToAutocheck;
    SCMiniProfileController *_miniProfileController;
    id <SCMiniProfileControllerDelegate> _delegate;
    UIViewController *_viewController;
    _Bool _collapsesSharedStoriesIntoLive;
    _Bool _collapsedLiveCellShowsSubtitle;
    _Bool _addToMyStory;
    _Bool _addToLiveStory;
    _Bool _addToMyGallery;
    _Bool _disallowAddFriend;
    _Bool _fastStoryPost;
    _Bool _searchable;
    FriendsTableIndex *_tableIndex;
    UITableView *_tableView;
    Friend *_replyFriend;
    NSArray *_sharedStories;
    NSArray *_officialStories;
    id <SCSelectGroupRecipientsDelegate> _groupRecipientsDelegate;
    id <SCSelectSingleRecipientDelegate> _singleRecipientDelegate;
    SCFriendFilter *_friendFilter;
    SCSearchBar *_searchBar;
    UILabel *_noSearchResultsLabel;
    NSMutableArray *_mutableOfficialStoriesSelected;
}

+ (long long)context;
+ (id)profiledSelectorNames;
@property(retain, nonatomic) NSMutableArray *mutableOfficialStoriesSelected; // @synthesize mutableOfficialStoriesSelected=_mutableOfficialStoriesSelected;
@property(retain, nonatomic) UILabel *noSearchResultsLabel; // @synthesize noSearchResultsLabel=_noSearchResultsLabel;
@property(retain, nonatomic) SCSearchBar *searchBar; // @synthesize searchBar=_searchBar;
@property(retain, nonatomic) SCFriendFilter *friendFilter; // @synthesize friendFilter=_friendFilter;
@property(nonatomic) __weak id <SCSelectSingleRecipientDelegate> singleRecipientDelegate; // @synthesize singleRecipientDelegate=_singleRecipientDelegate;
@property(nonatomic) __weak id <SCSelectGroupRecipientsDelegate> groupRecipientsDelegate; // @synthesize groupRecipientsDelegate=_groupRecipientsDelegate;
@property(copy, nonatomic) NSArray *officialStories; // @synthesize officialStories=_officialStories;
@property(copy, nonatomic) NSArray *sharedStories; // @synthesize sharedStories=_sharedStories;
@property(retain, nonatomic) Friend *replyFriend; // @synthesize replyFriend=_replyFriend;
@property(readonly, nonatomic) UITableView *tableView; // @synthesize tableView=_tableView;
@property(readonly, nonatomic) FriendsTableIndex *tableIndex; // @synthesize tableIndex=_tableIndex;
@property(nonatomic) _Bool searchable; // @synthesize searchable=_searchable;
@property(nonatomic) _Bool fastStoryPost; // @synthesize fastStoryPost=_fastStoryPost;
@property(nonatomic) _Bool disallowAddFriend; // @synthesize disallowAddFriend=_disallowAddFriend;
@property(nonatomic) _Bool addToMyGallery; // @synthesize addToMyGallery=_addToMyGallery;
@property(nonatomic) _Bool addToLiveStory; // @synthesize addToLiveStory=_addToLiveStory;
@property(nonatomic) _Bool addToMyStory; // @synthesize addToMyStory=_addToMyStory;
- (void).cxx_destruct;
- (id)excludedProfiledSelectorNames;
- (id)requestsContext;
- (void)popFirstSeenQuickAddAlert:(id)arg1 cellView:(id)arg2;
- (void)removeSelectedQuickAdd:(id)arg1;
- (_Bool)addSelectedQuickAdd:(id)arg1;
- (void)updateSuggestionProfileView:(id)arg1 withFriend:(id)arg2 isSelected:(_Bool)arg3;
- (void)sendToQuickAddCellView:(id)arg1 addFriendPressed:(id)arg2 friend:(id)arg3;
- (_Bool)shouldShowQuickAdd;
- (id)suggestedReasons:(id)arg1;
- (id)suggestedFriendsAsFriends:(id)arg1;
- (void)reloadSuggestedFriends;
- (void)_presentMiniProfile:(id)arg1;
- (void)_longPress:(id)arg1;
- (void)_initGesture;
- (_Bool)inMiniProfile;
- (void)showSearchingFor:(id)arg1;
- (void)showKeyboard:(_Bool)arg1;
- (void)updateActionCounters:(id)arg1;
- (void)scrollToIndex:(BOOL)arg1;
- (id)quickAdd;
- (id)justAdded;
- (id)invitedRecipients;
- (id)recipients;
- (_Bool)hasSelectedRecipients;
- (void)addedFriends:(id)arg1 removedFriends:(id)arg2 invitedFriends:(id)arg3;
- (void)searchBarKeyboardWillHide:(id)arg1;
- (void)searchBarDidBeginSearch:(id)arg1;
- (void)searchBar:(id)arg1 textDidChange:(id)arg2;
- (void)searchBar:(id)arg1 didSearch:(id)arg2;
- (id)getPageViewName;
- (void)updateNoSearchResultsLabel;
- (void)filterSearch:(id)arg1;
- (void)resetFriendFilter;
- (void)filterResults:(id)arg1;
- (void)scrollViewDidEndScrolling:(id)arg1;
- (void)scrollViewDidEndDecelerating:(id)arg1;
- (void)scrollViewDidEndDragging:(id)arg1 willDecelerate:(_Bool)arg2;
- (void)scrollViewWillBeginDragging:(id)arg1;
- (void)scrollViewDidScroll:(id)arg1;
- (void)didSelectAddFriendByNameCell:(id)arg1;
- (void)populateCellDisplayTextForFriend:(id)arg1 cell:(id)arg2;
- (void)populateCellDisplayTextForFriend:(id)arg1 selectContactCell:(id)arg2;
- (id)viewMoreCell:(id)arg1;
- (id)viewMoreContactsCell;
- (id)viewMoreRecentsCell;
- (unsigned long long)sectionTypeOfSection:(unsigned long long)arg1;
- (id)sectionTypes;
- (unsigned long long)quickAddSectionIndex;
- (unsigned long long)needsLoveSectionIndex;
- (unsigned long long)friendsSectionStartIndex;
- (unsigned long long)storiesSectionIndex;
- (id)getFriendAtIndexPath:(id)arg1;
- (void)removeFriendFromGroupSend:(id)arg1;
- (void)addFriendToGroupSend:(id)arg1;
- (void)addRecipient:(id)arg1;
- (void)_displayIntroSendForStory:(id)arg1 completion:(CDUnknownBlockType)arg2;
- (void)_displayIntroSendWithTitle:(id)arg1 message:(id)arg2 completion:(CDUnknownBlockType)arg3;
- (_Bool)_needsIntroSendForStory:(id)arg1;
- (void)didSelectPostSharedStoryCellWithSharedStory:(id)arg1;
- (void)didSelectPostOfficialStory:(id)arg1;
- (void)toggleSharedStory:(id)arg1;
- (void)didSelectPostLiveStoryCell;
- (void)didSelectPostMyStoryCell;
- (void)didSelectPostStoryCellAtIndexPath:(id)arg1;
- (void)didSelectCellAtIndexPath:(id)arg1;
- (void)tableView:(id)arg1 didSelectRowAtIndexPath:(id)arg2;
- (long long)indexOfSharedStoryAtIndexPath:(id)arg1;
- (id)officialStoryAtIndexPath:(id)arg1;
- (unsigned long long)storyRowTypeOfRowAtIndexPath:(id)arg1;
- (id)tableView:(id)arg1 viewForHeaderInSection:(long long)arg2;
- (void)tableView:(id)arg1 willDisplayCell:(id)arg2 forRowAtIndexPath:(id)arg3;
- (double)tableView:(id)arg1 heightForHeaderInSection:(long long)arg2;
- (id)tableView:(id)arg1 cellForRowAtIndexPath:(id)arg2;
- (long long)tableView:(id)arg1 numberOfRowsInSection:(long long)arg2;
- (long long)numberOfSectionsInTableView:(id)arg1;
- (void)didTapNeedsLoveHeader;
- (id)rollNeedsLoveFromSortedFriends:(id)arg1 excludingBestFriends:(id)arg2 andRecents:(id)arg3;
- (void)reloadContacts;
- (void)reloadFriends;
- (void)friendsDidChange;
- (void)updateSharedStories;
- (void)_setAddToMyGallery:(_Bool)arg1 reloadsCell:(_Bool)arg2 notifiesDelegate:(_Bool)arg3;
@property(nonatomic) _Bool bounces;
- (id)officialStoriesSelected;
- (id)sharedStoriesSelected;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1 configuration:(id)arg2 miniProfileDelegate:(id)arg3 viewController:(id)arg4;
- (id)initWithFrame:(struct CGRect)arg1 configuration:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

