//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

#import "SCSingleIconViewProtocol.h"

@class NSString, UIImage, UIImageView;

@interface SCSingleIconViewBase : UIView <SCSingleIconViewProtocol>
{
    UIImageView *imageView;
    UIImage *image;
    NSString *_logId;
}

@property(copy, nonatomic) NSString *logId; // @synthesize logId=_logId;
@property(retain, nonatomic) UIImageView *imageView; // @synthesize imageView;
- (void).cxx_destruct;
- (void)showGrayLoadingCircle;
@property(retain, nonatomic) UIImage *image; // @synthesize image;
- (void)setImageAlpha:(double)arg1;
- (void)showSpinner;
- (void)hideSpinner;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

