//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "SnapAdsLoggerAbstraction.h"

@class NSString;

@interface SCSnapAdsLoggerAbstractionImpl : NSObject <SnapAdsLoggerAbstraction>
{
}

- (void)debugInfoWithCompletion:(CDUnknownBlockType)arg1;
- (id)getAdsLogData;
- (id)prependDateTimeToString:(id)arg1;
- (void)log:(id)arg1;
- (void)logUserTrackedEvent:(id)arg1;
- (void)emitMetric:(id)arg1 parameters:(id)arg2 secretParameters:(id)arg3;
- (void)logTimedEventEnd:(id)arg1 withUniqueId:(id)arg2 withParameters:(id)arg3;
- (void)logTimedEventStart:(id)arg1 withUniqueId:(id)arg2 isUniqueEvent:(_Bool)arg3;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

