//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class SCButton, UIColor, UIImageView;

@interface SCSplashScreenView : UIView
{
    UIImageView *_ghostFaceImageView;
    SCButton *_loginButton;
    SCButton *_registerButton;
    id <SCSplashScreenViewDelegate> _delegate;
    UIColor *_backgroundPatternColor;
}

@property(retain, nonatomic) UIColor *backgroundPatternColor; // @synthesize backgroundPatternColor=_backgroundPatternColor;
@property(nonatomic) __weak id <SCSplashScreenViewDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)_touchUpOutside;
- (void)_touchDownInsideButton;
- (void)initGhostFaceImage;
- (void)initLoginButton;
- (void)initRegisterButton;
- (void)loadView;

@end

