//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray, UIView;

@interface SCStickerContainer : NSObject
{
    UIView *_staticStickersContainerView;
    UIView *_trackingStickersContainerView;
}

+ (id)renderableEmojiWithEmoji:(id)arg1;
@property(readonly, nonatomic) UIView *trackingStickersContainerView; // @synthesize trackingStickersContainerView=_trackingStickersContainerView;
@property(readonly, nonatomic) UIView *staticStickersContainerView; // @synthesize staticStickersContainerView=_staticStickersContainerView;
- (void).cxx_destruct;
- (void)setStickersState:(id)arg1 configuration:(CDUnknownBlockType)arg2;
- (id)stickersState;
@property(readonly, copy, nonatomic) NSArray *stickerViews;
@property(readonly, nonatomic) long long stickerCount;
- (id)videoTrackedImages;
- (id)staticStickersScreenshot;
- (_Bool)hasStaticStickers;
- (id)initWithFrame:(struct CGRect)arg1;

@end

