//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class SCStories;

@interface SCStoriesManager : NSObject
{
    SCStories *_stories;
}

+ (id)sharedInstance;
@property(retain, nonatomic) SCStories *stories; // @synthesize stories=_stories;
- (void).cxx_destruct;

@end

