//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SCSingleIconViewBase.h"

@class SCStoryLoadingIndicatorView;

@interface SCStoryIconView : SCSingleIconViewBase
{
    _Bool _isAnimating;
    SCStoryLoadingIndicatorView *_loadingView;
}

@property(retain, nonatomic) SCStoryLoadingIndicatorView *loadingView; // @synthesize loadingView=_loadingView;
- (void).cxx_destruct;
- (void)applicationWillEnterForeground:(id)arg1;
- (void)applicationDidEnterBackground:(id)arg1;
- (void)_log:(id)arg1;
- (void)_stopAnimating;
- (void)_startAnimating;
- (void)_resetIconView;
- (void)showGrayLoadingCircle;
- (void)setImageAlpha:(double)arg1;
- (void)hideSpinner;
- (void)showSpinner;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1;

@end

