//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SCStackedChatTableViewCell.h"

#import "SCBaseMediaFullScreenDelegate.h"
#import "SCBaseMediaFullScreenViewSource.h"
#import "SCExpandableMediaChatTableCell.h"

@class NSString, SCBaseMediaFullScreenBrowserController, UIViewController<SCChatCellBaseGestureDelegate>, UIWindow;

@interface SCStackedChatMediaChatTableViewCell : SCStackedChatTableViewCell <SCBaseMediaFullScreenDelegate, SCBaseMediaFullScreenViewSource, SCExpandableMediaChatTableCell>
{
    UIViewController<SCChatCellBaseGestureDelegate> *_parentVC;
    id <SCChatExpandableMediaChatTableCellDelegate> _delegate;
    UIWindow *_mediaFullScreenWindow;
    SCBaseMediaFullScreenBrowserController *_baseMediaBrowserController;
}

- (void).cxx_destruct;
- (_Bool)fullScreenIsShown;
- (void)dismissFullScreenView;
- (struct CGRect)destinationBoundingFrame;
- (id)thumbnailViewForMedia:(id)arg1;
- (void)fullScreenViewEndPanning;
- (void)fullScreenViewStartPanning;
- (void)fullScreenViewWasDismissed:(id)arg1;
- (void)fullScreenViewWillDismiss:(id)arg1;
- (void)handleTapForCellAtIndex:(long long)arg1;
- (id)baseMediaBrowserController;
- (id)viewModelList;
- (long long)numberOfSectionsInCollectionView:(id)arg1;
- (struct UIEdgeInsets)collectionView:(id)arg1 layout:(id)arg2 insetForSectionAtIndex:(long long)arg3;
- (long long)collectionView:(id)arg1 numberOfItemsInSection:(long long)arg2;
- (unsigned long long)_itemIndexWithIndexPath:(id)arg1 inCollectionView:(id)arg2;
- (void)collectionView:(id)arg1 didSelectItemAtIndexPath:(id)arg2;
- (id)mediaThumbnailViewForMedia:(id)arg1;
- (void)stopAnimations;
- (void)startAnimations;
- (void)clearContents;
- (id)initWithStyle:(long long)arg1 reuseIdentifier:(id)arg2 parentVC:(id)arg3 delegate:(id)arg4;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

