//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "SCTableIndexConfiguration.h"

@class NSString, UIColor;

@interface SCStoriesTableIndexConfiguration : NSObject <SCTableIndexConfiguration>
{
}

+ (id)configuration;
@property(readonly, nonatomic) UIColor *transitionScrollBarColor;
@property(readonly, nonatomic) UIColor *scrollBarBackgroundColor;
@property(readonly, nonatomic) UIColor *scrollBarColor;
@property(readonly, nonatomic) double scrollBarFastScrollingWidth;
@property(readonly, nonatomic) double scrollBarPressedWidth;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

