//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SCBaseMediaMessageViewModel.h"

@interface SCStoryReplyMediaMessageViewModel : SCBaseMediaMessageViewModel
{
}

+ (double)cornerRadius;
- (void)fetchVideoOverlayThumbnailWithSize:(struct CGSize)arg1 WithCompletionHandler:(CDUnknownBlockType)arg2;
- (void)fetchVideoOverlayWithCompletionHandler:(CDUnknownBlockType)arg1;
- (_Bool)containsVideo;
- (id)getCroppedThumbnailForVideoOverlayImage;
- (id)getCroppedThumbnailForImageToDisplay;
- (id)getCroppedThumbnailForImage:(id)arg1;
- (double)thumbnailWidth;
- (double)thumbnailHeight;
- (id)backgroundColorForChatLabel;
- (id)colorForChatLabel;
- (double)textBoxHeight;
- (double)textHeightForWidth:(double)arg1;
- (id)fontForChatLabel;
- (id)attributedText;
- (id)rawText;
- (id)storyReplyMediaMessage;
- (void)setMediaToDisplay:(id)arg1;

@end

