//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SCStillImageCaptureUnderexposureMethod.h"

@interface SCStillImageCaptureCompositionMethod : SCStillImageCaptureUnderexposureMethod
{
}

- (id)methodName;
- (void)captureStillImageOutput:(id)arg1 stillImageConnection:(id)arg2 capturerState:(id)arg3;

@end

