//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SCChatMediaMessage.h"

@class NSString;

@interface SCStoryReplyMediaMessage : SCChatMediaMessage
{
    _Bool _fullScreenVidLoggedThisSession;
    _Bool _thumbnailVidLoggedThisSession;
    NSString *_storyId;
    CDUnknownBlockType _completion;
}

+ (id)notifFailedToSendBgColor;
+ (id)notifSendSuccessTextColor;
@property(copy, nonatomic) CDUnknownBlockType completion; // @synthesize completion=_completion;
@property(nonatomic) _Bool thumbnailVidLoggedThisSession; // @synthesize thumbnailVidLoggedThisSession=_thumbnailVidLoggedThisSession;
@property(nonatomic) _Bool fullScreenVidLoggedThisSession; // @synthesize fullScreenVidLoggedThisSession=_fullScreenVidLoggedThisSession;
@property(copy, nonatomic) NSString *storyId; // @synthesize storyId=_storyId;
- (void).cxx_destruct;
- (void)imageProcessingDidSucceedForMedia:(id)arg1;
- (void)send;
- (id)sendJSON;
- (id)videoFilename;
- (id)logEventName;
- (long long)mediaType;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (void)initWithStoryId:(id)arg1 replyText:(id)arg2 mediaKey:(id)arg3 mediaIv:(id)arg4 mediaType:(long long)arg5;
- (id)initWithUsername:(id)arg1 dictionary:(id)arg2;

@end

