//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SCBaseMediaCardView.h"

#import "SCChatMediaCardViewDelegate.h"

@class NSString, SCChatMediaCardMediaView, SCStoryMediaCardViewModel, UILabel, UIView, UIViewController<SCChatCellGestureDelegate>;

@interface SCStoryMediaCardView : SCBaseMediaCardView <SCChatMediaCardViewDelegate>
{
    SCStoryMediaCardViewModel *_viewModel;
    UIViewController<SCChatCellGestureDelegate> *_parentVC;
    UIView *_titleContainerView;
    UILabel *_titleLabel;
    UILabel *_subtitleLabel;
    SCChatMediaCardMediaView *_storyThumbnailView;
}

- (void).cxx_destruct;
- (id)mediaThumbnailView;
- (void)didSetupMediaViewIncompleteDisplay;
- (void)didSetupMediaViewCompleteDisplay;
- (void)_setStoryThumbnail;
- (void)_setSubtitle:(id)arg1;
- (void)_setTitle:(id)arg1;
- (void)_renderPayload;
- (void)setViewModel:(id)arg1;
- (void)_initSubtitleLabel;
- (void)_initTitleLabel;
- (void)_initTitleContainerView;
- (void)_initStoryThumbnailView;
- (id)initWithParentVC:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

