//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "SCAdTransformListener.h"
#import "SCStoriesAutoAdvanceAdsDelegate.h"

@class FriendStories, NSString, SCAdsStories, SCAutoAdvanceAdsPlacement, SCStoriesAutoAdvanceAdViewTimer, Story;

@interface SCStoriesAutoAdvanceAdsManager : NSObject <SCAdTransformListener, SCStoriesAutoAdvanceAdsDelegate>
{
    SCAutoAdvanceAdsPlacement *_currentAdPlacement;
    long long _currentAdPlacementPosition;
    _Bool _retryAdRequest;
    SCAdsStories *_currentAdsStories;
    unsigned long long _minStoriesBeforeFirstAd;
    unsigned long long _minStoriesAfterLastAd;
    unsigned long long _minStoriesBetweenAds;
    unsigned long long _minTimeBetweenAdsInSeconds;
    _Bool _enabledAdsInAutoAdvance;
    _Bool _allowAdAfterSwipeToSkip;
    unsigned long long _storiesTotalCount;
    unsigned long long _storiesViewedCount;
    unsigned long long _snapsViewedCount;
    unsigned long long _nextAdsAfterStoriesCount;
    unsigned long long _adStoriesViewedCount;
    unsigned long long _adSnapsViewedCount;
    Story *_currentStory;
    FriendStories *_currentFriendsStories;
    SCStoriesAutoAdvanceAdViewTimer *_adViewTimer;
    long long _storySessionId;
}

+ (id)shared;
- (void).cxx_destruct;
- (void)onTransformComplete:(id)arg1;
- (long long)adStoryViewCountInSession;
- (long long)adSnapViewCountInSession;
- (void)handleNoFillAdStory;
- (id)currentAdsStories:(long long)arg1;
- (_Bool)isAdsStoryNoFill;
- (void)didUpdateStoriesCount:(unsigned long long)arg1;
- (void)didFinishStoriesInAutoAdvance:(id)arg1;
- (void)didStartStoriesInAutoAdvance:(id)arg1;
- (void)didHideSnapInAutoAdvance:(id)arg1;
- (void)didShowSnapInAutoAdvance:(id)arg1;
- (void)didFinishAutoAdvance;
- (void)didStartAutoAdvance:(unsigned long long)arg1 storySessionId:(long long)arg2;
- (void)cancelAdRequest;
- (void)makeAdRequest;
- (_Bool)isAdsStoryLoaded;
- (_Bool)isEnabled;
- (_Bool)canShowAd;
- (void)updateConfig:(id)arg1;
- (id)initWithConfig:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

