//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "SCViewingStoryViewControllerDelegate.h"

@class FriendStories, NSString, SCLeveledViewController, SCMediaView, SCOperaEventListenerAnnouncer, SCStoriesViewingSession, SCTileView, SCUserSession, SCViewControllerTransitionAnimator, SCViewingStoryViewController, UIViewController;

@interface SCStoryPresenter : NSObject <SCViewingStoryViewControllerDelegate>
{
    SCUserSession *_userSession;
    FriendStories *_friendStories;
    SCViewingStoryViewController *_baseStoryVC;
    SCLeveledViewController *_storyVC;
    UIViewController *_presentingViewController;
    SCTileView *_tappedTileView;
    SCOperaEventListenerAnnouncer *_eventAnnouncer;
    SCStoriesViewingSession *_storiesViewingSession;
    id <SCStoryPresenterDelegate> _delegate;
    id <SCStoryPresenterDataSource> _dataSource;
    SCViewControllerTransitionAnimator *_tileTransitionAnimator;
    SCMediaView *_mediaView;
}

@property(retain, nonatomic) SCMediaView *mediaView; // @synthesize mediaView=_mediaView;
@property(readonly, nonatomic) SCViewControllerTransitionAnimator *tileTransitionAnimator; // @synthesize tileTransitionAnimator=_tileTransitionAnimator;
@property(nonatomic) __weak id <SCStoryPresenterDataSource> dataSource; // @synthesize dataSource=_dataSource;
@property(nonatomic) __weak id <SCStoryPresenterDelegate> delegate; // @synthesize delegate=_delegate;
- (void).cxx_destruct;
- (void)_setupTimerConstraints;
- (void)_setupLeveledThumbnailsViewController;
- (void)_presentStoryImmediately;
- (void)_presentStoryFromTile;
- (void)_addStoryVC;
- (void)_didStopStory;
- (void)dismissStory;
- (_Bool)isPresentingStory;
- (void)cleanUpViewingStoriesState;
- (void)viewingStoryControllerDidBecomeUnloaded:(id)arg1;
- (void)viewingStoryController:(id)arg1 didResolveDeepLinkWithSharedId:(id)arg2 username:(id)arg3;
- (void)viewingStoryController:(id)arg1 failedToShowNextStorySnap:(id)arg2;
- (void)viewingStoryController:(id)arg1 didSelectDeleteStorySnap:(id)arg2;
- (void)viewingStoryController:(id)arg1 didSelectSaveStorySnap:(id)arg2;
- (void)hideMyStoryAndGoToFeed:(id)arg1;
- (void)hideMyStoryAndGoToChat:(id)arg1 friend:(id)arg2;
- (_Bool)shouldHideStoriesWhenPlayingStops:(long long)arg1;
- (void)didStartPullToDismissWithViewingStoryController:(id)arg1;
- (void)viewingStoryController:(id)arg1 didFinishStory:(id)arg2;
- (void)viewingStoryController:(id)arg1 didPullToDismissStory:(id)arg2 didFullyView:(_Bool)arg3 finishReason:(long long)arg4;
- (void)viewingStoryController:(id)arg1 didStopPlayingStory:(id)arg2 didFullyView:(_Bool)arg3 exitReason:(long long)arg4;
- (_Bool)viewingStoryController:(id)arg1 readyToShowNextStorySnap:(id)arg2;
- (void)willBeginAnimatingToDismissFromTileWithViewingStoryController:(id)arg1;
- (void)didCancelDismissingFromTileWithViewingStoryController:(id)arg1;
- (void)didFinishPresentingFromTileWithViewingStoryController:(id)arg1;
- (void)willBeginPresentingFromTileWithViewingStoryController:(id)arg1;
- (void)_playStoryWithInitialLoadingView:(_Bool)arg1 mediaView:(id)arg2;
- (void)presentFriendStories:(id)arg1 unviewed:(_Bool)arg2 showInitialLoadingView:(_Bool)arg3 viewingActionContext:(unsigned long long)arg4 tappedTileView:(id)arg5 viewLocation:(long long)arg6;
- (id)initWithPresentingViewController:(id)arg1 userSession:(id)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

