//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "SCTalkLoggerDelegate.h"

@class NSDate, NSString, SCTalkPromptRequestLogger;

@interface SCTalkLogger : NSObject <SCTalkLoggerDelegate>
{
    id <SCVideoChatLogProvider> _logProvider;
    _Bool _didLocalStartTheCall;
    unsigned long long _initialMediaType;
    unsigned long long _callMediaType;
    NSDate *_startCall;
    double _callDuration;
    NSDate *_startSendingAudio;
    NSDate *_startSendingVideo;
    double _secondsSendingAudio;
    double _secondsSendingVideo;
    NSDate *_startReceivingAudio;
    NSDate *_startReceivingVideo;
    double _secondsReceivingAudio;
    double _secondsReceivingVideo;
    NSDate *_startSymmetricCall;
    double _secondsInSymmetricCall;
    double _secondsRinging;
    NSDate *_startFullscreenWithKeyboard;
    NSDate *_startFullscreenWithNoKeyboard;
    double _secondsInFullscreenWithNoKeyboard;
    double _secondsInFullscreenWithKeyboard;
    NSDate *_startLocalVideoCircleMode;
    double _secondsLocalVideoInCircleMode;
    long long _sendingAudioCount;
    long long _sendingVideoCount;
    long long _chatMessageSentCount;
    long long _chatMessageReceivedCount;
    SCTalkPromptRequestLogger *_promptLogger;
}

+ (id)sharedInstance;
@property(readonly, nonatomic) SCTalkPromptRequestLogger *promptLogger; // @synthesize promptLogger=_promptLogger;
- (void).cxx_destruct;
- (void)ringingEndedWithDuration:(double)arg1;
- (void)logUserTrackedEvent:(id)arg1;
- (void)keyboardHiddenWhileOnFullscreen;
- (void)keyboardShownWhileOnFullscreen;
- (void)previewsWillExitFullscreen;
- (void)localVideoWillGoFullscreen;
- (void)localVideoInCircleMode;
- (void)chatMessageReceived;
- (void)chatMessageSent;
- (void)sendVideoCount;
- (void)sendAudioCount;
- (void)stopReceivingVideo;
- (void)startReceivingVideo;
- (void)stopSendingVideo;
- (void)startSendingVideo;
- (void)stopReceivingAudio;
- (void)startReceivingAudio;
- (void)stopSendingAudio;
- (void)startSendingAudio;
- (void)callMediaTypeChangedToVideo;
- (void)callEnded;
- (void)startCall:(_Bool)arg1 mediaType:(unsigned long long)arg2;
- (void)talkSessionAvailable;
- (void)_stopSymmetricCounterMaybe;
- (void)_startSymmetricCounterMaybe;
- (void)_endAnyActiveLogging;
- (double)_getSecondsFromDate:(id)arg1;
- (void)_cleanup;
- (void)setLogProvider:(id)arg1;
- (id)init;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

