//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

@class CAShapeLayer;

@interface SCTabBarBarView : UIView
{
    _Bool _darkModeEnabled;
    CAShapeLayer *_shapeLayer;
    struct CGSize _previousBoundsSize;
}

+ (Class)layerClass;
@property(nonatomic) struct CGSize previousBoundsSize; // @synthesize previousBoundsSize=_previousBoundsSize;
@property(retain, nonatomic) CAShapeLayer *shapeLayer; // @synthesize shapeLayer=_shapeLayer;
@property(nonatomic) _Bool darkModeEnabled; // @synthesize darkModeEnabled=_darkModeEnabled;
- (void).cxx_destruct;
- (id)normalBackgroundColor;
- (void)layoutSubviews;
- (id)initWithFrame:(struct CGRect)arg1;

@end

