//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIImageView.h"

@interface SCTabBarGradientView : UIImageView
{
    long long _style;
}

+ (long long)defaultStyle;
+ (void)setDefaultStyle:(long long)arg1;
@property(nonatomic) long long style; // @synthesize style=_style;
- (id)gradientImageForStyle:(long long)arg1;
- (void)styleDidChange:(id)arg1;
- (void)layoutGradient;
- (void)didMoveToSuperview;
- (void)dealloc;
- (id)init;

@end

