//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIView.h"

#import "UIGestureRecognizerDelegate.h"

@class NSArray, NSString, SCGradientView, SCTabBarBarView, SCTabBarVelocityDetectionGestureRecognizer, UIImageView;

@interface SCTabBarView : UIView <UIGestureRecognizerDelegate>
{
    _Bool _staticButtonOrigins;
    _Bool _transitioningToOrFromMultiplePages;
    _Bool _darkModeEnabled;
    _Bool _didUpdateFromAppStartup;
    NSArray *_items;
    id <SCTabBarViewDelegate> _delegate;
    id <SCTabBarViewDataSource> _dataSource;
    long long _selectedIndex;
    id <NSObject> _notificationObserver;
    UIView *_backgroundView;
    UIView *_backgroundMaskView;
    double _sideItemCenterOnCameraPage;
    double _sideItemCenterOnSidePage;
    SCTabBarBarView *_barView;
    SCTabBarVelocityDetectionGestureRecognizer *_screenEdgePanGestureRecognizer;
    SCGradientView *_lightGradientView;
    UIImageView *_darkGradientView;
    double _backgroundMaskPercent;
    struct _NSRange _lastKnownVisibleRange;
}

+ (_Bool)shouldShowCameraButtonInHeader;
+ (_Bool)shouldUseNewTabBar;
@property(nonatomic) _Bool didUpdateFromAppStartup; // @synthesize didUpdateFromAppStartup=_didUpdateFromAppStartup;
@property(nonatomic) double backgroundMaskPercent; // @synthesize backgroundMaskPercent=_backgroundMaskPercent;
@property(nonatomic, getter=isDarkModeEnabled) _Bool darkModeEnabled; // @synthesize darkModeEnabled=_darkModeEnabled;
@property(retain, nonatomic) UIImageView *darkGradientView; // @synthesize darkGradientView=_darkGradientView;
@property(retain, nonatomic) SCGradientView *lightGradientView; // @synthesize lightGradientView=_lightGradientView;
@property(nonatomic) struct _NSRange lastKnownVisibleRange; // @synthesize lastKnownVisibleRange=_lastKnownVisibleRange;
@property(retain, nonatomic) SCTabBarVelocityDetectionGestureRecognizer *screenEdgePanGestureRecognizer; // @synthesize screenEdgePanGestureRecognizer=_screenEdgePanGestureRecognizer;
@property(retain, nonatomic) SCTabBarBarView *barView; // @synthesize barView=_barView;
@property(nonatomic) double sideItemCenterOnSidePage; // @synthesize sideItemCenterOnSidePage=_sideItemCenterOnSidePage;
@property(nonatomic) double sideItemCenterOnCameraPage; // @synthesize sideItemCenterOnCameraPage=_sideItemCenterOnCameraPage;
@property(retain, nonatomic) UIView *backgroundMaskView; // @synthesize backgroundMaskView=_backgroundMaskView;
@property(retain, nonatomic) UIView *backgroundView; // @synthesize backgroundView=_backgroundView;
@property(retain, nonatomic) id <NSObject> notificationObserver; // @synthesize notificationObserver=_notificationObserver;
@property(nonatomic, getter=isTransitioningToOrFromMultiplePages) _Bool transitioningToOrFromMultiplePages; // @synthesize transitioningToOrFromMultiplePages=_transitioningToOrFromMultiplePages;
@property(nonatomic) long long selectedIndex; // @synthesize selectedIndex=_selectedIndex;
@property(nonatomic) _Bool staticButtonOrigins; // @synthesize staticButtonOrigins=_staticButtonOrigins;
@property(nonatomic) __weak id <SCTabBarViewDataSource> dataSource; // @synthesize dataSource=_dataSource;
@property(nonatomic) __weak id <SCTabBarViewDelegate> delegate; // @synthesize delegate=_delegate;
@property(retain, nonatomic) NSArray *items; // @synthesize items=_items;
- (void).cxx_destruct;
- (void)updatePercentDarkMode:(double)arg1;
- (void)flashBackgroundMaskVisibility;
- (struct CGPoint)centerForItemAtIndex:(long long)arg1;
- (void)updateAppStartupCompleteLayout;
- (_Bool)gestureRecognizer:(id)arg1 shouldBeRequiredToFailByGestureRecognizer:(id)arg2;
- (void)animateItemView:(id)arg1 toScale:(double)arg2 completion:(CDUnknownBlockType)arg3;
- (void)cancelGrowAnimationForItemView:(id)arg1;
- (void)shrinkItemView:(id)arg1;
- (void)growItemView:(id)arg1;
- (void)itemTouchUp:(id)arg1;
- (void)itemTapped:(id)arg1;
- (void)itemLongPressed:(id)arg1;
- (void)updateLayout:(_Bool)arg1;
- (_Bool)pointInside:(struct CGPoint)arg1 withEvent:(id)arg2;
- (id)hitTest:(struct CGPoint)arg1 withEvent:(id)arg2;
- (void)layoutSubviews;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

