//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class SCTabBarView;

@protocol SCTabBarViewDataSource <NSObject>
- (double)tabBarView:(SCTabBarView *)arg1 visibilityForItemType:(long long)arg2;
- (struct _NSRange)visibleRangeForTabBarView:(SCTabBarView *)arg1;
@end

