//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSDate, NSTimer;

@interface SCTalkPromptRequestLogger : NSObject
{
    id <SCTalkLoggerDelegate> _delegate;
    unsigned long long _mediaType;
    unsigned long long _promptType;
    NSTimer *_callAttemptTimeout;
    NSDate *_startTime;
    _Bool _asyncCall;
}

- (void).cxx_destruct;
- (void)endOutgoingCallAttempt;
- (void)endIncomingCallAttemptWithPromptResponse:(unsigned long long)arg1;
- (void)_callAttemptReachedTimeout;
- (void)startCallAttempt:(unsigned long long)arg1 mediaType:(unsigned long long)arg2 asynchronousCall:(_Bool)arg3;
- (id)initWithDelegate:(id)arg1;

@end

