//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSCoding.h"
#import "SCMediaOwnerProtocol.h"

@class NSArray, NSString, NSURL, SCRequest, SCTiles, UIColor;

@interface SCTile : NSObject <SCMediaOwnerProtocol, NSCoding>
{
    SCRequest *_logoIconRequest;
    _Bool _displayHasChanged;
    SCTiles *_tiles;
    id <SCTileDataSource> _dataSource;
    NSString *_tileId;
    unsigned long long _type;
    NSString *_discoverChannelName;
    NSString *_sharedStoryId;
    unsigned long long _logoType;
    NSString *_logoText;
    NSURL *_logoURL;
    NSArray *_covers;
    UIColor *_color;
    NSString *_sponsoredString;
    unsigned long long _logoIconMediaState;
}

+ (unsigned long long)typeWithTypeString:(id)arg1;
+ (unsigned long long)logoTypeWithLogoTypeString:(id)arg1;
@property(nonatomic) unsigned long long logoIconMediaState; // @synthesize logoIconMediaState=_logoIconMediaState;
@property(nonatomic) _Bool displayHasChanged; // @synthesize displayHasChanged=_displayHasChanged;
@property(readonly, nonatomic) NSString *sponsoredString; // @synthesize sponsoredString=_sponsoredString;
@property(readonly, nonatomic) UIColor *color; // @synthesize color=_color;
@property(readonly, copy, nonatomic) NSArray *covers; // @synthesize covers=_covers;
@property(copy, nonatomic) NSURL *logoURL; // @synthesize logoURL=_logoURL;
@property(readonly, copy, nonatomic) NSString *logoText; // @synthesize logoText=_logoText;
@property(readonly, nonatomic) unsigned long long logoType; // @synthesize logoType=_logoType;
@property(readonly, copy, nonatomic) NSString *sharedStoryId; // @synthesize sharedStoryId=_sharedStoryId;
@property(readonly, copy, nonatomic) NSString *discoverChannelName; // @synthesize discoverChannelName=_discoverChannelName;
@property(readonly, nonatomic) unsigned long long type; // @synthesize type=_type;
@property(readonly, copy, nonatomic) NSString *tileId; // @synthesize tileId=_tileId;
@property(nonatomic) __weak id <SCTileDataSource> dataSource; // @synthesize dataSource=_dataSource;
@property(nonatomic) __weak SCTiles *tiles; // @synthesize tiles=_tiles;
- (void).cxx_destruct;
- (_Bool)displaysEqual:(id)arg1;
- (_Bool)isFullyViewed;
- (id)cacheKeyForTileLogoImage;
- (void)didDecodeObject;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)cacheMediaIds;
- (_Bool)isLoading;
- (unsigned long long)coverLoadState;
- (void)logoIconWithCompletion:(CDUnknownBlockType)arg1;
- (void)fetchLogoImageMediaImmediately:(_Bool)arg1;
- (void)fetchMediaImmediately:(_Bool)arg1;
- (id)_sponsoredStringFromTileDict:(id)arg1;
- (void)updateWithTileId:(id)arg1 type:(unsigned long long)arg2 logoType:(unsigned long long)arg3 logoURL:(id)arg4 color:(id)arg5 JSONDict:(id)arg6 dataSource:(id)arg7;
- (id)initWithTile:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

