//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSMutableDictionary, SCTilesLayoutPartitioner;

@interface SCTilesDynamicLayoutCalculator : NSObject
{
    SCTilesLayoutPartitioner *_partitioner;
    double _maxY;
    _Bool _hasVerticalPadding;
    NSMutableDictionary *_layoutInformation;
}

@property(readonly, copy, nonatomic) NSMutableDictionary *layoutInformation; // @synthesize layoutInformation=_layoutInformation;
- (void).cxx_destruct;
- (id)_frameValuesWithTilesCount:(long long)arg1 layoutMode:(long long)arg2 imageModeArray:(id)arg3;
- (id)_imageModeArrayWithTilesCount:(long long)arg1 layoutMode:(long long)arg2;
- (struct CGSize)_sizeWithImageMode:(long long)arg1;
- (id)_frameValues:(id)arg1 withYOffset:(double)arg2;
- (double)sectionHeight;
- (void)calculateLayoutWithTiles:(id)arg1;
- (id)initWithHasVerticalPadding:(_Bool)arg1;

@end

