//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class FriendStories, NSString, SCDiscoverChannel, SCDiscoverEdition, SCTileView, SCTilesCollectionViewController;

@protocol SCTilesCollectionViewControllerDelegate <NSObject>
- (void)didReloadDynamicLayoutWithTilesCollectionVC:(SCTilesCollectionViewController *)arg1;
- (void)tilesCollectionVC:(SCTilesCollectionViewController *)arg1 didLongPressTileWithTileId:(NSString *)arg2 discoverChannel:(SCDiscoverChannel *)arg3;
- (void)tilesCollectionVC:(SCTilesCollectionViewController *)arg1 didLongPressTileWithTileId:(NSString *)arg2 friendStories:(FriendStories *)arg3;
- (void)tilesCollectionVC:(SCTilesCollectionViewController *)arg1 didTapTileView:(SCTileView *)arg2 toViewDiscoverEdition:(SCDiscoverEdition *)arg3 tileIndex:(unsigned long long)arg4;
- (void)tilesCollectionVC:(SCTilesCollectionViewController *)arg1 didTapTileView:(SCTileView *)arg2 toViewFriendStories:(FriendStories *)arg3;
@end

