//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SCTextMediaCardView.h"

#import "SCBrowserViewControllerDelegate.h"
#import "SCURLMediaCardViewModelDelegate.h"

@class NSString, NSURL, UILabel, UILongPressGestureRecognizer, UITapGestureRecognizer, UIViewController<SKStoreProductViewControllerDelegate><SCChatCellMessageStateUpdateDelegate><SCChatCellURLLinkGestureDelegate>;

@interface SCURLMediaCardView : SCTextMediaCardView <SCURLMediaCardViewModelDelegate, SCBrowserViewControllerDelegate>
{
    UITapGestureRecognizer *_tapGestureRecognizer;
    UILongPressGestureRecognizer *_longPressGestureRecognizer;
    NSURL *_url;
    UILabel *_subtitleLabel;
    UIViewController<SKStoreProductViewControllerDelegate><SCChatCellMessageStateUpdateDelegate><SCChatCellURLLinkGestureDelegate> *_parentVC;
}

@property(retain, nonatomic) NSURL *url; // @synthesize url=_url;
- (void).cxx_destruct;
- (void)browserViewIsClosing;
- (id)_copyActionForUrl:(id)arg1;
- (id)_saveActionForMessage:(id)arg1;
- (void)_openURL:(id)arg1 cachedWebViewController:(id)arg2;
- (void)onLongPress:(id)arg1;
- (void)onTap:(id)arg1;
- (void)showThumbnailImage:(id)arg1 isGrayScale:(_Bool)arg2 isDefaultThumbnail:(_Bool)arg3;
- (void)dealloc;
- (void)setTitle:(id)arg1 subtitle:(id)arg2;
- (void)initSubTitleView;
- (id)urlMediaCardViewModel;
- (id)initWithViewModel:(id)arg1 parentVC:(id)arg2 backgroundColor:(id)arg3;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

