//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "NSCoding.h"
#import "NSCopying.h"

@interface SCUserClientProperties : NSObject <NSCoding, NSCopying>
{
    _Bool _seenSendToQuickAddAlert;
    _Bool _seenSendToSMSSnapAlert;
}

- (id)_getPropertyString:(unsigned long long)arg1;
- (void)updateClientPropertiesWithDict:(id)arg1;
- (_Bool)getUserClientProperty:(unsigned long long)arg1;
- (void)setUserClientProperty:(unsigned long long)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)initWithCoder:(id)arg1;
- (void)encodeWithCoder:(id)arg1;

@end

