//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class ALVideoViewY, NSString, UILabel;

@interface SCVideoChatRemoteUser : NSObject
{
    UILabel *_uplinkStatsLabel;
    UILabel *_downlinkStatsLabel;
    UILabel *_mediaIssueLabel;
    _Bool _userConnected;
    _Bool _videoPublished;
    _Bool _audioPublished;
    NSString *_userId;
    ALVideoViewY *_videoView;
    NSString *_videoSinkId;
    struct CGSize _remoteResolution;
}

@property(nonatomic) struct CGSize remoteResolution; // @synthesize remoteResolution=_remoteResolution;
@property(retain, nonatomic) NSString *videoSinkId; // @synthesize videoSinkId=_videoSinkId;
@property(retain, nonatomic) ALVideoViewY *videoView; // @synthesize videoView=_videoView;
@property(nonatomic) _Bool audioPublished; // @synthesize audioPublished=_audioPublished;
@property(nonatomic) _Bool videoPublished; // @synthesize videoPublished=_videoPublished;
@property(nonatomic) _Bool userConnected; // @synthesize userConnected=_userConnected;
@property(retain, nonatomic) NSString *userId; // @synthesize userId=_userId;
- (void).cxx_destruct;
- (void)stopVideoViewWithCompletion:(CDUnknownBlockType)arg1;
- (void)startVideoViewWithCompletion:(CDUnknownBlockType)arg1;
- (void)updateWithUserEvent:(id)arg1;
- (id)_issueStringForCode:(id)arg1;
- (void)updateMediaIssueOnVideoView:(id)arg1;
- (void)updateDownlinkStatsOnVideoView:(id)arg1;
- (void)updateUplinkStatsOnVideoView:(id)arg1;
- (void)_prepareMediaIssueLabel;
- (void)_prepareDownlinkLabel;
- (void)_prepareUplinkLabel;
- (id)initWithUserEvent:(id)arg1;

@end

