//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSObject<OS_dispatch_queue>;

@interface SCVideoTrackerNotifier : NSObject
{
    id <SCVideoTrackerListener> _listener;
    NSObject<OS_dispatch_queue> *_notificationQueue;
}

@property(readonly, nonatomic) NSObject<OS_dispatch_queue> *notificationQueue; // @synthesize notificationQueue=_notificationQueue;
@property(readonly, nonatomic) __weak id <SCVideoTrackerListener> listener; // @synthesize listener=_listener;
- (void).cxx_destruct;
- (id)initWithListener:(id)arg1 notificationQueue:(id)arg2;

@end

