//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SCSwipeFilterView.h"

#import "SCImageProcessVideoPlaybackSessionListener.h"
#import "SCVideoMediaFilterScrollViewDelegate.h"

@class AVAsset, AVPlayer, CAEAGLLayer, NSArray, NSData, NSString, SCImageProcessVideoPlaybackSession, SCImageProcessVideoPlaybackSessionListenerAnnouncer, SCMediaFilterView, SCVideoTracker;

@interface SCVideoSwipeFilterView : SCSwipeFilterView <SCImageProcessVideoPlaybackSessionListener, SCVideoMediaFilterScrollViewDelegate>
{
    _Bool _rewindingToBegining;
    CDUnknownBlockType _rewindingToBeginningCompletion;
    SCImageProcessVideoPlaybackSessionListenerAnnouncer *_videoPlaybackSessionAnnouncer;
    _Bool _didProcessFirstFrame;
    NSString *_snapSource;
    NSData *_reversedAudioData;
    SCVideoTracker *_videoTracker;
    AVAsset *_videoAsset;
    AVPlayer *_reverseAudioPlayer;
    SCImageProcessVideoPlaybackSession *_videoPlaybackSession;
    CAEAGLLayer *_glLayer;
    NSArray *_commands;
    unsigned long long _videoPlaybackQuality;
    SCMediaFilterView *_videoMediaView;
    CDStruct_1b6d18a9 _lastFrameTime;
}

@property(retain, nonatomic) SCMediaFilterView *videoMediaView; // @synthesize videoMediaView=_videoMediaView;
@property(nonatomic) unsigned long long videoPlaybackQuality; // @synthesize videoPlaybackQuality=_videoPlaybackQuality;
@property(copy, nonatomic) NSArray *commands; // @synthesize commands=_commands;
@property(retain, nonatomic) CAEAGLLayer *glLayer; // @synthesize glLayer=_glLayer;
@property(retain, nonatomic) SCImageProcessVideoPlaybackSession *videoPlaybackSession; // @synthesize videoPlaybackSession=_videoPlaybackSession;
@property(retain, nonatomic) AVPlayer *reverseAudioPlayer; // @synthesize reverseAudioPlayer=_reverseAudioPlayer;
@property(nonatomic) _Bool didProcessFirstFrame; // @synthesize didProcessFirstFrame=_didProcessFirstFrame;
@property(retain, nonatomic) AVAsset *videoAsset; // @synthesize videoAsset=_videoAsset;
@property(readonly, nonatomic) CDStruct_1b6d18a9 lastFrameTime; // @synthesize lastFrameTime=_lastFrameTime;
@property(readonly, nonatomic) SCVideoTracker *videoTracker; // @synthesize videoTracker=_videoTracker;
@property(retain, nonatomic) NSData *reversedAudioData; // @synthesize reversedAudioData=_reversedAudioData;
@property(nonatomic) NSString *snapSource; // @synthesize snapSource=_snapSource;
- (void).cxx_destruct;
- (_Bool)isDoubleSwipingWithReverseFirstSelected;
- (_Bool)isDoubleSwipingWithSpeedFirstSelected;
- (void)controlViewDidEndDecelerating:(id)arg1;
- (void)controlViewWillBeginDragging:(id)arg1;
- (void)filterScrollView:(id)arg1 didChangeOrientation:(long long)arg2;
- (void)filterScrollView:(id)arg1 didUpdateOffset:(double)arg2;
- (void)filterScrollViewDidReload:(id)arg1;
- (void)videoPlaybackSessionWillLoopVideo:(id)arg1;
- (void)videoPlaybackSession:(id)arg1 didRenderFrameAtTime:(CDStruct_1b6d18a9)arg2;
- (void)videoPlaybackSession:(id)arg1 willRenderFrame:(struct __CVBuffer *)arg2 atTime:(CDStruct_1b6d18a9)arg3;
- (void)_resetOverlayLookAndPlaybackSessionSpeed;
- (id)viewInFilterScrollView:(id)arg1 atIndex:(long long)arg2 shouldAddToAlternativeSuperview:(_Bool *)arg3;
- (id)_currentSpeedMotionFilterSelected;
- (id)_currentReverseMotionFilterSelected;
- (_Bool)isReverseMotionFilterSelected;
- (double)currentVideoPlaybackRate;
- (void)setVolume:(double)arg1;
- (void)addSubviewToBackButAboveVideo:(id)arg1;
- (void)addVideoPlaybackSessionListener:(id)arg1;
- (void)addVideoOverlayView:(id)arg1;
- (double)duration;
- (void)_resetCommands;
- (void)reloadData;
- (void)rewindToBeginingAndResume:(CDUnknownBlockType)arg1;
- (void)pauseVideo;
- (void)stopVideo;
- (void)showVideo;
- (id)mediaFilterScrollView;
- (void)dealloc;
- (id)initWithFrame:(struct CGRect)arg1 videoPlaybackQuality:(unsigned long long)arg2;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(nonatomic) __weak id <SCVideoSwipeFilterViewDelegate> delegate; // @dynamic delegate;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

