//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString, UIView;

@protocol SCVideoChatProviderV2Delegate <NSObject>
- (void)sessionReconnected;
- (void)connectionLost;
- (void)connectionFailed;
- (void)connectionSucceeded;
- (void)proximitySensorInactive;
- (void)proximitySensorActive;
- (void)receiveIncomingCallPromptResponse:(unsigned long long)arg1;
- (void)hideIncomingCallPromptWithCompletion:(void (^)(void))arg1;
- (void)showIncomingCallPromptAnimated:(_Bool)arg1 completion:(void (^)(void))arg2;
- (void)localPeerTakingWithStrength:(double)arg1;
- (void)remotePeerTalkingWithStrength:(double)arg1;
- (void)remoteStreamUnpublished:(NSString *)arg1;
- (void)remoteStreamStartedWithVideoView:(UIView *)arg1;
- (void)remoteStreamPublished:(NSString *)arg1;
- (void)remotePeerDisconnected;
- (void)remotePeerConnected;
@end

