//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "AVCaptureVideoDataOutputSampleBufferDelegate.h"

@class ALService, ALVideoFrame, AVCaptureVideoDataOutput, NSDictionary, NSMutableDictionary, NSMutableSet, NSObject<OS_dispatch_queue>, NSString, SCHereAuth, UIView;

@interface SCVideoChatProviderV2 : NSObject <AVCaptureVideoDataOutputSampleBufferDelegate>
{
    _Bool _togglingCamera;
    _Bool _cameraChangesReady;
    _Bool _h264Enabled;
    struct SCALVideoResolution _videoResolution;
    AVCaptureVideoDataOutput *_captureDataOutput;
    id <SCVideoChatCameraProvider> _cameraProvider;
    id <SCVideoChatAudioSessionManager> _audioSessionManager;
    NSString *_cameraToken;
    NSString *_adlVersion;
    _Bool _frontCamInUse;
    _Bool _monitorSpeechActivity;
    _Bool _cameraTogglingEnabled;
    _Bool _serviceInitialising;
    _Bool _serviceInitRequested;
    _Bool _isRemoteAudioMuted;
    _Bool _isHavingConnectionIssues;
    SCHereAuth *_hereAuth;
    NSDictionary *_chatGatewayAuth;
    UIView *_captureVideoPreviewView;
    id <SCVideoChatProviderV2Delegate> _delegate;
    NSString *_scopeId;
    NSString *_currentConnectionType;
    ALService *_alService;
    ALVideoFrame *_alVideoFrame;
    NSMutableDictionary *_remoteUsersCollection;
    NSObject<OS_dispatch_queue> *_videoDataOutputQueue;
    NSMutableSet *_messagesPending;
    unsigned long long _connectivityState;
    unsigned long long _streamingVideoState;
    unsigned long long _streamingAudioState;
    NSMutableSet *_pendingConnections;
    NSMutableDictionary *_mediaIssues;
    unsigned long long _connectAttempts;
    struct CGRect _previousRemoteRendererFrame;
}

@property(nonatomic) unsigned long long connectAttempts; // @synthesize connectAttempts=_connectAttempts;
@property(nonatomic) _Bool isHavingConnectionIssues; // @synthesize isHavingConnectionIssues=_isHavingConnectionIssues;
@property(retain, nonatomic) NSMutableDictionary *mediaIssues; // @synthesize mediaIssues=_mediaIssues;
@property(retain, nonatomic) NSMutableSet *pendingConnections; // @synthesize pendingConnections=_pendingConnections;
@property(nonatomic) _Bool isRemoteAudioMuted; // @synthesize isRemoteAudioMuted=_isRemoteAudioMuted;
@property(nonatomic) _Bool serviceInitRequested; // @synthesize serviceInitRequested=_serviceInitRequested;
@property(nonatomic) _Bool serviceInitialising; // @synthesize serviceInitialising=_serviceInitialising;
@property(nonatomic) unsigned long long streamingAudioState; // @synthesize streamingAudioState=_streamingAudioState;
@property(nonatomic) unsigned long long streamingVideoState; // @synthesize streamingVideoState=_streamingVideoState;
@property(nonatomic) unsigned long long connectivityState; // @synthesize connectivityState=_connectivityState;
@property(retain, nonatomic) NSMutableSet *messagesPending; // @synthesize messagesPending=_messagesPending;
@property(nonatomic) _Bool cameraTogglingEnabled; // @synthesize cameraTogglingEnabled=_cameraTogglingEnabled;
@property(retain, nonatomic) NSObject<OS_dispatch_queue> *videoDataOutputQueue; // @synthesize videoDataOutputQueue=_videoDataOutputQueue;
@property(nonatomic) struct CGRect previousRemoteRendererFrame; // @synthesize previousRemoteRendererFrame=_previousRemoteRendererFrame;
@property(retain, nonatomic) NSMutableDictionary *remoteUsersCollection; // @synthesize remoteUsersCollection=_remoteUsersCollection;
@property(retain, nonatomic) ALVideoFrame *alVideoFrame; // @synthesize alVideoFrame=_alVideoFrame;
@property(retain, nonatomic) ALService *alService; // @synthesize alService=_alService;
@property(retain, nonatomic) NSString *currentConnectionType; // @synthesize currentConnectionType=_currentConnectionType;
@property(retain, nonatomic) NSString *scopeId; // @synthesize scopeId=_scopeId;
@property(nonatomic) __weak id <SCVideoChatProviderV2Delegate> delegate; // @synthesize delegate=_delegate;
@property(nonatomic) _Bool monitorSpeechActivity; // @synthesize monitorSpeechActivity=_monitorSpeechActivity;
@property(nonatomic) _Bool frontCamInUse; // @synthesize frontCamInUse=_frontCamInUse;
@property(nonatomic) __weak UIView *captureVideoPreviewView; // @synthesize captureVideoPreviewView=_captureVideoPreviewView;
@property(retain, nonatomic) NSDictionary *chatGatewayAuth; // @synthesize chatGatewayAuth=_chatGatewayAuth;
@property(retain, nonatomic) SCHereAuth *hereAuth; // @synthesize hereAuth=_hereAuth;
- (void).cxx_destruct;
- (id)messageType:(id)arg1 withParams:(id)arg2;
- (id)getRemoteUsersPublishingVideo;
- (id)getRemoteUsersPublishingAudio;
- (id)getRemoteUserWithSinkId:(id)arg1;
- (id)getRemoteUserWithUserId:(long long)arg1;
- (void)stopAllRemoteVideoViews;
- (_Bool)isUserAlreadyPresent:(long long)arg1;
- (_Bool)handleError:(id)arg1 forApi:(id)arg2;
- (void)updateVideoResolution:(struct SCALVideoResolution)arg1;
- (id)_appInfo;
- (id)_deviceInfo;
- (void)sendMessage:(id)arg1;
- (void)enableCameraToggle;
- (void)disableCameraToggleForTime:(double)arg1;
- (void)setLiveVideoFrameDurationWithDevice:(id)arg1 input:(id)arg2;
- (void)setLiveVideoConnectionWithDevice:(id)arg1 input:(id)arg2;
- (void)detachCameraChangesWithCompletion:(CDUnknownBlockType)arg1;
- (void)attachCameraChangesWithCompletion:(CDUnknownBlockType)arg1;
- (void)teardownCameraWithCompletion:(CDUnknownBlockType)arg1;
- (void)initCameraWithCompletion:(CDUnknownBlockType)arg1;
- (_Bool)canSwitchCamera;
- (void)reportReachabiltyChange:(_Bool)arg1;
- (_Bool)isRemoteUserConnected;
- (_Bool)usesChatGatewayAuth;
- (void)captureOutput:(id)arg1 didOutputSampleBuffer:(struct opaqueCMSampleBuffer *)arg2 fromConnection:(id)arg3;
- (void)resumeAudioMaybeWithCompletion:(CDUnknownBlockType)arg1;
- (void)suspendAudioWithCompletion:(CDUnknownBlockType)arg1;
- (void)unpublishVideoWithCompletion:(CDUnknownBlockType)arg1;
- (void)publishVideoWithCompletion:(CDUnknownBlockType)arg1;
- (void)unpublishAudioWithCompletion:(CDUnknownBlockType)arg1;
- (void)publishAudioWithCompletion:(CDUnknownBlockType)arg1;
- (void)publishAudioMaybeWithCompletion:(CDUnknownBlockType)arg1;
- (void)unmuteRemoteAudio;
- (void)muteRemoteAudio;
- (void)detachChangesAndStopCameraWithCompletion:(CDUnknownBlockType)arg1;
- (void)attachChangesAndStartCameraWithCompletion:(CDUnknownBlockType)arg1;
- (void)_setAudioDeviceEnabled:(_Bool)arg1 completion:(CDUnknownBlockType)arg2;
- (void)teardownAudioSessionIfNeededWithCompletion:(CDUnknownBlockType)arg1;
- (void)initAudioSessionIfNeededWithCompletion:(CDUnknownBlockType)arg1;
- (void)proximityChanged;
- (id)sha256HashFor:(id)arg1;
- (id)getScopeIdFromToken:(id)arg1;
- (id)fixBase64:(id)arg1;
- (void)increaseVideoCodecComplexityMaybe;
- (void)startMeasuringStatsMaybe;
- (void)onAddLiveConnected;
- (void)onAddLiveConnectionFailed;
- (void)connect;
- (void)onAddLiveReady;
- (void)initAddLive;
- (void)initAddLiveMaybe;
- (void)initCommons;
- (void)setDelegateV2:(id)arg1;
- (_Bool)didConnectionSucceed;
- (_Bool)didConnectionFail;
- (_Bool)sendingVideo;
- (_Bool)sendingAudio;
- (_Bool)sendingAudioOrVideo;
- (_Bool)receivingVideo;
- (_Bool)receivingAudio;
- (_Bool)receivingAudioOrVideo;
- (void)sendDeviceInfoMessage;
- (void)sendCallPromptUserResponse:(unsigned long long)arg1;
- (void)sendHideCallPromptMessage;
- (id)getHideCallPromptMessageBody;
- (void)sendShowCallPromptMessage;
- (id)getShowCallPromptMessageBody;
- (void)sendPendingMessages;
- (void)showTapAnimationAtPoint:(struct CGPoint)arg1 andView:(id)arg2;
- (void)setAutofocusAndExposurePointOfInterest:(struct CGPoint)arg1;
- (_Bool)shouldToggleCamera:(_Bool)arg1;
- (void)switchCamera:(_Bool)arg1 withCompletion:(CDUnknownBlockType)arg2;
- (void)toggleCameraWithCompletion:(CDUnknownBlockType)arg1;
- (_Bool)hasMultipleCameras;
- (void)endSessionWithTimeout:(double)arg1 andCompletion:(CDUnknownBlockType)arg2;
- (void)startSessionWithHereAuth:(id)arg1;
- (void)startSessionWithChatAuth:(id)arg1 andMac:(id)arg2;
- (id)initWithCameraProvider:(id)arg1 h264Enabled:(_Bool)arg2 audioSessionManager:(id)arg3;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

