//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIViewController.h"

#import "SCContentInviteSnapLinkSenderDelegate.h"
#import "SCHeaderDataSource.h"
#import "SCHeaderDelegate.h"
#import "SCInviteSnapSenderDelegate.h"
#import "SCLocationHeaderViewDelegate.h"
#import "SCMiniProfileControllerDelegate.h"
#import "SCSelectGroupRecipientsDelegate.h"
#import "SCSendConfirmationViewControllerDelegate.h"
#import "SCTimeProfilable.h"
#import "UIAlertViewDelegate.h"
#import "UITextFieldDelegate.h"

@class FBKVOController, Friend, LoadingView, NSArray, NSMutableDictionary, NSString, SCContentInviteSnapLinkSender, SCFindFriendMenuViewController, SCLocationController, SCLocationHeaderView, SCSelectRecipientsView, SCSendConfirmationView, SCSendViewControllerDismissalAnimator, SCUserSession, UIImageView, UIView;

@interface SendViewController : UIViewController <SCSelectGroupRecipientsDelegate, SCSendConfirmationViewControllerDelegate, SCHeaderDataSource, SCHeaderDelegate, SCMiniProfileControllerDelegate, SCTimeProfilable, SCContentInviteSnapLinkSenderDelegate, UITextFieldDelegate, UIAlertViewDelegate, SCLocationHeaderViewDelegate, SCInviteSnapSenderDelegate>
{
    _Bool _leftSwipeToDismissEnabled;
    _Bool _shouldHideBackgroundImages;
    SCUserSession *_userSession;
    SCSendViewControllerDismissalAnimator *_dismissalAnimator;
    FBKVOController *_KVOController;
    SCLocationHeaderView *_locationHeaderView;
    SCLocationController *_locationController;
    _Bool _userSentToSettings;
    _Bool _shouldSyncGallerySelectionWithMyStory;
    SCContentInviteSnapLinkSender *_contentInviteSnapLinkSender;
    LoadingView *_activityIndicator;
    _Bool _gallerySendingLongVideo;
    _Bool _gallerySendingScreenshot;
    _Bool _animationInProgress;
    id <SCSendViewControllerSendingDelegate> _sendingDelegate;
    id <SendSnapNavigationControllerDelegate> _delegate;
    id <SCStartChatDelegate> _startChatDelegate;
    Friend *_replyFriend;
    SCSelectRecipientsView *_selectRecipientsView;
    long long _snapSource;
    NSString *_pageType;
    SCFindFriendMenuViewController *_addFriendsVC;
    SCSendConfirmationView *_sendConfirmationView;
    UIImageView *_stillImageBackgroundView;
    UIImageView *_animatedBackgroundImageLayer;
    UIView *_containerView;
    NSArray *_filteredFriends;
    NSArray *_friendKeys;
    NSArray *_friends;
    double _keyboardHeight;
    NSMutableDictionary *_replyParameters;
    Friend *_selectedFriend;
}

+ (long long)context;
+ (id)profiledSelectorNames;
+ (id)pageViewName;
@property(retain, nonatomic) Friend *selectedFriend; // @synthesize selectedFriend=_selectedFriend;
@property(retain, nonatomic) NSMutableDictionary *replyParameters; // @synthesize replyParameters=_replyParameters;
@property(nonatomic) double keyboardHeight; // @synthesize keyboardHeight=_keyboardHeight;
@property(copy, nonatomic) NSArray *friends; // @synthesize friends=_friends;
@property(copy, nonatomic) NSArray *friendKeys; // @synthesize friendKeys=_friendKeys;
@property(copy, nonatomic) NSArray *filteredFriends; // @synthesize filteredFriends=_filteredFriends;
@property(retain, nonatomic) UIView *containerView; // @synthesize containerView=_containerView;
@property(nonatomic) _Bool animationInProgress; // @synthesize animationInProgress=_animationInProgress;
@property(retain, nonatomic) UIImageView *animatedBackgroundImageLayer; // @synthesize animatedBackgroundImageLayer=_animatedBackgroundImageLayer;
@property(retain, nonatomic) UIImageView *stillImageBackgroundView; // @synthesize stillImageBackgroundView=_stillImageBackgroundView;
@property(retain, nonatomic) SCSendConfirmationView *sendConfirmationView; // @synthesize sendConfirmationView=_sendConfirmationView;
@property(retain, nonatomic) SCFindFriendMenuViewController *addFriendsVC; // @synthesize addFriendsVC=_addFriendsVC;
@property(nonatomic) _Bool gallerySendingScreenshot; // @synthesize gallerySendingScreenshot=_gallerySendingScreenshot;
@property(nonatomic) _Bool gallerySendingLongVideo; // @synthesize gallerySendingLongVideo=_gallerySendingLongVideo;
@property(copy, nonatomic) NSString *pageType; // @synthesize pageType=_pageType;
@property(nonatomic) long long snapSource; // @synthesize snapSource=_snapSource;
@property(retain, nonatomic) SCSelectRecipientsView *selectRecipientsView; // @synthesize selectRecipientsView=_selectRecipientsView;
@property(retain, nonatomic) Friend *replyFriend; // @synthesize replyFriend=_replyFriend;
@property(nonatomic) __weak id <SCStartChatDelegate> startChatDelegate; // @synthesize startChatDelegate=_startChatDelegate;
@property(nonatomic) __weak id <SendSnapNavigationControllerDelegate> delegate; // @synthesize delegate=_delegate;
@property(nonatomic) __weak id <SCSendViewControllerSendingDelegate> sendingDelegate; // @synthesize sendingDelegate=_sendingDelegate;
- (void).cxx_destruct;
- (void)didFinishAllActionForContentInviteSnap:(id)arg1 sender:(id)arg2;
- (id)activityIndicator;
- (void)_hideActivityIndicator;
- (void)_showActivityIndicator;
- (void)sendInviteSnap:(id)arg1 success:(_Bool)arg2 inviteSnapsForRecipients:(id)arg3;
- (id)userSession;
- (void)didPressChatButtonForFriend:(id)arg1 controller:(id)arg2;
- (_Bool)hasSelectedRecipients;
- (void)_hideLocationHeader;
- (void)locationHeaderDismissed;
- (void)locationHeaderTapped;
- (_Bool)scrollViewShouldScrollToTop:(id)arg1;
- (void)selectRecipientsTableViewDidScroll:(id)arg1;
- (void)doBackgroundAnimation;
- (double)backgroundImageVerticalOffset;
- (void)updateGroupLabelAnimated:(_Bool)arg1;
- (void)sendGroupPressed;
- (void)addMultiFriendsFromQuickAdd;
- (void)didUpdateSearchResults;
- (void)didUpdateRecipients;
- (void)rightButtonPressed;
- (void)leftButtonPressed;
- (void)dismiss;
- (id)imageForRightButtonInState:(unsigned long long)arg1;
- (id)imageForLeftButtonInState:(unsigned long long)arg1;
- (id)textColorForHeader:(id)arg1;
- (id)titleForHeader:(id)arg1;
- (id)backgroundColorForHeader;
- (void)didPressRecipient:(id)arg1;
- (void)didPressSend;
- (void)didBecomeActive:(id)arg1;
- (void)keyboardWillChange:(id)arg1 willShow:(_Bool)arg2;
- (void)keyboardWillHide:(id)arg1;
- (void)keyboardWillShow:(id)arg1;
- (unsigned long long)supportedInterfaceOrientations;
- (_Bool)shouldPopToRootViewController;
- (void)viewDidDisappear:(_Bool)arg1;
- (void)viewWillDisappear:(_Bool)arg1;
- (void)viewDidAppear:(_Bool)arg1;
- (void)viewWillAppear:(_Bool)arg1;
- (void)setReplyFriend:(id)arg1 parameters:(id)arg2;
- (void)viewDidLoad;
- (void)initHeader;
- (void)initBackgroundImages;
- (void)updateSendConfirmationLayoutConstraints;
- (void)dealloc;
- (void)loadView;
- (id)getPageViewParams;
- (id)getPageViewName;
- (id)initWithUserSession:(id)arg1;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly, copy) NSString *description;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

