//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSDictionary, NSURL;

@interface SnapAdsNetworkRequest : NSObject
{
    NSURL *_url;
    id _uploadData;
    NSDictionary *_additionalHTTPHeaders;
    long long _method;
}

@property(readonly, nonatomic) long long method; // @synthesize method=_method;
@property(readonly, nonatomic) NSDictionary *additionalHTTPHeaders; // @synthesize additionalHTTPHeaders=_additionalHTTPHeaders;
@property(readonly, nonatomic) id uploadData; // @synthesize uploadData=_uploadData;
@property(readonly, nonatomic) NSURL *url; // @synthesize url=_url;
- (void).cxx_destruct;
- (id)initWithUrl:(id)arg1 uploadData:(id)arg2 additionalHTTPHeaders:(id)arg3 method:(long long)arg4;

@end

