//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSNumber, NSString;

@interface SOJUFriendmojiBuilder : NSObject
{
    NSString *_categoryName;
    NSNumber *_expirationTime;
}

+ (id)withJUFriendmoji:(id)arg1;
- (void).cxx_destruct;
- (id)setExpirationTime:(id)arg1;
- (id)setCategoryName:(id)arg1;
- (id)build;

@end

