//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString, SOJUAdDeviceScreenDimension;

@interface SOJUAdClientInitRequestBuilder : NSObject
{
    NSString *_deviceType;
    NSString *_osVersion;
    NSString *_appVersion;
    NSString *_idfa;
    SOJUAdDeviceScreenDimension *_screenDimensions;
}

+ (id)withJUAdClientInitRequest:(id)arg1;
- (void).cxx_destruct;
- (id)setScreenDimensions:(id)arg1;
- (id)setIdfa:(id)arg1;
- (id)setAppVersion:(id)arg1;
- (id)setOsVersion:(id)arg1;
- (id)setDeviceType:(id)arg1;
- (id)build;

@end

