//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSNumber;

@interface SOJUAdLocalWebpageImpressionTrackBuilder : NSObject
{
    NSNumber *_topsnapTimeViewedSeconds;
    NSNumber *_topsnapMediaDurationSeconds;
    NSNumber *_longformTimeViewedSeconds;
    NSNumber *_swiped;
}

+ (id)withJUAdLocalWebpageImpressionTrack:(id)arg1;
- (void).cxx_destruct;
- (id)setSwiped:(id)arg1;
- (id)setLongformTimeViewedSeconds:(id)arg1;
- (id)setTopsnapMediaDurationSeconds:(id)arg1;
- (id)setTopsnapTimeViewedSeconds:(id)arg1;
- (id)build;

@end

