//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSDictionary, NSString;

@interface SOJURichStoryRichStoryAppInstallAndroidBuilder : NSObject
{
    NSString *_packageId;
    NSDictionary *_storeParams;
}

+ (id)withJURichStoryRichStoryAppInstallAndroid:(id)arg1;
- (void).cxx_destruct;
- (id)setStoreParams:(id)arg1;
- (id)setPackageId:(id)arg1;
- (id)build;

@end

