//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SOJUStickerPackMetadataBuilder.h"

@interface SOJUStickerPackMetadataBuilder (Setter)
- (id)setHasBannerValue:(_Bool)arg1;
- (id)setActiveValue:(_Bool)arg1;
- (id)setVersionValue:(int)arg1;
- (id)setPackTypeEnum:(long long)arg1;
@end

