//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSNumber, NSString;

@interface SOJUSecurityKeyServiceAssertionBuilder : NSObject
{
    NSString *_purpose;
    NSString *_iss;
    NSString *_aud;
    NSNumber *_exp;
    NSNumber *_nbf;
    NSString *_name;
    NSString *_sub;
    NSString *_userId;
    NSString *_nonce;
}

+ (id)withJUSecurityKeyServiceAssertion:(id)arg1;
- (void).cxx_destruct;
- (id)setNonce:(id)arg1;
- (id)setUserId:(id)arg1;
- (id)setSub:(id)arg1;
- (id)setName:(id)arg1;
- (id)setNbf:(id)arg1;
- (id)setExp:(id)arg1;
- (id)setAud:(id)arg1;
- (id)setIss:(id)arg1;
- (id)setPurpose:(id)arg1;
- (id)build;

@end

