//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSCoding.h"
#import "NSCopying.h"
#import "NSObject.h"

@class NSString, SOJUAdAppInstallImpressionTrack, SOJUAdLocalWebpageImpressionTrack, SOJUAdLongformVideoImpressionTrack, SOJUAdRemoteWebpageImpressionTrack, SOJUAdThreeVImpressionTrack;

@protocol SOJUAdImpressionData <NSObject, NSCoding, NSCopying>
@property(readonly, copy, nonatomic) SOJUAdLocalWebpageImpressionTrack *localWebpage;
@property(readonly, copy, nonatomic) SOJUAdRemoteWebpageImpressionTrack *remoteWebpage;
@property(readonly, copy, nonatomic) SOJUAdLongformVideoImpressionTrack *longformVideo;
@property(readonly, copy, nonatomic) SOJUAdAppInstallImpressionTrack *appInstall;
@property(readonly, copy, nonatomic) SOJUAdThreeVImpressionTrack *threeV;
@property(readonly, copy, nonatomic) NSString *adType;
@end

