//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "SOJUDiscoverEditionViewState.h"

@class NSNumber, NSString;

@interface SOJUDiscoverEditionViewState : NSObject <SOJUDiscoverEditionViewState>
{
    NSString *_publisherId;
    NSString *_editionId;
    NSNumber *_timeViewed;
    NSNumber *_numSnapsViewed;
    NSNumber *_numLongformViewed;
    NSString *_exitEvent;
    NSNumber *_snapIndexCount;
    NSString *_source;
    NSNumber *_viewLocationPos;
    NSNumber *_tapTimestamp;
    NSNumber *_isCompleted;
}

@property(readonly, copy, nonatomic) NSNumber *isCompleted; // @synthesize isCompleted=_isCompleted;
@property(readonly, copy, nonatomic) NSNumber *tapTimestamp; // @synthesize tapTimestamp=_tapTimestamp;
@property(readonly, copy, nonatomic) NSNumber *viewLocationPos; // @synthesize viewLocationPos=_viewLocationPos;
@property(readonly, copy, nonatomic) NSString *source; // @synthesize source=_source;
@property(readonly, copy, nonatomic) NSNumber *snapIndexCount; // @synthesize snapIndexCount=_snapIndexCount;
@property(readonly, copy, nonatomic) NSString *exitEvent; // @synthesize exitEvent=_exitEvent;
@property(readonly, copy, nonatomic) NSNumber *numLongformViewed; // @synthesize numLongformViewed=_numLongformViewed;
@property(readonly, copy, nonatomic) NSNumber *numSnapsViewed; // @synthesize numSnapsViewed=_numSnapsViewed;
@property(readonly, copy, nonatomic) NSNumber *timeViewed; // @synthesize timeViewed=_timeViewed;
@property(readonly, copy, nonatomic) NSString *editionId; // @synthesize editionId=_editionId;
@property(readonly, copy, nonatomic) NSString *publisherId; // @synthesize publisherId=_publisherId;
- (void).cxx_destruct;
@property(readonly, copy) NSString *description;
- (_Bool)isEqual:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)initWithPublisherId:(id)arg1 editionId:(id)arg2 timeViewed:(id)arg3 numSnapsViewed:(id)arg4 numLongformViewed:(id)arg5 exitEvent:(id)arg6 snapIndexCount:(id)arg7 source:(id)arg8 viewLocationPos:(id)arg9 tapTimestamp:(id)arg10 isCompleted:(id)arg11;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

