//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SOJUBroadcastPrecachingPrecacheCountsBuilder.h"

@interface SOJUBroadcastPrecachingPrecacheCountsBuilder (Setter)
- (id)setTravelModeCountValue:(int)arg1;
- (id)setLowPowerModeCountValue:(int)arg1;
- (id)setWwanCountValue:(int)arg1;
- (id)setWifiCountValue:(int)arg1;
@end

