//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray, NSDictionary;

@interface SOJUFlushStateRequestBuilder : NSObject
{
    NSDictionary *_snapStates;
    NSArray *_storyStates;
}

+ (id)withJUFlushStateRequest:(id)arg1;
- (void).cxx_destruct;
- (id)setStoryStates:(id)arg1;
- (id)setSnapStates:(id)arg1;
- (id)build;

@end

