//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSCoding.h"
#import "NSCopying.h"
#import "NSObject.h"

@class NSNumber, NSString;

@protocol SOJUPingSummaryStats <NSObject, NSCoding, NSCopying>
@property(readonly, copy, nonatomic) NSNumber *avgLatency;
@property(readonly, copy, nonatomic) NSNumber *medianLatency;
@property(readonly, copy, nonatomic) NSNumber *maxLatency;
@property(readonly, copy, nonatomic) NSNumber *minLatency;
@property(readonly, copy, nonatomic) NSNumber *totalCount;
@property(readonly, copy, nonatomic) NSNumber *emptyCount;
@property(readonly, copy, nonatomic) NSNumber *errorCount;
@property(readonly, copy, nonatomic) NSNumber *pingInterval;
@property(readonly, copy, nonatomic) NSString *pingUrl;
@end

