//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "SOJUBroadcastPrecachingPrecacheCounts.h"

@class NSNumber, NSString;

@interface SOJUBroadcastPrecachingPrecacheCounts : NSObject <SOJUBroadcastPrecachingPrecacheCounts>
{
    NSNumber *_wifiCount;
    NSNumber *_wwanCount;
    NSNumber *_lowPowerModeCount;
    NSNumber *_travelModeCount;
}

@property(readonly, copy, nonatomic) NSNumber *travelModeCount; // @synthesize travelModeCount=_travelModeCount;
@property(readonly, copy, nonatomic) NSNumber *lowPowerModeCount; // @synthesize lowPowerModeCount=_lowPowerModeCount;
@property(readonly, copy, nonatomic) NSNumber *wwanCount; // @synthesize wwanCount=_wwanCount;
@property(readonly, copy, nonatomic) NSNumber *wifiCount; // @synthesize wifiCount=_wifiCount;
- (void).cxx_destruct;
@property(readonly, copy) NSString *description;
- (_Bool)isEqual:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)initWithWifiCount:(id)arg1 wwanCount:(id)arg2 lowPowerModeCount:(id)arg3 travelModeCount:(id)arg4;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

