//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SOJUDiscoverEditionViewStateBuilder.h"

@interface SOJUDiscoverEditionViewStateBuilder (Setter)
- (id)setIsCompletedValue:(_Bool)arg1;
- (id)setTapTimestampValue:(long long)arg1;
- (id)setViewLocationPosValue:(int)arg1;
- (id)setSourceEnum:(long long)arg1;
- (id)setSnapIndexCountValue:(int)arg1;
- (id)setExitEventEnum:(long long)arg1;
- (id)setNumLongformViewedValue:(int)arg1;
- (id)setNumSnapsViewedValue:(int)arg1;
- (id)setTimeViewedValue:(float)arg1;
@end

