//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray, NSNumber, NSString;

@interface SOJUStickerMetadataBuilder : NSObject
{
    NSString *_stickerId;
    NSString *_stickerType;
    NSString *_mediaPath;
    NSNumber *_priority;
    NSNumber *_active;
    NSNumber *_hasAlpha;
    NSArray *_capabilities;
}

+ (id)withJUStickerMetadata:(id)arg1;
- (void).cxx_destruct;
- (id)setCapabilities:(id)arg1;
- (id)setHasAlpha:(id)arg1;
- (id)setActive:(id)arg1;
- (id)setPriority:(id)arg1;
- (id)setMediaPath:(id)arg1;
- (id)setStickerType:(id)arg1;
- (id)setStickerId:(id)arg1;
- (id)build;

@end

