//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "SOJUSecurityGetAssertionResponse.h"

@class NSString;

@interface SOJUSecurityGetAssertionResponse : NSObject <SOJUSecurityGetAssertionResponse>
{
    NSString *_assertion;
    NSString *_tag1;
    NSString *_tag2;
    NSString *_nonce;
}

@property(readonly, copy, nonatomic) NSString *nonce; // @synthesize nonce=_nonce;
@property(readonly, copy, nonatomic) NSString *tag2; // @synthesize tag2=_tag2;
@property(readonly, copy, nonatomic) NSString *tag1; // @synthesize tag1=_tag1;
@property(readonly, copy, nonatomic) NSString *assertion; // @synthesize assertion=_assertion;
- (void).cxx_destruct;
@property(readonly, copy) NSString *description;
- (_Bool)isEqual:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)initWithAssertion:(id)arg1 tag1:(id)arg2 tag2:(id)arg3 nonce:(id)arg4;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

