//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray, NSNumber, NSString, SOJURichStoryRichStoryAppInstallAndroid, SOJURichStoryRichStoryAppInstallIos;

@interface SOJURichStoryRichStoryItemPropertiesResponseBuilder : NSObject
{
    NSString *_file;
    NSArray *_images;
    NSArray *_articleVideos;
    NSString *_background;
    NSString *_backgroundType;
    NSString *_overlay;
    NSString *_videoId;
    NSString *_mode;
    NSString *_docking;
    NSString *_sponsoredOverlay;
    NSString *_videoFirstFrame;
    NSString *_videoShareFrame;
    NSNumber *_zIndex;
    NSString *_icon;
    NSString *_title;
    SOJURichStoryRichStoryAppInstallIos *_ios;
    SOJURichStoryRichStoryAppInstallAndroid *_android;
    NSString *_url;
}

+ (id)withJURichStoryRichStoryItemPropertiesResponse:(id)arg1;
- (void).cxx_destruct;
- (id)setUrl:(id)arg1;
- (id)setAndroid:(id)arg1;
- (id)setIos:(id)arg1;
- (id)setTitle:(id)arg1;
- (id)setIcon:(id)arg1;
- (id)setZIndex:(id)arg1;
- (id)setVideoShareFrame:(id)arg1;
- (id)setVideoFirstFrame:(id)arg1;
- (id)setSponsoredOverlay:(id)arg1;
- (id)setDocking:(id)arg1;
- (id)setMode:(id)arg1;
- (id)setVideoId:(id)arg1;
- (id)setOverlay:(id)arg1;
- (id)setBackgroundType:(id)arg1;
- (id)setBackground:(id)arg1;
- (id)setArticleVideos:(id)arg1;
- (id)setImages:(id)arg1;
- (id)setFile:(id)arg1;
- (id)build;

@end

