//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "SOJUFeatureSettingsBuilder.h"

@interface SOJUFeatureSettingsBuilder (Setter)
- (id)setESnapMediaValue:(_Bool)arg1;
- (id)setGalleryInvitedValue:(_Bool)arg1;
- (id)setGalleryEnabledValue:(_Bool)arg1;
- (id)setIsBirthdayPartyEnabledValue:(_Bool)arg1;
- (id)setIsLensesTooltipEnabledValue:(_Bool)arg1;
- (id)setIsPrefetchForStoreLensesEnabledValue:(_Bool)arg1;
- (id)setLookseryFaceTrackingv2InitializationEnabledValue:(_Bool)arg1;
- (id)setLookseryFaceTrackingv2EnabledValue:(_Bool)arg1;
- (id)setQrcodeEnabledValue:(_Bool)arg1;
- (id)setBarcodeEnabledValue:(_Bool)arg1;
- (id)setLensStoreAvailableValue:(_Bool)arg1;
- (id)setPayReplaySnapsValue:(_Bool)arg1;
- (id)setTravelModeValue:(_Bool)arg1;
- (id)setReplaySnapsValue:(_Bool)arg1;
- (id)setFrontFacingFlashValue:(_Bool)arg1;
- (id)setVisualFiltersValue:(_Bool)arg1;
- (id)setSmartFiltersValue:(_Bool)arg1;
@end

