//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "SOJUInviteSnapData.h"

@class NSNumber, NSString;

@interface SOJUInviteSnapData : NSObject <SOJUInviteSnapData>
{
    NSString *_idValue;
    NSNumber *_timestamp;
    NSNumber *_pending;
    NSString *_invitedRecipientId;
    NSString *_deepLinkUrl;
}

@property(readonly, copy, nonatomic) NSString *deepLinkUrl; // @synthesize deepLinkUrl=_deepLinkUrl;
@property(readonly, copy, nonatomic) NSString *invitedRecipientId; // @synthesize invitedRecipientId=_invitedRecipientId;
@property(readonly, copy, nonatomic) NSNumber *pending; // @synthesize pending=_pending;
@property(readonly, copy, nonatomic) NSNumber *timestamp; // @synthesize timestamp=_timestamp;
@property(readonly, copy, nonatomic) NSString *idValue; // @synthesize idValue=_idValue;
- (void).cxx_destruct;
@property(readonly, copy) NSString *description;
- (_Bool)isEqual:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)initWithIdValue:(id)arg1 timestamp:(id)arg2 pending:(id)arg3 invitedRecipientId:(id)arg4 deepLinkUrl:(id)arg5;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

