//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface SOJUAdAdBuilder : NSObject
{
    NSString *_orderId;
    NSString *_orderName;
    NSString *_adId;
    NSString *_adName;
    NSString *_lineItemId;
    NSString *_lineItemName;
    NSString *_brandId;
    NSString *_placementId;
    NSString *_iosAppId;
    NSString *_andAppId;
    NSString *_adType;
}

+ (id)withJUAdAd:(id)arg1;
- (void).cxx_destruct;
- (id)setAdType:(id)arg1;
- (id)setAndAppId:(id)arg1;
- (id)setIosAppId:(id)arg1;
- (id)setPlacementId:(id)arg1;
- (id)setBrandId:(id)arg1;
- (id)setLineItemName:(id)arg1;
- (id)setLineItemId:(id)arg1;
- (id)setAdName:(id)arg1;
- (id)setAdId:(id)arg1;
- (id)setOrderName:(id)arg1;
- (id)setOrderId:(id)arg1;
- (id)build;

@end

