//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "SOJUMessagingConversationShareBatchedMediaRequest.h"

@class NSArray, NSString;

@interface SOJUMessagingConversationShareBatchedMediaRequest : NSObject <SOJUMessagingConversationShareBatchedMediaRequest>
{
    NSString *_timestamp;
    NSString *_reqToken;
    NSString *_username;
    NSString *_recipients;
    NSArray *_mediaList;
    NSString *_bodyType;
    NSString *_storyTitle;
    NSString *_seqNums;
}

@property(readonly, copy, nonatomic) NSString *seqNums; // @synthesize seqNums=_seqNums;
@property(readonly, copy, nonatomic) NSString *storyTitle; // @synthesize storyTitle=_storyTitle;
@property(readonly, copy, nonatomic) NSString *bodyType; // @synthesize bodyType=_bodyType;
@property(readonly, copy, nonatomic) NSArray *mediaList; // @synthesize mediaList=_mediaList;
@property(readonly, copy, nonatomic) NSString *recipients; // @synthesize recipients=_recipients;
@property(readonly, copy, nonatomic) NSString *username; // @synthesize username=_username;
@property(readonly, copy, nonatomic) NSString *reqToken; // @synthesize reqToken=_reqToken;
@property(readonly, copy, nonatomic) NSString *timestamp; // @synthesize timestamp=_timestamp;
- (void).cxx_destruct;
@property(readonly, copy) NSString *description;
- (_Bool)isEqual:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)initWithTimestamp:(id)arg1 reqToken:(id)arg2 username:(id)arg3 recipients:(id)arg4 mediaList:(id)arg5 bodyType:(id)arg6 storyTitle:(id)arg7 seqNums:(id)arg8;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

