//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSArray, NSNumber;

@interface SOJUFlushStateResponseSnapResponseBuilder : NSObject
{
    NSArray *_esIds;
    NSNumber *_logged;
    NSNumber *_throttled;
    NSNumber *_success;
}

+ (id)withJUFlushStateResponseSnapResponse:(id)arg1;
- (void).cxx_destruct;
- (id)setSuccess:(id)arg1;
- (id)setThrottled:(id)arg1;
- (id)setLogged:(id)arg1;
- (id)setEsIds:(id)arg1;
- (id)build;

@end

