//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "SOJUOurStoryAuth.h"

@class NSNumber, NSString, SOJUGeofence;

@interface SOJUOurStoryAuth : NSObject <SOJUOurStoryAuth>
{
    NSString *_storyId;
    NSString *_account;
    NSString *_displayName;
    SOJUGeofence *_geofence;
    NSString *_myStoriesDisplayName;
    NSString *_venue;
    NSString *_friendName;
    NSNumber *_localStory;
    NSNumber *_isWhitelisted;
    NSNumber *_timeLeft;
}

@property(readonly, copy, nonatomic) NSNumber *timeLeft; // @synthesize timeLeft=_timeLeft;
@property(readonly, copy, nonatomic) NSNumber *isWhitelisted; // @synthesize isWhitelisted=_isWhitelisted;
@property(readonly, copy, nonatomic) NSNumber *localStory; // @synthesize localStory=_localStory;
@property(readonly, copy, nonatomic) NSString *friendName; // @synthesize friendName=_friendName;
@property(readonly, copy, nonatomic) NSString *venue; // @synthesize venue=_venue;
@property(readonly, copy, nonatomic) NSString *myStoriesDisplayName; // @synthesize myStoriesDisplayName=_myStoriesDisplayName;
@property(readonly, copy, nonatomic) SOJUGeofence *geofence; // @synthesize geofence=_geofence;
@property(readonly, copy, nonatomic) NSString *displayName; // @synthesize displayName=_displayName;
@property(readonly, copy, nonatomic) NSString *account; // @synthesize account=_account;
@property(readonly, copy, nonatomic) NSString *storyId; // @synthesize storyId=_storyId;
- (void).cxx_destruct;
@property(readonly, copy) NSString *description;
- (_Bool)isEqual:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)initWithStoryId:(id)arg1 account:(id)arg2 displayName:(id)arg3 geofence:(id)arg4 myStoriesDisplayName:(id)arg5 venue:(id)arg6 friendName:(id)arg7 localStory:(id)arg8 isWhitelisted:(id)arg9 timeLeft:(id)arg10;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

