//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "SOJUIdentityMatchDeviceResponse.h"

@class NSNumber, NSString;

@interface SOJUIdentityMatchDeviceResponse : NSObject <SOJUIdentityMatchDeviceResponse>
{
    NSNumber *_matched;
    NSString *_deeplinkUrl;
    NSString *_clickUuid;
    NSString *_shareUuid;
    NSString *_userAgent;
    NSString *_referrer;
}

@property(readonly, copy, nonatomic) NSString *referrer; // @synthesize referrer=_referrer;
@property(readonly, copy, nonatomic) NSString *userAgent; // @synthesize userAgent=_userAgent;
@property(readonly, copy, nonatomic) NSString *shareUuid; // @synthesize shareUuid=_shareUuid;
@property(readonly, copy, nonatomic) NSString *clickUuid; // @synthesize clickUuid=_clickUuid;
@property(readonly, copy, nonatomic) NSString *deeplinkUrl; // @synthesize deeplinkUrl=_deeplinkUrl;
@property(readonly, copy, nonatomic) NSNumber *matched; // @synthesize matched=_matched;
- (void).cxx_destruct;
@property(readonly, copy) NSString *description;
- (_Bool)isEqual:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)initWithMatched:(id)arg1 deeplinkUrl:(id)arg2 clickUuid:(id)arg3 shareUuid:(id)arg4 userAgent:(id)arg5 referrer:(id)arg6;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

