//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

#import "SOJUSettingsRequest.h"

@class NSArray, NSString;

@interface SOJUSettingsRequest : NSObject <SOJUSettingsRequest>
{
    NSString *_timestamp;
    NSString *_reqToken;
    NSString *_username;
    NSString *_action;
    NSString *_birthday;
    NSString *_timeZone;
    NSString *_email;
    NSString *_password;
    NSString *_phoneNumber;
    NSString *_code;
    NSString *_deviceid;
    NSString *_dtoken1i;
    NSString *_dsig;
    NSString *_otpSecret;
    NSString *_privacySetting;
    NSString *_searchable;
    NSArray *_storyFriendsToBlock;
    NSString *_notificationSoundSetting;
    NSString *_notificationPrivacy;
    NSString *_ringingSound;
}

@property(readonly, copy, nonatomic) NSString *ringingSound; // @synthesize ringingSound=_ringingSound;
@property(readonly, copy, nonatomic) NSString *notificationPrivacy; // @synthesize notificationPrivacy=_notificationPrivacy;
@property(readonly, copy, nonatomic) NSString *notificationSoundSetting; // @synthesize notificationSoundSetting=_notificationSoundSetting;
@property(readonly, copy, nonatomic) NSArray *storyFriendsToBlock; // @synthesize storyFriendsToBlock=_storyFriendsToBlock;
@property(readonly, copy, nonatomic) NSString *searchable; // @synthesize searchable=_searchable;
@property(readonly, copy, nonatomic) NSString *privacySetting; // @synthesize privacySetting=_privacySetting;
@property(readonly, copy, nonatomic) NSString *otpSecret; // @synthesize otpSecret=_otpSecret;
@property(readonly, copy, nonatomic) NSString *dsig; // @synthesize dsig=_dsig;
@property(readonly, copy, nonatomic) NSString *dtoken1i; // @synthesize dtoken1i=_dtoken1i;
@property(readonly, copy, nonatomic) NSString *deviceid; // @synthesize deviceid=_deviceid;
@property(readonly, copy, nonatomic) NSString *code; // @synthesize code=_code;
@property(readonly, copy, nonatomic) NSString *phoneNumber; // @synthesize phoneNumber=_phoneNumber;
@property(readonly, copy, nonatomic) NSString *password; // @synthesize password=_password;
@property(readonly, copy, nonatomic) NSString *email; // @synthesize email=_email;
@property(readonly, copy, nonatomic) NSString *timeZone; // @synthesize timeZone=_timeZone;
@property(readonly, copy, nonatomic) NSString *birthday; // @synthesize birthday=_birthday;
@property(readonly, copy, nonatomic) NSString *action; // @synthesize action=_action;
@property(readonly, copy, nonatomic) NSString *username; // @synthesize username=_username;
@property(readonly, copy, nonatomic) NSString *reqToken; // @synthesize reqToken=_reqToken;
@property(readonly, copy, nonatomic) NSString *timestamp; // @synthesize timestamp=_timestamp;
- (void).cxx_destruct;
@property(readonly, copy) NSString *description;
- (_Bool)isEqual:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)initWithTimestamp:(id)arg1 reqToken:(id)arg2 username:(id)arg3 action:(id)arg4 birthday:(id)arg5 timeZone:(id)arg6 email:(id)arg7 password:(id)arg8 phoneNumber:(id)arg9 code:(id)arg10 deviceid:(id)arg11 dtoken1i:(id)arg12 dsig:(id)arg13 otpSecret:(id)arg14 privacySetting:(id)arg15 searchable:(id)arg16 storyFriendsToBlock:(id)arg17 notificationSoundSetting:(id)arg18 notificationPrivacy:(id)arg19 ringingSound:(id)arg20;

// Remaining properties
@property(readonly, copy) NSString *debugDescription;
@property(readonly) unsigned long long hash;
@property(readonly) Class superclass;

@end

