//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "NSObject.h"

@class NSString;

@interface SOJUIdentitySuggestionPlacementReasonPairDeprecatedBuilder : NSObject
{
    NSString *_placement;
    NSString *_reason;
}

+ (id)withJUIdentitySuggestionPlacementReasonPairDeprecated:(id)arg1;
- (void).cxx_destruct;
- (id)setReason:(id)arg1;
- (id)setPlacement:(id)arg1;
- (id)build;

@end

