//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIButton.h"

@class BCOV_RACCommand;

@interface UIButton (RACCommandSupport)
- (void)BCOV_rac_commandPerformAction:(id)arg1;
- (void)BCOV_rac_hijackActionAndTargetIfNeeded;
@property(retain, nonatomic) BCOV_RACCommand *BCOV_rac_command;
@end

