//
//     Generated by class-dump 3.5 (64 bit).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2013 by Steve Nygard.
//

#import "UIImagePickerController.h"

@class BCOV_RACDelegateProxy;

@interface UIImagePickerController (RACSignalSupport)
- (id)BCOV_rac_imageSelectedSignal;
@property(readonly, nonatomic) BCOV_RACDelegateProxy *BCOV_rac_delegateProxy;
@end

